set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[9]}]
set_property MARK_DEBUG true [get_nets unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TLAST]
set_property MARK_DEBUG true [get_nets unusual_s2mm_sys_i/counter_TVALID]
set_property MARK_DEBUG true [get_nets unusual_s2mm_sys_i/counter_TREADY]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list unusual_s2mm_sys_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[0]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[1]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[2]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[3]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[4]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[5]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[6]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[7]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[8]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[9]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[10]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[11]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[12]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[13]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[14]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[15]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[16]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[17]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[18]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[19]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[20]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[21]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[22]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[23]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[24]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[25]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[26]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[27]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[28]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[29]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[30]} {unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list unusual_s2mm_sys_i/counter_stream_unusual_s2mm_hls_0_counter_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list unusual_s2mm_sys_i/counter_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list unusual_s2mm_sys_i/counter_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
