#pragma line 1 "lab2/hamming_window.c" ::: 0
#pragma line 1 "lab2/hamming_window.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 6 "<command line>" 2 ::: 190
#pragma line 1 "<built-in>" 2 ::: 191
#pragma line 1 "lab2/hamming_window.c" 2 ::: 192
#pragma line 1 "lab2/hamming_window.h" 1 ::: 238
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 287
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 321
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 348
#pragma line 122 "/usr/include/features.h" 3 4 ::: 444
#pragma line 146 "/usr/include/features.h" 3 4 ::: 461
#pragma line 177 "/usr/include/features.h" 3 4 ::: 470
#pragma line 326 "/usr/include/features.h" 3 4 ::: 497
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 534
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 580
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 598
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 604
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 608
#pragma line 150 "/usr/include/sys/cdefs.h" 3 4 ::: 618
#pragma line 168 "/usr/include/sys/cdefs.h" 3 4 ::: 622
#pragma line 191 "/usr/include/sys/cdefs.h" 3 4 ::: 632
#pragma line 235 "/usr/include/sys/cdefs.h" 3 4 ::: 669
#pragma line 288 "/usr/include/sys/cdefs.h" 3 4 ::: 710
#pragma line 324 "/usr/include/sys/cdefs.h" 3 4 ::: 720
#pragma line 334 "/usr/include/sys/cdefs.h" 3 4 ::: 723
#pragma line 373 "/usr/include/sys/cdefs.h" 3 4 ::: 740
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 741
#pragma line 374 "/usr/include/sys/cdefs.h" 2 3 4 ::: 743
#pragma line 362 "/usr/include/features.h" 2 3 4 ::: 744
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 769
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 774
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 776
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 781
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 786
#pragma line 386 "/usr/include/features.h" 2 3 4 ::: 787
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 788
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 789
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 808
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 809
#pragma line 29 "/usr/include/stdint.h" 2 3 4 ::: 811
#pragma line 117 "/usr/include/stdint.h" 3 4 ::: 892
#pragma line 133 "/usr/include/stdint.h" 3 4 ::: 900
#pragma line 145 "/usr/include/stdint.h" 3 4 ::: 905
#pragma line 157 "/usr/include/stdint.h" 3 4 ::: 908
#pragma line 205 "/usr/include/stdint.h" 3 4 ::: 948
#pragma line 216 "/usr/include/stdint.h" 3 4 ::: 950
#pragma line 228 "/usr/include/stdint.h" 3 4 ::: 952
#pragma line 240 "/usr/include/stdint.h" 3 4 ::: 954
#pragma line 260 "/usr/include/stdint.h" 3 4 ::: 967
#pragma line 299 "/usr/include/stdint.h" 3 4 ::: 998
#pragma line 309 "/usr/include/stdint.h" 3 4 ::: 1000
#pragma line 34 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 1002
#pragma line 49 "lab2/hamming_window.h" 2 ::: 1003
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 1004
#pragma line 32 "/usr/include/math.h" 3 4 ::: 1028
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 1032
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 1059
#pragma line 1 "/usr/include/bits/huge_valf.h" 1 3 4 ::: 1061
#pragma line 37 "/usr/include/math.h" 2 3 4 ::: 1088
#pragma line 1 "/usr/include/bits/huge_vall.h" 1 3 4 ::: 1089
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 1109
#pragma line 1 "/usr/include/bits/inf.h" 1 3 4 ::: 1113
#pragma line 41 "/usr/include/math.h" 2 3 4 ::: 1138
#pragma line 1 "/usr/include/bits/nan.h" 1 3 4 ::: 1142
#pragma line 44 "/usr/include/math.h" 2 3 4 ::: 1168
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 1173
#pragma line 26 "/usr/include/bits/mathdef.h" 3 4 ::: 1191
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1192
#pragma line 27 "/usr/include/bits/mathdef.h" 2 3 4 ::: 1194
#pragma line 44 "/usr/include/bits/mathdef.h" 3 4 ::: 1202
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 1204
#pragma line 71 "/usr/include/math.h" 3 4 ::: 1210
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1211
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1289
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1319
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 1557
#pragma line 94 "/usr/include/math.h" 3 4 ::: 1568
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1569
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1647
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1677
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1915
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1916
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1917
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1995
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 2025
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 2263
#pragma line 156 "/usr/include/math.h" 3 4 ::: 2264
#pragma line 224 "/usr/include/math.h" 3 4 ::: 2322
#pragma line 236 "/usr/include/math.h" 3 4 ::: 2324
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2326
#pragma line 264 "/usr/include/math.h" 3 4 ::: 2332
#pragma line 276 "/usr/include/math.h" 3 4 ::: 2334
#pragma line 355 "/usr/include/math.h" 3 4 ::: 2402
#pragma line 372 "/usr/include/math.h" 3 4 ::: 2404
#pragma line 392 "/usr/include/math.h" 3 4 ::: 2408
#pragma line 414 "/usr/include/math.h" 3 4 ::: 2423
#pragma line 50 "lab2/hamming_window.h" 2 ::: 2473
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 1 ::: 2498
#pragma line 62 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 2551
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2552
#pragma line 31 "/usr/include/string.h" 3 4 ::: 2575
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2580
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2621
#pragma line 35 "/usr/include/string.h" 2 3 4 ::: 2624
#pragma line 95 "/usr/include/string.h" 3 4 ::: 2662
#pragma line 127 "/usr/include/string.h" 3 4 ::: 2665
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2702
#pragma line 163 "/usr/include/string.h" 2 3 4 ::: 2746
#pragma line 211 "/usr/include/string.h" 3 4 ::: 2769
#pragma line 235 "/usr/include/string.h" 3 4 ::: 2771
#pragma line 262 "/usr/include/string.h" 3 4 ::: 2776
#pragma line 282 "/usr/include/string.h" 3 4 ::: 2779
#pragma line 314 "/usr/include/string.h" 3 4 ::: 2789
#pragma line 342 "/usr/include/string.h" 3 4 ::: 2794
#pragma line 398 "/usr/include/string.h" 3 4 ::: 2815
#pragma line 444 "/usr/include/string.h" 3 4 ::: 2846
#pragma line 489 "/usr/include/string.h" 3 4 ::: 2869
#pragma line 517 "/usr/include/string.h" 3 4 ::: 2875
#pragma line 535 "/usr/include/string.h" 3 4 ::: 2886
#pragma line 557 "/usr/include/string.h" 3 4 ::: 2894
#pragma line 63 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 2920
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 2921
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 2944
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2945
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2970
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 2973
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 2975
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3004
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 3006
#pragma line 70 "/usr/include/bits/types.h" 3 4 ::: 3033
#pragma line 126 "/usr/include/bits/types.h" 3 4 ::: 3062
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 3069
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 3088
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 3091
#pragma line 132 "/usr/include/bits/types.h" 2 3 4 ::: 3093
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 3155
#pragma line 64 "/usr/include/stdio.h" 3 4 ::: 3169
#pragma line 75 "/usr/include/stdio.h" 3 4 ::: 3172
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 3173
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 3206
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3222
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3247
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 3250
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 3255
#pragma line 82 "/usr/include/wchar.h" 3 4 ::: 3278
#pragma line 895 "/usr/include/wchar.h" 3 4 ::: 3299
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 3302
#pragma line 53 "/usr/include/_G_config.h" 3 4 ::: 3314
#pragma line 82 "/usr/include/_G_config.h" 3 4 ::: 3324
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 3331
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 3333
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 3337
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 3386
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 3387
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 3389
#pragma line 150 "/usr/include/libio.h" 3 4 ::: 3395
#pragma line 170 "/usr/include/libio.h" 3 4 ::: 3397
#pragma line 203 "/usr/include/libio.h" 3 4 ::: 3421
#pragma line 271 "/usr/include/libio.h" 3 4 ::: 3432
#pragma line 319 "/usr/include/libio.h" 3 4 ::: 3473
#pragma line 328 "/usr/include/libio.h" 3 4 ::: 3475
#pragma line 360 "/usr/include/libio.h" 3 4 ::: 3497
#pragma line 416 "/usr/include/libio.h" 3 4 ::: 3523
#pragma line 460 "/usr/include/libio.h" 3 4 ::: 3527
#pragma line 490 "/usr/include/libio.h" 3 4 ::: 3542
#pragma line 76 "/usr/include/stdio.h" 2 3 4 ::: 3554
#pragma line 91 "/usr/include/stdio.h" 3 4 ::: 3560
#pragma line 103 "/usr/include/stdio.h" 3 4 ::: 3562
#pragma line 120 "/usr/include/stdio.h" 3 4 ::: 3572
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 3615
#pragma line 162 "/usr/include/stdio.h" 2 3 4 ::: 3633
#pragma line 207 "/usr/include/stdio.h" 3 4 ::: 3667
#pragma line 267 "/usr/include/stdio.h" 3 4 ::: 3713
#pragma line 304 "/usr/include/stdio.h" 3 4 ::: 3727
#pragma line 317 "/usr/include/stdio.h" 3 4 ::: 3730
#pragma line 410 "/usr/include/stdio.h" 3 4 ::: 3806
#pragma line 471 "/usr/include/stdio.h" 3 4 ::: 3850
#pragma line 531 "/usr/include/stdio.h" 3 4 ::: 3891
#pragma line 650 "/usr/include/stdio.h" 3 4 ::: 3996
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 4059
#pragma line 789 "/usr/include/stdio.h" 3 4 ::: 4108
#pragma line 820 "/usr/include/stdio.h" 3 4 ::: 4119
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 4149
#pragma line 849 "/usr/include/stdio.h" 2 3 4 ::: 4178
#pragma line 905 "/usr/include/stdio.h" 3 4 ::: 4211
#pragma line 926 "/usr/include/stdio.h" 3 4 ::: 4223
#pragma line 64 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 4226
#pragma line 77 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 4227
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 4228
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 1 ::: 4286
#pragma line 97 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 4340
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 4341
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 5380
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 5381
#pragma line 99 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 6408
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 6409
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 6410
#pragma line 109 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 7449
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 7450
#pragma line 110 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 8477
#pragma line 131 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 8478
#pragma line 58 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 8481
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" 1 ::: 8482
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8535
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8537
#pragma line 129 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8539
#pragma line 143 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8544
#pragma line 156 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8547
#pragma line 192 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8549
#pragma line 59 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 8551
#pragma line 85 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" ::: 8552
#pragma line 78 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 8554
#pragma line 74 "lab2/hamming_window.h" 2 ::: 8555
#pragma line 46 "lab2/hamming_window.c" 2 ::: 8560
