#pragma line 1 "lab2/hamming_window.c" ::: -10
#pragma line 1 "lab2/hamming_window.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 6 "<command line>" 2 ::: 180
#pragma line 1 "<built-in>" 2 ::: 181
#pragma line 1 "lab2/hamming_window.c" 2 ::: 182
#pragma line 1 "lab2/hamming_window.h" 1 ::: 228
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 277
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 311
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 338
#pragma line 122 "/usr/include/features.h" 3 4 ::: 434
#pragma line 146 "/usr/include/features.h" 3 4 ::: 451
#pragma line 177 "/usr/include/features.h" 3 4 ::: 460
#pragma line 326 "/usr/include/features.h" 3 4 ::: 487
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 524
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 570
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 588
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 594
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 598
#pragma line 150 "/usr/include/sys/cdefs.h" 3 4 ::: 608
#pragma line 168 "/usr/include/sys/cdefs.h" 3 4 ::: 612
#pragma line 191 "/usr/include/sys/cdefs.h" 3 4 ::: 622
#pragma line 235 "/usr/include/sys/cdefs.h" 3 4 ::: 659
#pragma line 288 "/usr/include/sys/cdefs.h" 3 4 ::: 700
#pragma line 324 "/usr/include/sys/cdefs.h" 3 4 ::: 710
#pragma line 334 "/usr/include/sys/cdefs.h" 3 4 ::: 713
#pragma line 373 "/usr/include/sys/cdefs.h" 3 4 ::: 730
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 731
#pragma line 374 "/usr/include/sys/cdefs.h" 2 3 4 ::: 733
#pragma line 362 "/usr/include/features.h" 2 3 4 ::: 734
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 759
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 764
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 766
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 771
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 776
#pragma line 386 "/usr/include/features.h" 2 3 4 ::: 777
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 778
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 779
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 798
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 799
#pragma line 29 "/usr/include/stdint.h" 2 3 4 ::: 801
#pragma line 117 "/usr/include/stdint.h" 3 4 ::: 882
#pragma line 133 "/usr/include/stdint.h" 3 4 ::: 890
#pragma line 145 "/usr/include/stdint.h" 3 4 ::: 895
#pragma line 157 "/usr/include/stdint.h" 3 4 ::: 898
#pragma line 205 "/usr/include/stdint.h" 3 4 ::: 938
#pragma line 216 "/usr/include/stdint.h" 3 4 ::: 940
#pragma line 228 "/usr/include/stdint.h" 3 4 ::: 942
#pragma line 240 "/usr/include/stdint.h" 3 4 ::: 944
#pragma line 260 "/usr/include/stdint.h" 3 4 ::: 957
#pragma line 299 "/usr/include/stdint.h" 3 4 ::: 988
#pragma line 309 "/usr/include/stdint.h" 3 4 ::: 990
#pragma line 34 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 992
#pragma line 49 "lab2/hamming_window.h" 2 ::: 993
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 994
#pragma line 32 "/usr/include/math.h" 3 4 ::: 1018
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 1022
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 1049
#pragma line 1 "/usr/include/bits/huge_valf.h" 1 3 4 ::: 1051
#pragma line 37 "/usr/include/math.h" 2 3 4 ::: 1078
#pragma line 1 "/usr/include/bits/huge_vall.h" 1 3 4 ::: 1079
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 1099
#pragma line 1 "/usr/include/bits/inf.h" 1 3 4 ::: 1103
#pragma line 41 "/usr/include/math.h" 2 3 4 ::: 1128
#pragma line 1 "/usr/include/bits/nan.h" 1 3 4 ::: 1132
#pragma line 44 "/usr/include/math.h" 2 3 4 ::: 1158
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 1163
#pragma line 26 "/usr/include/bits/mathdef.h" 3 4 ::: 1181
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1182
#pragma line 27 "/usr/include/bits/mathdef.h" 2 3 4 ::: 1184
#pragma line 44 "/usr/include/bits/mathdef.h" 3 4 ::: 1192
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 1194
#pragma line 71 "/usr/include/math.h" 3 4 ::: 1200
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1201
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1279
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1309
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 1547
#pragma line 94 "/usr/include/math.h" 3 4 ::: 1558
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1559
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1637
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1667
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1905
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1906
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1907
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1985
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 2015
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 2253
#pragma line 156 "/usr/include/math.h" 3 4 ::: 2254
#pragma line 224 "/usr/include/math.h" 3 4 ::: 2312
#pragma line 236 "/usr/include/math.h" 3 4 ::: 2314
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2316
#pragma line 264 "/usr/include/math.h" 3 4 ::: 2322
#pragma line 276 "/usr/include/math.h" 3 4 ::: 2324
#pragma line 355 "/usr/include/math.h" 3 4 ::: 2392
#pragma line 372 "/usr/include/math.h" 3 4 ::: 2394
#pragma line 392 "/usr/include/math.h" 3 4 ::: 2398
#pragma line 414 "/usr/include/math.h" 3 4 ::: 2413
#pragma line 50 "lab2/hamming_window.h" 2 ::: 2463
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 1 ::: 2488
#pragma line 62 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 2541
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2542
#pragma line 31 "/usr/include/string.h" 3 4 ::: 2565
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2570
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2611
#pragma line 35 "/usr/include/string.h" 2 3 4 ::: 2614
#pragma line 95 "/usr/include/string.h" 3 4 ::: 2652
#pragma line 127 "/usr/include/string.h" 3 4 ::: 2655
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2692
#pragma line 163 "/usr/include/string.h" 2 3 4 ::: 2736
#pragma line 211 "/usr/include/string.h" 3 4 ::: 2759
#pragma line 235 "/usr/include/string.h" 3 4 ::: 2761
#pragma line 262 "/usr/include/string.h" 3 4 ::: 2766
#pragma line 282 "/usr/include/string.h" 3 4 ::: 2769
#pragma line 314 "/usr/include/string.h" 3 4 ::: 2779
#pragma line 342 "/usr/include/string.h" 3 4 ::: 2784
#pragma line 398 "/usr/include/string.h" 3 4 ::: 2805
#pragma line 444 "/usr/include/string.h" 3 4 ::: 2836
#pragma line 489 "/usr/include/string.h" 3 4 ::: 2859
#pragma line 517 "/usr/include/string.h" 3 4 ::: 2865
#pragma line 535 "/usr/include/string.h" 3 4 ::: 2876
#pragma line 557 "/usr/include/string.h" 3 4 ::: 2884
#pragma line 63 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 2910
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 2911
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 2934
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2935
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2960
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 2963
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 2965
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 2994
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 2996
#pragma line 70 "/usr/include/bits/types.h" 3 4 ::: 3023
#pragma line 126 "/usr/include/bits/types.h" 3 4 ::: 3052
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 3059
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 3078
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 3081
#pragma line 132 "/usr/include/bits/types.h" 2 3 4 ::: 3083
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 3145
#pragma line 64 "/usr/include/stdio.h" 3 4 ::: 3159
#pragma line 75 "/usr/include/stdio.h" 3 4 ::: 3162
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 3163
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 3196
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3212
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3237
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 3240
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 3245
#pragma line 82 "/usr/include/wchar.h" 3 4 ::: 3268
#pragma line 895 "/usr/include/wchar.h" 3 4 ::: 3289
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 3292
#pragma line 53 "/usr/include/_G_config.h" 3 4 ::: 3304
#pragma line 82 "/usr/include/_G_config.h" 3 4 ::: 3314
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 3321
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 3323
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 3327
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 3376
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 3377
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 3379
#pragma line 150 "/usr/include/libio.h" 3 4 ::: 3385
#pragma line 170 "/usr/include/libio.h" 3 4 ::: 3387
#pragma line 203 "/usr/include/libio.h" 3 4 ::: 3411
#pragma line 271 "/usr/include/libio.h" 3 4 ::: 3422
#pragma line 319 "/usr/include/libio.h" 3 4 ::: 3463
#pragma line 328 "/usr/include/libio.h" 3 4 ::: 3465
#pragma line 360 "/usr/include/libio.h" 3 4 ::: 3487
#pragma line 416 "/usr/include/libio.h" 3 4 ::: 3513
#pragma line 460 "/usr/include/libio.h" 3 4 ::: 3517
#pragma line 490 "/usr/include/libio.h" 3 4 ::: 3532
#pragma line 76 "/usr/include/stdio.h" 2 3 4 ::: 3544
#pragma line 91 "/usr/include/stdio.h" 3 4 ::: 3550
#pragma line 103 "/usr/include/stdio.h" 3 4 ::: 3552
#pragma line 120 "/usr/include/stdio.h" 3 4 ::: 3562
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 3605
#pragma line 162 "/usr/include/stdio.h" 2 3 4 ::: 3623
#pragma line 207 "/usr/include/stdio.h" 3 4 ::: 3657
#pragma line 267 "/usr/include/stdio.h" 3 4 ::: 3703
#pragma line 304 "/usr/include/stdio.h" 3 4 ::: 3717
#pragma line 317 "/usr/include/stdio.h" 3 4 ::: 3720
#pragma line 410 "/usr/include/stdio.h" 3 4 ::: 3796
#pragma line 471 "/usr/include/stdio.h" 3 4 ::: 3840
#pragma line 531 "/usr/include/stdio.h" 3 4 ::: 3881
#pragma line 650 "/usr/include/stdio.h" 3 4 ::: 3986
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 4049
#pragma line 789 "/usr/include/stdio.h" 3 4 ::: 4098
#pragma line 820 "/usr/include/stdio.h" 3 4 ::: 4109
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 4139
#pragma line 849 "/usr/include/stdio.h" 2 3 4 ::: 4168
#pragma line 905 "/usr/include/stdio.h" 3 4 ::: 4201
#pragma line 926 "/usr/include/stdio.h" 3 4 ::: 4213
#pragma line 64 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 4216
#pragma line 77 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 4217
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 4218
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 1 ::: 4276
#pragma line 97 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 4330
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 4331
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 5370
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 5371
#pragma line 99 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 6398
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 6399
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 6400
#pragma line 109 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 7439
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 7440
#pragma line 110 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 8467
#pragma line 131 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 8468
#pragma line 58 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 8471
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" 1 ::: 8472
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8525
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8527
#pragma line 129 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8529
#pragma line 143 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8534
#pragma line 156 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8537
#pragma line 192 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 8539
#pragma line 59 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 8541
#pragma line 85 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" ::: 8542
#pragma line 78 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 8544
#pragma line 74 "lab2/hamming_window.h" 2 ::: 8545
#pragma line 46 "lab2/hamming_window.c" 2 ::: 8550
