// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XCOUNTER_STREAM_UNUSUAL_S2MM_HLS_H
#define XCOUNTER_STREAM_UNUSUAL_S2MM_HLS_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xcounter_stream_unusual_s2mm_hls_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Cpucontrol_BaseAddress;
} XCounter_stream_unusual_s2mm_hls_Config;
#endif

typedef struct {
    u32 Cpucontrol_BaseAddress;
    u32 IsReady;
} XCounter_stream_unusual_s2mm_hls;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XCounter_stream_unusual_s2mm_hls_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XCounter_stream_unusual_s2mm_hls_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XCounter_stream_unusual_s2mm_hls_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XCounter_stream_unusual_s2mm_hls_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XCounter_stream_unusual_s2mm_hls_Initialize(XCounter_stream_unusual_s2mm_hls *InstancePtr, u16 DeviceId);
XCounter_stream_unusual_s2mm_hls_Config* XCounter_stream_unusual_s2mm_hls_LookupConfig(u16 DeviceId);
int XCounter_stream_unusual_s2mm_hls_CfgInitialize(XCounter_stream_unusual_s2mm_hls *InstancePtr, XCounter_stream_unusual_s2mm_hls_Config *ConfigPtr);
#else
int XCounter_stream_unusual_s2mm_hls_Initialize(XCounter_stream_unusual_s2mm_hls *InstancePtr, const char* InstanceName);
int XCounter_stream_unusual_s2mm_hls_Release(XCounter_stream_unusual_s2mm_hls *InstancePtr);
#endif

void XCounter_stream_unusual_s2mm_hls_Start(XCounter_stream_unusual_s2mm_hls *InstancePtr);
u32 XCounter_stream_unusual_s2mm_hls_IsDone(XCounter_stream_unusual_s2mm_hls *InstancePtr);
u32 XCounter_stream_unusual_s2mm_hls_IsIdle(XCounter_stream_unusual_s2mm_hls *InstancePtr);
u32 XCounter_stream_unusual_s2mm_hls_IsReady(XCounter_stream_unusual_s2mm_hls *InstancePtr);
void XCounter_stream_unusual_s2mm_hls_EnableAutoRestart(XCounter_stream_unusual_s2mm_hls *InstancePtr);
void XCounter_stream_unusual_s2mm_hls_DisableAutoRestart(XCounter_stream_unusual_s2mm_hls *InstancePtr);

void XCounter_stream_unusual_s2mm_hls_Set_resolution(XCounter_stream_unusual_s2mm_hls *InstancePtr, u32 Data);
u32 XCounter_stream_unusual_s2mm_hls_Get_resolution(XCounter_stream_unusual_s2mm_hls *InstancePtr);
void XCounter_stream_unusual_s2mm_hls_Set_numIteration(XCounter_stream_unusual_s2mm_hls *InstancePtr, u32 Data);
u32 XCounter_stream_unusual_s2mm_hls_Get_numIteration(XCounter_stream_unusual_s2mm_hls *InstancePtr);

void XCounter_stream_unusual_s2mm_hls_InterruptGlobalEnable(XCounter_stream_unusual_s2mm_hls *InstancePtr);
void XCounter_stream_unusual_s2mm_hls_InterruptGlobalDisable(XCounter_stream_unusual_s2mm_hls *InstancePtr);
void XCounter_stream_unusual_s2mm_hls_InterruptEnable(XCounter_stream_unusual_s2mm_hls *InstancePtr, u32 Mask);
void XCounter_stream_unusual_s2mm_hls_InterruptDisable(XCounter_stream_unusual_s2mm_hls *InstancePtr, u32 Mask);
void XCounter_stream_unusual_s2mm_hls_InterruptClear(XCounter_stream_unusual_s2mm_hls *InstancePtr, u32 Mask);
u32 XCounter_stream_unusual_s2mm_hls_InterruptGetEnabled(XCounter_stream_unusual_s2mm_hls *InstancePtr);
u32 XCounter_stream_unusual_s2mm_hls_InterruptGetStatus(XCounter_stream_unusual_s2mm_hls *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
