# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2015.3
# Copyright (C) 2015 Xilinx Inc. All rights reserved.
# 
# ==============================================================


/opt/Xilinx/Vivado_HLS/2015.3/../../Vivado/2015.3/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7k160tfbg484-1 ../xilinx_com_hls_axi_interfaces_1_0.zip
