webtalk_init -webtalk_dir /mnt/hgfs/GitHub/vivado_hls/testing/axi_stream_testing_hls/axi_stream_have_last_signal_xsdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 31 02:13:16 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "v6h7ig8mo62tk6df71ihlbmtjv" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.3_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1472435620000" -context "sdk\\\\hardware/1472435620000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1472435620000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1472435620000"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.3" -context "sdk\\\\hardware/1472435620000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1472435620000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1472435620000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1472435620000"
webtalk_add_data -client sdk -key uid -value "1472435641000" -context "sdk\\\\bsp/1472435641000"
webtalk_add_data -client sdk -key hwid -value "1472435620000" -context "sdk\\\\bsp/1472435641000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1472435641000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1472435641000"
webtalk_add_data -client sdk -key uid -value "1472435738000" -context "sdk\\\\application/1472435738000"
webtalk_add_data -client sdk -key hwid -value "1472435620000" -context "sdk\\\\application/1472435738000"
webtalk_add_data -client sdk -key bspid -value "1472435641000" -context "sdk\\\\application/1472435738000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1472435738000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1472435738000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1472435738000"
webtalk_transmit -clientid 3104775405 -regid "" -xml /mnt/hgfs/GitHub/vivado_hls/testing/axi_stream_testing_hls/axi_stream_have_last_signal_xsdk/webtalk/usage_statistics_ext_sdk.xml -html /mnt/hgfs/GitHub/vivado_hls/testing/axi_stream_testing_hls/axi_stream_have_last_signal_xsdk/webtalk/usage_statistics_ext_sdk.html -wdm /mnt/hgfs/GitHub/vivado_hls/testing/axi_stream_testing_hls/axi_stream_have_last_signal_xsdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
