-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.3
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_xfft2real is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    din_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    din_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    dout_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    din_TVALID : IN STD_LOGIC;
    din_TREADY : OUT STD_LOGIC;
    dout_V_TVALID : OUT STD_LOGIC;
    dout_V_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC );
end;


architecture behav of hls_xfft2real is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hls_xfft2real,hls_ip_2015_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.420000,HLS_SYN_LAT=1036,HLS_SYN_TPT=525,HLS_SYN_MEM=10,HLS_SYN_DSP=4,HLS_SYN_FF=840,HLS_SYN_LUT=640}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_true : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal descramble_buf_0_M_real_V_i_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_0_M_real_V_i_ce0 : STD_LOGIC;
    signal descramble_buf_0_M_real_V_i_we0 : STD_LOGIC;
    signal descramble_buf_0_M_real_V_i_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_real_V_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_real_V_i_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_0_M_real_V_i_ce1 : STD_LOGIC;
    signal descramble_buf_0_M_real_V_i_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_real_V_t_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_0_M_real_V_t_ce0 : STD_LOGIC;
    signal descramble_buf_0_M_real_V_t_we0 : STD_LOGIC;
    signal descramble_buf_0_M_real_V_t_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_real_V_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_real_V_t_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_0_M_real_V_t_ce1 : STD_LOGIC;
    signal descramble_buf_0_M_real_V_t_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_real_V_U_ap_dummy_ce : STD_LOGIC;
    signal descramble_buf_1_M_real_V_i_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_1_M_real_V_i_ce0 : STD_LOGIC;
    signal descramble_buf_1_M_real_V_i_we0 : STD_LOGIC;
    signal descramble_buf_1_M_real_V_i_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_real_V_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_real_V_i_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_1_M_real_V_i_ce1 : STD_LOGIC;
    signal descramble_buf_1_M_real_V_i_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_real_V_t_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_1_M_real_V_t_ce0 : STD_LOGIC;
    signal descramble_buf_1_M_real_V_t_we0 : STD_LOGIC;
    signal descramble_buf_1_M_real_V_t_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_real_V_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_real_V_t_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_1_M_real_V_t_ce1 : STD_LOGIC;
    signal descramble_buf_1_M_real_V_t_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_real_V_U_ap_dummy_ce : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_i_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_0_M_imag_V_i_ce0 : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_i_we0 : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_i_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_imag_V_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_imag_V_i_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_0_M_imag_V_i_ce1 : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_i_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_imag_V_t_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_0_M_imag_V_t_ce0 : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_t_we0 : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_t_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_imag_V_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_imag_V_t_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_0_M_imag_V_t_ce1 : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_t_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_imag_V_U_ap_dummy_ce : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_i_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_1_M_imag_V_i_ce0 : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_i_we0 : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_i_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_imag_V_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_imag_V_i_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_1_M_imag_V_i_ce1 : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_i_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_imag_V_t_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_1_M_imag_V_t_ce0 : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_t_we0 : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_t_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_imag_V_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_imag_V_t_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal descramble_buf_1_M_imag_V_t_ce1 : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_t_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_imag_V_U_ap_dummy_ce : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_start : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_continue : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_idle : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_ready : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_ce0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_we0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_ce0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_we0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TVALID : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TREADY : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_ce0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_we0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_ce0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_we0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status : STD_LOGIC;
    signal ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status : STD_LOGIC := '0';
    signal ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status : STD_LOGIC;
    signal ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status : STD_LOGIC;
    signal ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status : STD_LOGIC := '0';
    signal ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status : STD_LOGIC;
    signal ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status : STD_LOGIC;
    signal ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status : STD_LOGIC := '0';
    signal ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status : STD_LOGIC;
    signal ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status : STD_LOGIC;
    signal ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status : STD_LOGIC := '0';
    signal ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_start : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_done : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_continue : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_idle : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_ready : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_dout_V_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_dout_V_TVALID : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_dout_V_TREADY : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_ce0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_ce1 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_ce0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_ce1 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_ce0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_ce1 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_ce0 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_ce1 : STD_LOGIC;
    signal hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_hs_continue : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_i_full_n : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_i_write : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_t_empty_n : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_t_read : STD_LOGIC;
    signal descramble_buf_0_M_imag_V_t_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_imag_V_t_we1 : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_i_full_n : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_i_write : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_t_empty_n : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_t_read : STD_LOGIC;
    signal descramble_buf_1_M_imag_V_t_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_imag_V_t_we1 : STD_LOGIC;
    signal descramble_buf_0_M_real_V_i_full_n : STD_LOGIC;
    signal descramble_buf_0_M_real_V_i_write : STD_LOGIC;
    signal descramble_buf_0_M_real_V_t_empty_n : STD_LOGIC;
    signal descramble_buf_0_M_real_V_t_read : STD_LOGIC;
    signal descramble_buf_0_M_real_V_t_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_real_V_t_we1 : STD_LOGIC;
    signal descramble_buf_1_M_real_V_i_full_n : STD_LOGIC;
    signal descramble_buf_1_M_real_V_i_write : STD_LOGIC;
    signal descramble_buf_1_M_real_V_t_empty_n : STD_LOGIC;
    signal descramble_buf_1_M_real_V_t_read : STD_LOGIC;
    signal descramble_buf_1_M_real_V_t_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_real_V_t_we1 : STD_LOGIC;
    signal ap_reg_procdone_hls_xfft2real_Loop_realfft_be_buffer_proc_U0 : STD_LOGIC := '0';
    signal ap_sig_hs_done : STD_LOGIC;
    signal ap_reg_procdone_hls_xfft2real_Loop_realfft_be_descramble_pro_U0 : STD_LOGIC := '0';
    signal ap_CS : STD_LOGIC;
    signal ap_sig_top_allready : STD_LOGIC;

    component hls_xfft2real_Loop_realfft_be_buffer_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        descramble_buf_0_M_imag_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_imag_V_ce0 : OUT STD_LOGIC;
        descramble_buf_0_M_imag_V_we0 : OUT STD_LOGIC;
        descramble_buf_0_M_imag_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_imag_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_imag_V_ce0 : OUT STD_LOGIC;
        descramble_buf_1_M_imag_V_we0 : OUT STD_LOGIC;
        descramble_buf_1_M_imag_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        din_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        din_TVALID : IN STD_LOGIC;
        din_TREADY : OUT STD_LOGIC;
        din_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        descramble_buf_0_M_real_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_real_V_ce0 : OUT STD_LOGIC;
        descramble_buf_0_M_real_V_we0 : OUT STD_LOGIC;
        descramble_buf_0_M_real_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_real_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_real_V_ce0 : OUT STD_LOGIC;
        descramble_buf_1_M_real_V_we0 : OUT STD_LOGIC;
        descramble_buf_1_M_real_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component hls_xfft2real_Loop_realfft_be_descramble_pro IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        dout_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        dout_V_TVALID : OUT STD_LOGIC;
        dout_V_TREADY : IN STD_LOGIC;
        descramble_buf_0_M_imag_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_imag_V_ce0 : OUT STD_LOGIC;
        descramble_buf_0_M_imag_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_0_M_imag_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_imag_V_ce1 : OUT STD_LOGIC;
        descramble_buf_0_M_imag_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_imag_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_imag_V_ce0 : OUT STD_LOGIC;
        descramble_buf_1_M_imag_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_imag_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_imag_V_ce1 : OUT STD_LOGIC;
        descramble_buf_1_M_imag_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_0_M_real_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_real_V_ce0 : OUT STD_LOGIC;
        descramble_buf_0_M_real_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_0_M_real_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_real_V_ce1 : OUT STD_LOGIC;
        descramble_buf_0_M_real_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_real_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_real_V_ce0 : OUT STD_LOGIC;
        descramble_buf_1_M_real_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_real_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_real_V_ce1 : OUT STD_LOGIC;
        descramble_buf_1_M_real_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component hls_xfft2real_descramble_buf_0_M_real_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        i_address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        i_ce1 : IN STD_LOGIC;
        i_q1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        t_address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        t_ce1 : IN STD_LOGIC;
        t_q1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;



begin
    descramble_buf_0_M_real_V_U : component hls_xfft2real_descramble_buf_0_M_real_V
    generic map (
        DataWidth => 16,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => descramble_buf_0_M_real_V_i_address0,
        i_ce0 => descramble_buf_0_M_real_V_i_ce0,
        i_we0 => descramble_buf_0_M_real_V_i_we0,
        i_d0 => descramble_buf_0_M_real_V_i_d0,
        i_q0 => descramble_buf_0_M_real_V_i_q0,
        i_address1 => descramble_buf_0_M_real_V_i_address1,
        i_ce1 => descramble_buf_0_M_real_V_i_ce1,
        i_q1 => descramble_buf_0_M_real_V_i_q1,
        t_address0 => descramble_buf_0_M_real_V_t_address0,
        t_ce0 => descramble_buf_0_M_real_V_t_ce0,
        t_we0 => descramble_buf_0_M_real_V_t_we0,
        t_d0 => descramble_buf_0_M_real_V_t_d0,
        t_q0 => descramble_buf_0_M_real_V_t_q0,
        t_address1 => descramble_buf_0_M_real_V_t_address1,
        t_ce1 => descramble_buf_0_M_real_V_t_ce1,
        t_q1 => descramble_buf_0_M_real_V_t_q1,
        i_ce => descramble_buf_0_M_real_V_U_ap_dummy_ce,
        t_ce => descramble_buf_0_M_real_V_U_ap_dummy_ce,
        i_full_n => descramble_buf_0_M_real_V_i_full_n,
        i_write => descramble_buf_0_M_real_V_i_write,
        t_empty_n => descramble_buf_0_M_real_V_t_empty_n,
        t_read => descramble_buf_0_M_real_V_t_read);

    descramble_buf_1_M_real_V_U : component hls_xfft2real_descramble_buf_0_M_real_V
    generic map (
        DataWidth => 16,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => descramble_buf_1_M_real_V_i_address0,
        i_ce0 => descramble_buf_1_M_real_V_i_ce0,
        i_we0 => descramble_buf_1_M_real_V_i_we0,
        i_d0 => descramble_buf_1_M_real_V_i_d0,
        i_q0 => descramble_buf_1_M_real_V_i_q0,
        i_address1 => descramble_buf_1_M_real_V_i_address1,
        i_ce1 => descramble_buf_1_M_real_V_i_ce1,
        i_q1 => descramble_buf_1_M_real_V_i_q1,
        t_address0 => descramble_buf_1_M_real_V_t_address0,
        t_ce0 => descramble_buf_1_M_real_V_t_ce0,
        t_we0 => descramble_buf_1_M_real_V_t_we0,
        t_d0 => descramble_buf_1_M_real_V_t_d0,
        t_q0 => descramble_buf_1_M_real_V_t_q0,
        t_address1 => descramble_buf_1_M_real_V_t_address1,
        t_ce1 => descramble_buf_1_M_real_V_t_ce1,
        t_q1 => descramble_buf_1_M_real_V_t_q1,
        i_ce => descramble_buf_1_M_real_V_U_ap_dummy_ce,
        t_ce => descramble_buf_1_M_real_V_U_ap_dummy_ce,
        i_full_n => descramble_buf_1_M_real_V_i_full_n,
        i_write => descramble_buf_1_M_real_V_i_write,
        t_empty_n => descramble_buf_1_M_real_V_t_empty_n,
        t_read => descramble_buf_1_M_real_V_t_read);

    descramble_buf_0_M_imag_V_U : component hls_xfft2real_descramble_buf_0_M_real_V
    generic map (
        DataWidth => 16,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => descramble_buf_0_M_imag_V_i_address0,
        i_ce0 => descramble_buf_0_M_imag_V_i_ce0,
        i_we0 => descramble_buf_0_M_imag_V_i_we0,
        i_d0 => descramble_buf_0_M_imag_V_i_d0,
        i_q0 => descramble_buf_0_M_imag_V_i_q0,
        i_address1 => descramble_buf_0_M_imag_V_i_address1,
        i_ce1 => descramble_buf_0_M_imag_V_i_ce1,
        i_q1 => descramble_buf_0_M_imag_V_i_q1,
        t_address0 => descramble_buf_0_M_imag_V_t_address0,
        t_ce0 => descramble_buf_0_M_imag_V_t_ce0,
        t_we0 => descramble_buf_0_M_imag_V_t_we0,
        t_d0 => descramble_buf_0_M_imag_V_t_d0,
        t_q0 => descramble_buf_0_M_imag_V_t_q0,
        t_address1 => descramble_buf_0_M_imag_V_t_address1,
        t_ce1 => descramble_buf_0_M_imag_V_t_ce1,
        t_q1 => descramble_buf_0_M_imag_V_t_q1,
        i_ce => descramble_buf_0_M_imag_V_U_ap_dummy_ce,
        t_ce => descramble_buf_0_M_imag_V_U_ap_dummy_ce,
        i_full_n => descramble_buf_0_M_imag_V_i_full_n,
        i_write => descramble_buf_0_M_imag_V_i_write,
        t_empty_n => descramble_buf_0_M_imag_V_t_empty_n,
        t_read => descramble_buf_0_M_imag_V_t_read);

    descramble_buf_1_M_imag_V_U : component hls_xfft2real_descramble_buf_0_M_real_V
    generic map (
        DataWidth => 16,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => descramble_buf_1_M_imag_V_i_address0,
        i_ce0 => descramble_buf_1_M_imag_V_i_ce0,
        i_we0 => descramble_buf_1_M_imag_V_i_we0,
        i_d0 => descramble_buf_1_M_imag_V_i_d0,
        i_q0 => descramble_buf_1_M_imag_V_i_q0,
        i_address1 => descramble_buf_1_M_imag_V_i_address1,
        i_ce1 => descramble_buf_1_M_imag_V_i_ce1,
        i_q1 => descramble_buf_1_M_imag_V_i_q1,
        t_address0 => descramble_buf_1_M_imag_V_t_address0,
        t_ce0 => descramble_buf_1_M_imag_V_t_ce0,
        t_we0 => descramble_buf_1_M_imag_V_t_we0,
        t_d0 => descramble_buf_1_M_imag_V_t_d0,
        t_q0 => descramble_buf_1_M_imag_V_t_q0,
        t_address1 => descramble_buf_1_M_imag_V_t_address1,
        t_ce1 => descramble_buf_1_M_imag_V_t_ce1,
        t_q1 => descramble_buf_1_M_imag_V_t_q1,
        i_ce => descramble_buf_1_M_imag_V_U_ap_dummy_ce,
        t_ce => descramble_buf_1_M_imag_V_U_ap_dummy_ce,
        i_full_n => descramble_buf_1_M_imag_V_i_full_n,
        i_write => descramble_buf_1_M_imag_V_i_write,
        t_empty_n => descramble_buf_1_M_imag_V_t_empty_n,
        t_read => descramble_buf_1_M_imag_V_t_read);

    hls_xfft2real_Loop_realfft_be_buffer_proc_U0 : component hls_xfft2real_Loop_realfft_be_buffer_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_start,
        ap_done => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done,
        ap_continue => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_continue,
        ap_idle => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_idle,
        ap_ready => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_ready,
        descramble_buf_0_M_imag_V_address0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_address0,
        descramble_buf_0_M_imag_V_ce0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_ce0,
        descramble_buf_0_M_imag_V_we0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_we0,
        descramble_buf_0_M_imag_V_d0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_d0,
        descramble_buf_1_M_imag_V_address0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_address0,
        descramble_buf_1_M_imag_V_ce0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_ce0,
        descramble_buf_1_M_imag_V_we0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_we0,
        descramble_buf_1_M_imag_V_d0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_d0,
        din_TDATA => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TDATA,
        din_TVALID => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TVALID,
        din_TREADY => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TREADY,
        din_TLAST => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TLAST,
        descramble_buf_0_M_real_V_address0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_address0,
        descramble_buf_0_M_real_V_ce0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_ce0,
        descramble_buf_0_M_real_V_we0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_we0,
        descramble_buf_0_M_real_V_d0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_d0,
        descramble_buf_1_M_real_V_address0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_address0,
        descramble_buf_1_M_real_V_ce0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_ce0,
        descramble_buf_1_M_real_V_we0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_we0,
        descramble_buf_1_M_real_V_d0 => hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_d0);

    hls_xfft2real_Loop_realfft_be_descramble_pro_U0 : component hls_xfft2real_Loop_realfft_be_descramble_pro
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_start,
        ap_done => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_done,
        ap_continue => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_continue,
        ap_idle => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_idle,
        ap_ready => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_ready,
        dout_V_TDATA => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_dout_V_TDATA,
        dout_V_TVALID => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_dout_V_TVALID,
        dout_V_TREADY => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_dout_V_TREADY,
        descramble_buf_0_M_imag_V_address0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_address0,
        descramble_buf_0_M_imag_V_ce0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_ce0,
        descramble_buf_0_M_imag_V_q0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_q0,
        descramble_buf_0_M_imag_V_address1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_address1,
        descramble_buf_0_M_imag_V_ce1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_ce1,
        descramble_buf_0_M_imag_V_q1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_q1,
        descramble_buf_1_M_imag_V_address0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_address0,
        descramble_buf_1_M_imag_V_ce0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_ce0,
        descramble_buf_1_M_imag_V_q0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_q0,
        descramble_buf_1_M_imag_V_address1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_address1,
        descramble_buf_1_M_imag_V_ce1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_ce1,
        descramble_buf_1_M_imag_V_q1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_q1,
        descramble_buf_0_M_real_V_address0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_address0,
        descramble_buf_0_M_real_V_ce0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_ce0,
        descramble_buf_0_M_real_V_q0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_q0,
        descramble_buf_0_M_real_V_address1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_address1,
        descramble_buf_0_M_real_V_ce1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_ce1,
        descramble_buf_0_M_real_V_q1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_q1,
        descramble_buf_1_M_real_V_address0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_address0,
        descramble_buf_1_M_real_V_ce0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_ce0,
        descramble_buf_1_M_real_V_q0 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_q0,
        descramble_buf_1_M_real_V_address1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_address1,
        descramble_buf_1_M_real_V_ce1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_ce1,
        descramble_buf_1_M_real_V_q1 => hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_q1);





    -- ap_reg_procdone_hls_xfft2real_Loop_realfft_be_buffer_proc_U0 assign process. --
    ap_reg_procdone_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_hls_xfft2real_Loop_realfft_be_buffer_proc_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_hls_xfft2real_Loop_realfft_be_buffer_proc_U0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done)) then 
                    ap_reg_procdone_hls_xfft2real_Loop_realfft_be_buffer_proc_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_procdone_hls_xfft2real_Loop_realfft_be_descramble_pro_U0 assign process. --
    ap_reg_procdone_hls_xfft2real_Loop_realfft_be_descramble_pro_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_hls_xfft2real_Loop_realfft_be_descramble_pro_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_hls_xfft2real_Loop_realfft_be_descramble_pro_U0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_done)) then 
                    ap_reg_procdone_hls_xfft2real_Loop_realfft_be_descramble_pro_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status assign process. --
    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done) and (ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_continue))) then 
                    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done) and (ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status))) then 
                    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status assign process. --
    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done) and (ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_continue))) then 
                    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done) and (ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status))) then 
                    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status assign process. --
    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done) and (ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_continue))) then 
                    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done) and (ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status))) then 
                    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status assign process. --
    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done) and (ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_continue))) then 
                    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done) and (ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status))) then 
                    ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_CS assign process. --
    ap_CS_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_CS <= ap_const_logic_0;
        end if;
    end process;

    -- ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V assign process. --
    ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_assign_proc : process(hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done, ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status)) then 
            ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V <= ap_const_logic_0;
        else 
            ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done;
        end if; 
    end process;


    -- ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V assign process. --
    ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_assign_proc : process(hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done, ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status)) then 
            ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V <= ap_const_logic_0;
        else 
            ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done;
        end if; 
    end process;


    -- ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V assign process. --
    ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_assign_proc : process(hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done, ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status)) then 
            ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V <= ap_const_logic_0;
        else 
            ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done;
        end if; 
    end process;


    -- ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V assign process. --
    ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_assign_proc : process(hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done, ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status)) then 
            ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V <= ap_const_logic_0;
        else 
            ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_done;
        end if; 
    end process;

    ap_done <= ap_sig_hs_done;

    -- ap_idle assign process. --
    ap_idle_assign_proc : process(hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_idle, hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_idle, descramble_buf_0_M_imag_V_t_empty_n, descramble_buf_1_M_imag_V_t_empty_n, descramble_buf_0_M_real_V_t_empty_n, descramble_buf_1_M_real_V_t_empty_n)
    begin
        if (((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_idle) and (ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_idle) and (ap_const_logic_0 = descramble_buf_0_M_imag_V_t_empty_n) and (ap_const_logic_0 = descramble_buf_1_M_imag_V_t_empty_n) and (ap_const_logic_0 = descramble_buf_0_M_real_V_t_empty_n) and (ap_const_logic_0 = descramble_buf_1_M_real_V_t_empty_n))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_sig_top_allready;

    -- ap_rst_n_inv assign process. --
    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sig_hs_continue <= ap_const_logic_1;

    -- ap_sig_hs_done assign process. --
    ap_sig_hs_done_assign_proc : process(hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_done)
    begin
        if ((ap_const_logic_1 = hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_done)) then 
            ap_sig_hs_done <= ap_const_logic_1;
        else 
            ap_sig_hs_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status assign process. --
    ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status_assign_proc : process(hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status, ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status)
    begin
        if ((ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status = ap_const_logic_0)) then 
            ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status;
        else 
            ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status assign process. --
    ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status_assign_proc : process(hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status, ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status)) then 
            ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status;
        else 
            ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status assign process. --
    ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status_assign_proc : process(hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status, ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status)) then 
            ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status;
        else 
            ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status assign process. --
    ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status_assign_proc : process(hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status, ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status)) then 
            ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status;
        else 
            ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status <= ap_const_logic_1;
        end if; 
    end process;

    ap_sig_top_allready <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_ready;
    descramble_buf_0_M_imag_V_U_ap_dummy_ce <= ap_const_logic_1;
    descramble_buf_0_M_imag_V_i_address0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_address0;
    descramble_buf_0_M_imag_V_i_address1 <= ap_const_lv8_0;
    descramble_buf_0_M_imag_V_i_ce0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_ce0;
    descramble_buf_0_M_imag_V_i_ce1 <= ap_const_logic_0;
    descramble_buf_0_M_imag_V_i_d0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_d0;
    descramble_buf_0_M_imag_V_i_we0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_we0;
    descramble_buf_0_M_imag_V_i_write <= ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V;
    descramble_buf_0_M_imag_V_t_address0 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_address0;
    descramble_buf_0_M_imag_V_t_address1 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_address1;
    descramble_buf_0_M_imag_V_t_ce0 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_ce0;
    descramble_buf_0_M_imag_V_t_ce1 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_ce1;
    descramble_buf_0_M_imag_V_t_d0 <= ap_const_lv16_0;
    descramble_buf_0_M_imag_V_t_d1 <= ap_const_lv16_0;
    descramble_buf_0_M_imag_V_t_read <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_ready;
    descramble_buf_0_M_imag_V_t_we0 <= ap_const_logic_0;
    descramble_buf_0_M_imag_V_t_we1 <= ap_const_logic_0;
    descramble_buf_0_M_real_V_U_ap_dummy_ce <= ap_const_logic_1;
    descramble_buf_0_M_real_V_i_address0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_address0;
    descramble_buf_0_M_real_V_i_address1 <= ap_const_lv8_0;
    descramble_buf_0_M_real_V_i_ce0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_ce0;
    descramble_buf_0_M_real_V_i_ce1 <= ap_const_logic_0;
    descramble_buf_0_M_real_V_i_d0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_d0;
    descramble_buf_0_M_real_V_i_we0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_we0;
    descramble_buf_0_M_real_V_i_write <= ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V;
    descramble_buf_0_M_real_V_t_address0 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_address0;
    descramble_buf_0_M_real_V_t_address1 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_address1;
    descramble_buf_0_M_real_V_t_ce0 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_ce0;
    descramble_buf_0_M_real_V_t_ce1 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_ce1;
    descramble_buf_0_M_real_V_t_d0 <= ap_const_lv16_0;
    descramble_buf_0_M_real_V_t_d1 <= ap_const_lv16_0;
    descramble_buf_0_M_real_V_t_read <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_ready;
    descramble_buf_0_M_real_V_t_we0 <= ap_const_logic_0;
    descramble_buf_0_M_real_V_t_we1 <= ap_const_logic_0;
    descramble_buf_1_M_imag_V_U_ap_dummy_ce <= ap_const_logic_1;
    descramble_buf_1_M_imag_V_i_address0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_address0;
    descramble_buf_1_M_imag_V_i_address1 <= ap_const_lv8_0;
    descramble_buf_1_M_imag_V_i_ce0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_ce0;
    descramble_buf_1_M_imag_V_i_ce1 <= ap_const_logic_0;
    descramble_buf_1_M_imag_V_i_d0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_d0;
    descramble_buf_1_M_imag_V_i_we0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_we0;
    descramble_buf_1_M_imag_V_i_write <= ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V;
    descramble_buf_1_M_imag_V_t_address0 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_address0;
    descramble_buf_1_M_imag_V_t_address1 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_address1;
    descramble_buf_1_M_imag_V_t_ce0 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_ce0;
    descramble_buf_1_M_imag_V_t_ce1 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_ce1;
    descramble_buf_1_M_imag_V_t_d0 <= ap_const_lv16_0;
    descramble_buf_1_M_imag_V_t_d1 <= ap_const_lv16_0;
    descramble_buf_1_M_imag_V_t_read <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_ready;
    descramble_buf_1_M_imag_V_t_we0 <= ap_const_logic_0;
    descramble_buf_1_M_imag_V_t_we1 <= ap_const_logic_0;
    descramble_buf_1_M_real_V_U_ap_dummy_ce <= ap_const_logic_1;
    descramble_buf_1_M_real_V_i_address0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_address0;
    descramble_buf_1_M_real_V_i_address1 <= ap_const_lv8_0;
    descramble_buf_1_M_real_V_i_ce0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_ce0;
    descramble_buf_1_M_real_V_i_ce1 <= ap_const_logic_0;
    descramble_buf_1_M_real_V_i_d0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_d0;
    descramble_buf_1_M_real_V_i_we0 <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_we0;
    descramble_buf_1_M_real_V_i_write <= ap_chn_write_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V;
    descramble_buf_1_M_real_V_t_address0 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_address0;
    descramble_buf_1_M_real_V_t_address1 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_address1;
    descramble_buf_1_M_real_V_t_ce0 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_ce0;
    descramble_buf_1_M_real_V_t_ce1 <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_ce1;
    descramble_buf_1_M_real_V_t_d0 <= ap_const_lv16_0;
    descramble_buf_1_M_real_V_t_d1 <= ap_const_lv16_0;
    descramble_buf_1_M_real_V_t_read <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_ready;
    descramble_buf_1_M_real_V_t_we0 <= ap_const_logic_0;
    descramble_buf_1_M_real_V_t_we1 <= ap_const_logic_0;
    din_TREADY <= hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TREADY;
    dout_V_TDATA <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_dout_V_TDATA;
    dout_V_TVALID <= hls_xfft2real_Loop_realfft_be_descramble_pro_U0_dout_V_TVALID;

    -- hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_continue assign process. --
    hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_continue_assign_proc : process(ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status, ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status, ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status, ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status)
    begin
        if (((ap_const_logic_1 = ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status) and (ap_const_logic_1 = ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status) and (ap_const_logic_1 = ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status) and (ap_const_logic_1 = ap_sig_ready_hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status))) then 
            hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_continue <= ap_const_logic_1;
        else 
            hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    hls_xfft2real_Loop_realfft_be_buffer_proc_U0_ap_start <= ap_start;
    hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_imag_V_pipo_status <= descramble_buf_0_M_imag_V_i_full_n;
    hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_0_M_real_V_pipo_status <= descramble_buf_0_M_real_V_i_full_n;
    hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_imag_V_pipo_status <= descramble_buf_1_M_imag_V_i_full_n;
    hls_xfft2real_Loop_realfft_be_buffer_proc_U0_descramble_buf_1_M_real_V_pipo_status <= descramble_buf_1_M_real_V_i_full_n;
    hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TDATA <= din_TDATA;
    hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TLAST <= din_TLAST;
    hls_xfft2real_Loop_realfft_be_buffer_proc_U0_din_TVALID <= din_TVALID;
    hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_continue <= ap_sig_hs_continue;
    hls_xfft2real_Loop_realfft_be_descramble_pro_U0_ap_start <= (descramble_buf_0_M_imag_V_t_empty_n and descramble_buf_1_M_imag_V_t_empty_n and descramble_buf_0_M_real_V_t_empty_n and descramble_buf_1_M_real_V_t_empty_n);
    hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_q0 <= descramble_buf_0_M_imag_V_t_q0;
    hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_imag_V_q1 <= descramble_buf_0_M_imag_V_t_q1;
    hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_q0 <= descramble_buf_0_M_real_V_t_q0;
    hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_0_M_real_V_q1 <= descramble_buf_0_M_real_V_t_q1;
    hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_q0 <= descramble_buf_1_M_imag_V_t_q0;
    hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_imag_V_q1 <= descramble_buf_1_M_imag_V_t_q1;
    hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_q0 <= descramble_buf_1_M_real_V_t_q0;
    hls_xfft2real_Loop_realfft_be_descramble_pro_U0_descramble_buf_1_M_real_V_q1 <= descramble_buf_1_M_real_V_t_q1;
    hls_xfft2real_Loop_realfft_be_descramble_pro_U0_dout_V_TREADY <= dout_V_TREADY;
end behav;
