#pragma line 1 "duc.c" ::: -10
#pragma line 1 "duc.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 6 "<command line>" 2 ::: 180
#pragma line 1 "<built-in>" 2 ::: 181
#pragma line 1 "duc.c" 2 ::: 182
#pragma line 1 "./duc.h" 1 ::: 183
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 1 ::: 186
#pragma line 62 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 239
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 240
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 268
#pragma line 122 "/usr/include/features.h" 3 4 ::: 364
#pragma line 146 "/usr/include/features.h" 3 4 ::: 381
#pragma line 177 "/usr/include/features.h" 3 4 ::: 390
#pragma line 326 "/usr/include/features.h" 3 4 ::: 417
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 454
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 500
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 518
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 524
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 528
#pragma line 150 "/usr/include/sys/cdefs.h" 3 4 ::: 538
#pragma line 168 "/usr/include/sys/cdefs.h" 3 4 ::: 542
#pragma line 191 "/usr/include/sys/cdefs.h" 3 4 ::: 552
#pragma line 235 "/usr/include/sys/cdefs.h" 3 4 ::: 589
#pragma line 288 "/usr/include/sys/cdefs.h" 3 4 ::: 630
#pragma line 324 "/usr/include/sys/cdefs.h" 3 4 ::: 640
#pragma line 334 "/usr/include/sys/cdefs.h" 3 4 ::: 643
#pragma line 373 "/usr/include/sys/cdefs.h" 3 4 ::: 660
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 661
#pragma line 374 "/usr/include/sys/cdefs.h" 2 3 4 ::: 663
#pragma line 362 "/usr/include/features.h" 2 3 4 ::: 664
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 689
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 694
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 696
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 701
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 706
#pragma line 386 "/usr/include/features.h" 2 3 4 ::: 707
#pragma line 28 "/usr/include/string.h" 2 3 4 ::: 708
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 716
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 757
#pragma line 35 "/usr/include/string.h" 2 3 4 ::: 760
#pragma line 95 "/usr/include/string.h" 3 4 ::: 798
#pragma line 127 "/usr/include/string.h" 3 4 ::: 801
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 838
#pragma line 163 "/usr/include/string.h" 2 3 4 ::: 882
#pragma line 211 "/usr/include/string.h" 3 4 ::: 905
#pragma line 235 "/usr/include/string.h" 3 4 ::: 907
#pragma line 262 "/usr/include/string.h" 3 4 ::: 912
#pragma line 282 "/usr/include/string.h" 3 4 ::: 915
#pragma line 314 "/usr/include/string.h" 3 4 ::: 925
#pragma line 342 "/usr/include/string.h" 3 4 ::: 930
#pragma line 398 "/usr/include/string.h" 3 4 ::: 951
#pragma line 444 "/usr/include/string.h" 3 4 ::: 982
#pragma line 489 "/usr/include/string.h" 3 4 ::: 1005
#pragma line 517 "/usr/include/string.h" 3 4 ::: 1011
#pragma line 535 "/usr/include/string.h" 3 4 ::: 1022
#pragma line 557 "/usr/include/string.h" 3 4 ::: 1030
#pragma line 63 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 1056
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1057
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 1080
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1081
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1106
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 1109
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1111
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1140
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1142
#pragma line 70 "/usr/include/bits/types.h" 3 4 ::: 1169
#pragma line 126 "/usr/include/bits/types.h" 3 4 ::: 1198
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1205
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1224
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1227
#pragma line 132 "/usr/include/bits/types.h" 2 3 4 ::: 1229
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 1291
#pragma line 64 "/usr/include/stdio.h" 3 4 ::: 1305
#pragma line 75 "/usr/include/stdio.h" 3 4 ::: 1308
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1309
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1342
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1358
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1383
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1386
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1391
#pragma line 82 "/usr/include/wchar.h" 3 4 ::: 1414
#pragma line 895 "/usr/include/wchar.h" 3 4 ::: 1435
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1438
#pragma line 53 "/usr/include/_G_config.h" 3 4 ::: 1450
#pragma line 82 "/usr/include/_G_config.h" 3 4 ::: 1460
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 1467
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 1469
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1473
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 1522
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 1523
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 1525
#pragma line 150 "/usr/include/libio.h" 3 4 ::: 1531
#pragma line 170 "/usr/include/libio.h" 3 4 ::: 1533
#pragma line 203 "/usr/include/libio.h" 3 4 ::: 1557
#pragma line 271 "/usr/include/libio.h" 3 4 ::: 1568
#pragma line 319 "/usr/include/libio.h" 3 4 ::: 1609
#pragma line 328 "/usr/include/libio.h" 3 4 ::: 1611
#pragma line 360 "/usr/include/libio.h" 3 4 ::: 1633
#pragma line 416 "/usr/include/libio.h" 3 4 ::: 1659
#pragma line 460 "/usr/include/libio.h" 3 4 ::: 1663
#pragma line 490 "/usr/include/libio.h" 3 4 ::: 1678
#pragma line 76 "/usr/include/stdio.h" 2 3 4 ::: 1690
#pragma line 91 "/usr/include/stdio.h" 3 4 ::: 1696
#pragma line 103 "/usr/include/stdio.h" 3 4 ::: 1698
#pragma line 120 "/usr/include/stdio.h" 3 4 ::: 1708
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 1751
#pragma line 162 "/usr/include/stdio.h" 2 3 4 ::: 1769
#pragma line 207 "/usr/include/stdio.h" 3 4 ::: 1803
#pragma line 267 "/usr/include/stdio.h" 3 4 ::: 1849
#pragma line 304 "/usr/include/stdio.h" 3 4 ::: 1863
#pragma line 317 "/usr/include/stdio.h" 3 4 ::: 1866
#pragma line 410 "/usr/include/stdio.h" 3 4 ::: 1942
#pragma line 471 "/usr/include/stdio.h" 3 4 ::: 1986
#pragma line 531 "/usr/include/stdio.h" 3 4 ::: 2027
#pragma line 650 "/usr/include/stdio.h" 3 4 ::: 2132
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 2195
#pragma line 789 "/usr/include/stdio.h" 3 4 ::: 2244
#pragma line 820 "/usr/include/stdio.h" 3 4 ::: 2255
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 2285
#pragma line 849 "/usr/include/stdio.h" 2 3 4 ::: 2314
#pragma line 905 "/usr/include/stdio.h" 3 4 ::: 2347
#pragma line 926 "/usr/include/stdio.h" 3 4 ::: 2359
#pragma line 64 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 2362
#pragma line 77 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 2363
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 2364
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 1 ::: 2422
#pragma line 97 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 2476
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 2477
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 3516
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 3517
#pragma line 99 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 4544
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 4545
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 4546
#pragma line 109 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 5585
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 5586
#pragma line 110 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 6613
#pragma line 131 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 6614
#pragma line 58 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6617
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" 1 ::: 6618
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6671
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6673
#pragma line 129 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6675
#pragma line 143 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6680
#pragma line 156 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6683
#pragma line 192 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6685
#pragma line 59 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6687
#pragma line 85 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" ::: 6688
#pragma line 78 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 6690
#pragma line 3 "./duc.h" 2 ::: 6691
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 6694
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 6728
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 6753
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 6756
#pragma line 1 "/usr/include/bits/waitflags.h" 1 3 4 ::: 6766
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 6796
#pragma line 1 "/usr/include/bits/waitstatus.h" 1 3 4 ::: 6797
#pragma line 65 "/usr/include/bits/waitstatus.h" 3 4 ::: 6854
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 6855
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 6893
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 6895
#pragma line 60 "/usr/include/endian.h" 3 4 ::: 6899
#pragma line 1 "/usr/include/bits/byteswap.h" 1 3 4 ::: 6902
#pragma line 28 "/usr/include/bits/byteswap.h" 3 4 ::: 6922
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 6923
#pragma line 29 "/usr/include/bits/byteswap.h" 2 3 4 ::: 6925
#pragma line 55 "/usr/include/bits/byteswap.h" 3 4 ::: 6928
#pragma line 67 "/usr/include/bits/byteswap.h" 3 4 ::: 6930
#pragma line 100 "/usr/include/bits/byteswap.h" 3 4 ::: 6933
#pragma line 62 "/usr/include/endian.h" 2 3 4 ::: 6935
#pragma line 66 "/usr/include/bits/waitstatus.h" 2 3 4 ::: 6936
#pragma line 44 "/usr/include/stdlib.h" 2 3 4 ::: 6970
#pragma line 58 "/usr/include/stdlib.h" 3 4 ::: 6976
#pragma line 84 "/usr/include/stdlib.h" 3 4 ::: 6992
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 6994
#pragma line 308 "/usr/include/stdlib.h" 3 4 ::: 7116
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 7130
#pragma line 34 "/usr/include/sys/types.h" 3 4 ::: 7152
#pragma line 61 "/usr/include/sys/types.h" 3 4 ::: 7169
#pragma line 99 "/usr/include/sys/types.h" 3 4 ::: 7191
#pragma line 116 "/usr/include/sys/types.h" 3 4 ::: 7199
#pragma line 133 "/usr/include/sys/types.h" 3 4 ::: 7208
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 7209
#pragma line 59 "/usr/include/time.h" 3 4 ::: 7231
#pragma line 75 "/usr/include/time.h" 3 4 ::: 7234
#pragma line 91 "/usr/include/time.h" 3 4 ::: 7237
#pragma line 103 "/usr/include/time.h" 3 4 ::: 7240
#pragma line 134 "/usr/include/sys/types.h" 2 3 4 ::: 7243
#pragma line 147 "/usr/include/sys/types.h" 3 4 ::: 7244
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 7245
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 7270
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 7273
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 7283
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 7318
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 7350
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 7374
#pragma line 24 "/usr/include/bits/select.h" 2 3 4 ::: 7376
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 7377
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 7381
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 7423
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 7434
#pragma line 118 "/usr/include/time.h" 3 4 ::: 7456
#pragma line 45 "/usr/include/sys/select.h" 2 3 4 ::: 7464
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 7466
#pragma line 73 "/usr/include/bits/time.h" 3 4 ::: 7489
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 7497
#pragma line 101 "/usr/include/sys/select.h" 3 4 ::: 7544
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 7570
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 7574
#pragma line 64 "/usr/include/sys/sysmacros.h" 3 4 ::: 7614
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 7616
#pragma line 269 "/usr/include/sys/types.h" 3 4 ::: 7638
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 7642
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 7666
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 7668
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 7669
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 7688
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 7707
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 7776
#pragma line 272 "/usr/include/sys/types.h" 2 3 4 ::: 7807
#pragma line 321 "/usr/include/stdlib.h" 2 3 4 ::: 7808
#pragma line 470 "/usr/include/stdlib.h" 3 4 ::: 7950
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 7979
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 8005
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 8030
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 8033
#pragma line 498 "/usr/include/stdlib.h" 2 3 4 ::: 8042
#pragma line 534 "/usr/include/stdlib.h" 3 4 ::: 8064
#pragma line 558 "/usr/include/stdlib.h" 3 4 ::: 8076
#pragma line 635 "/usr/include/stdlib.h" 3 4 ::: 8140
#pragma line 658 "/usr/include/stdlib.h" 3 4 ::: 8149
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 8156
#pragma line 729 "/usr/include/stdlib.h" 3 4 ::: 8162
#pragma line 753 "/usr/include/stdlib.h" 3 4 ::: 8177
#pragma line 909 "/usr/include/stdlib.h" 3 4 ::: 8325
#pragma line 945 "/usr/include/stdlib.h" 3 4 ::: 8327
#pragma line 5 "./duc.h" 2 ::: 8337
#pragma line 2 "duc.c" 2 ::: 8477
