#pragma line 1 "imf2.c" ::: 0
#pragma line 1 "imf2.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 6 "<command line>" 2 ::: 190
#pragma line 1 "<built-in>" 2 ::: 191
#pragma line 1 "imf2.c" 2 ::: 192
#pragma line 1 "./duc.h" 1 ::: 193
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 1 ::: 196
#pragma line 62 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 249
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 250
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 278
#pragma line 122 "/usr/include/features.h" 3 4 ::: 374
#pragma line 146 "/usr/include/features.h" 3 4 ::: 391
#pragma line 177 "/usr/include/features.h" 3 4 ::: 400
#pragma line 326 "/usr/include/features.h" 3 4 ::: 427
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 464
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 510
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 528
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 534
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 538
#pragma line 150 "/usr/include/sys/cdefs.h" 3 4 ::: 548
#pragma line 168 "/usr/include/sys/cdefs.h" 3 4 ::: 552
#pragma line 191 "/usr/include/sys/cdefs.h" 3 4 ::: 562
#pragma line 235 "/usr/include/sys/cdefs.h" 3 4 ::: 599
#pragma line 288 "/usr/include/sys/cdefs.h" 3 4 ::: 640
#pragma line 324 "/usr/include/sys/cdefs.h" 3 4 ::: 650
#pragma line 334 "/usr/include/sys/cdefs.h" 3 4 ::: 653
#pragma line 373 "/usr/include/sys/cdefs.h" 3 4 ::: 670
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 671
#pragma line 374 "/usr/include/sys/cdefs.h" 2 3 4 ::: 673
#pragma line 362 "/usr/include/features.h" 2 3 4 ::: 674
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 699
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 704
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 706
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 711
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 716
#pragma line 386 "/usr/include/features.h" 2 3 4 ::: 717
#pragma line 28 "/usr/include/string.h" 2 3 4 ::: 718
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 726
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 767
#pragma line 35 "/usr/include/string.h" 2 3 4 ::: 770
#pragma line 95 "/usr/include/string.h" 3 4 ::: 808
#pragma line 127 "/usr/include/string.h" 3 4 ::: 811
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 848
#pragma line 163 "/usr/include/string.h" 2 3 4 ::: 892
#pragma line 211 "/usr/include/string.h" 3 4 ::: 915
#pragma line 235 "/usr/include/string.h" 3 4 ::: 917
#pragma line 262 "/usr/include/string.h" 3 4 ::: 922
#pragma line 282 "/usr/include/string.h" 3 4 ::: 925
#pragma line 314 "/usr/include/string.h" 3 4 ::: 935
#pragma line 342 "/usr/include/string.h" 3 4 ::: 940
#pragma line 398 "/usr/include/string.h" 3 4 ::: 961
#pragma line 444 "/usr/include/string.h" 3 4 ::: 992
#pragma line 489 "/usr/include/string.h" 3 4 ::: 1015
#pragma line 517 "/usr/include/string.h" 3 4 ::: 1021
#pragma line 535 "/usr/include/string.h" 3 4 ::: 1032
#pragma line 557 "/usr/include/string.h" 3 4 ::: 1040
#pragma line 63 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 1066
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1067
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 1090
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1091
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1116
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 1119
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1121
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1150
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1152
#pragma line 70 "/usr/include/bits/types.h" 3 4 ::: 1179
#pragma line 126 "/usr/include/bits/types.h" 3 4 ::: 1208
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1215
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1234
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1237
#pragma line 132 "/usr/include/bits/types.h" 2 3 4 ::: 1239
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 1301
#pragma line 64 "/usr/include/stdio.h" 3 4 ::: 1315
#pragma line 75 "/usr/include/stdio.h" 3 4 ::: 1318
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1319
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1352
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1368
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1393
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1396
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1401
#pragma line 82 "/usr/include/wchar.h" 3 4 ::: 1424
#pragma line 895 "/usr/include/wchar.h" 3 4 ::: 1445
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1448
#pragma line 53 "/usr/include/_G_config.h" 3 4 ::: 1460
#pragma line 82 "/usr/include/_G_config.h" 3 4 ::: 1470
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 1477
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 1479
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1483
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 1532
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 1533
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 1535
#pragma line 150 "/usr/include/libio.h" 3 4 ::: 1541
#pragma line 170 "/usr/include/libio.h" 3 4 ::: 1543
#pragma line 203 "/usr/include/libio.h" 3 4 ::: 1567
#pragma line 271 "/usr/include/libio.h" 3 4 ::: 1578
#pragma line 319 "/usr/include/libio.h" 3 4 ::: 1619
#pragma line 328 "/usr/include/libio.h" 3 4 ::: 1621
#pragma line 360 "/usr/include/libio.h" 3 4 ::: 1643
#pragma line 416 "/usr/include/libio.h" 3 4 ::: 1669
#pragma line 460 "/usr/include/libio.h" 3 4 ::: 1673
#pragma line 490 "/usr/include/libio.h" 3 4 ::: 1688
#pragma line 76 "/usr/include/stdio.h" 2 3 4 ::: 1700
#pragma line 91 "/usr/include/stdio.h" 3 4 ::: 1706
#pragma line 103 "/usr/include/stdio.h" 3 4 ::: 1708
#pragma line 120 "/usr/include/stdio.h" 3 4 ::: 1718
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 1761
#pragma line 162 "/usr/include/stdio.h" 2 3 4 ::: 1779
#pragma line 207 "/usr/include/stdio.h" 3 4 ::: 1813
#pragma line 267 "/usr/include/stdio.h" 3 4 ::: 1859
#pragma line 304 "/usr/include/stdio.h" 3 4 ::: 1873
#pragma line 317 "/usr/include/stdio.h" 3 4 ::: 1876
#pragma line 410 "/usr/include/stdio.h" 3 4 ::: 1952
#pragma line 471 "/usr/include/stdio.h" 3 4 ::: 1996
#pragma line 531 "/usr/include/stdio.h" 3 4 ::: 2037
#pragma line 650 "/usr/include/stdio.h" 3 4 ::: 2142
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 2205
#pragma line 789 "/usr/include/stdio.h" 3 4 ::: 2254
#pragma line 820 "/usr/include/stdio.h" 3 4 ::: 2265
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 2295
#pragma line 849 "/usr/include/stdio.h" 2 3 4 ::: 2324
#pragma line 905 "/usr/include/stdio.h" 3 4 ::: 2357
#pragma line 926 "/usr/include/stdio.h" 3 4 ::: 2369
#pragma line 64 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 2372
#pragma line 77 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 2373
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 2374
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 1 ::: 2432
#pragma line 97 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 2486
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 2487
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 3526
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 3527
#pragma line 99 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 4554
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 4555
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 4556
#pragma line 109 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 5595
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 5596
#pragma line 110 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 6623
#pragma line 131 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 6624
#pragma line 58 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6627
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" 1 ::: 6628
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6681
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6683
#pragma line 129 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6685
#pragma line 143 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6690
#pragma line 156 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6693
#pragma line 192 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6695
#pragma line 59 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6697
#pragma line 85 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" ::: 6698
#pragma line 78 "/opt/Xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 6700
#pragma line 3 "./duc.h" 2 ::: 6701
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 6704
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 6738
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 6763
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 6766
#pragma line 1 "/usr/include/bits/waitflags.h" 1 3 4 ::: 6776
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 6806
#pragma line 1 "/usr/include/bits/waitstatus.h" 1 3 4 ::: 6807
#pragma line 65 "/usr/include/bits/waitstatus.h" 3 4 ::: 6864
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 6865
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 6903
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 6905
#pragma line 60 "/usr/include/endian.h" 3 4 ::: 6909
#pragma line 1 "/usr/include/bits/byteswap.h" 1 3 4 ::: 6912
#pragma line 28 "/usr/include/bits/byteswap.h" 3 4 ::: 6932
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 6933
#pragma line 29 "/usr/include/bits/byteswap.h" 2 3 4 ::: 6935
#pragma line 55 "/usr/include/bits/byteswap.h" 3 4 ::: 6938
#pragma line 67 "/usr/include/bits/byteswap.h" 3 4 ::: 6940
#pragma line 100 "/usr/include/bits/byteswap.h" 3 4 ::: 6943
#pragma line 62 "/usr/include/endian.h" 2 3 4 ::: 6945
#pragma line 66 "/usr/include/bits/waitstatus.h" 2 3 4 ::: 6946
#pragma line 44 "/usr/include/stdlib.h" 2 3 4 ::: 6980
#pragma line 58 "/usr/include/stdlib.h" 3 4 ::: 6986
#pragma line 84 "/usr/include/stdlib.h" 3 4 ::: 7002
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 7004
#pragma line 308 "/usr/include/stdlib.h" 3 4 ::: 7126
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 7140
#pragma line 34 "/usr/include/sys/types.h" 3 4 ::: 7162
#pragma line 61 "/usr/include/sys/types.h" 3 4 ::: 7179
#pragma line 99 "/usr/include/sys/types.h" 3 4 ::: 7201
#pragma line 116 "/usr/include/sys/types.h" 3 4 ::: 7209
#pragma line 133 "/usr/include/sys/types.h" 3 4 ::: 7218
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 7219
#pragma line 59 "/usr/include/time.h" 3 4 ::: 7241
#pragma line 75 "/usr/include/time.h" 3 4 ::: 7244
#pragma line 91 "/usr/include/time.h" 3 4 ::: 7247
#pragma line 103 "/usr/include/time.h" 3 4 ::: 7250
#pragma line 134 "/usr/include/sys/types.h" 2 3 4 ::: 7253
#pragma line 147 "/usr/include/sys/types.h" 3 4 ::: 7254
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 7255
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 7280
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 7283
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 7293
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 7328
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 7360
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 7384
#pragma line 24 "/usr/include/bits/select.h" 2 3 4 ::: 7386
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 7387
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 7391
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 7433
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 7444
#pragma line 118 "/usr/include/time.h" 3 4 ::: 7466
#pragma line 45 "/usr/include/sys/select.h" 2 3 4 ::: 7474
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 7476
#pragma line 73 "/usr/include/bits/time.h" 3 4 ::: 7499
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 7507
#pragma line 101 "/usr/include/sys/select.h" 3 4 ::: 7554
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 7580
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 7584
#pragma line 64 "/usr/include/sys/sysmacros.h" 3 4 ::: 7624
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 7626
#pragma line 269 "/usr/include/sys/types.h" 3 4 ::: 7648
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 7652
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 7676
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 7678
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 7679
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 7698
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 7717
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 7786
#pragma line 272 "/usr/include/sys/types.h" 2 3 4 ::: 7817
#pragma line 321 "/usr/include/stdlib.h" 2 3 4 ::: 7818
#pragma line 470 "/usr/include/stdlib.h" 3 4 ::: 7960
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 7989
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 8015
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 8040
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 8043
#pragma line 498 "/usr/include/stdlib.h" 2 3 4 ::: 8052
#pragma line 534 "/usr/include/stdlib.h" 3 4 ::: 8074
#pragma line 558 "/usr/include/stdlib.h" 3 4 ::: 8086
#pragma line 635 "/usr/include/stdlib.h" 3 4 ::: 8150
#pragma line 658 "/usr/include/stdlib.h" 3 4 ::: 8159
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 8166
#pragma line 729 "/usr/include/stdlib.h" 3 4 ::: 8172
#pragma line 753 "/usr/include/stdlib.h" 3 4 ::: 8187
#pragma line 909 "/usr/include/stdlib.h" 3 4 ::: 8335
#pragma line 945 "/usr/include/stdlib.h" 3 4 ::: 8337
#pragma line 5 "./duc.h" 2 ::: 8347
#pragma line 1 "imf2.c" 2 ::: 8487
#pragma line 1 "./imf2_coef.h" 1 ::: 8496
#pragma line 8 "imf2.c" 2 ::: 8509
