// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XUNUSUAL_MM2S_HLS_H
#define XUNUSUAL_MM2S_HLS_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xunusual_mm2s_hls_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Cpucontrol_BaseAddress;
} XUnusual_mm2s_hls_Config;
#endif

typedef struct {
    u32 Cpucontrol_BaseAddress;
    u32 IsReady;
} XUnusual_mm2s_hls;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XUnusual_mm2s_hls_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XUnusual_mm2s_hls_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XUnusual_mm2s_hls_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XUnusual_mm2s_hls_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XUnusual_mm2s_hls_Initialize(XUnusual_mm2s_hls *InstancePtr, u16 DeviceId);
XUnusual_mm2s_hls_Config* XUnusual_mm2s_hls_LookupConfig(u16 DeviceId);
int XUnusual_mm2s_hls_CfgInitialize(XUnusual_mm2s_hls *InstancePtr, XUnusual_mm2s_hls_Config *ConfigPtr);
#else
int XUnusual_mm2s_hls_Initialize(XUnusual_mm2s_hls *InstancePtr, const char* InstanceName);
int XUnusual_mm2s_hls_Release(XUnusual_mm2s_hls *InstancePtr);
#endif

void XUnusual_mm2s_hls_Start(XUnusual_mm2s_hls *InstancePtr);
u32 XUnusual_mm2s_hls_IsDone(XUnusual_mm2s_hls *InstancePtr);
u32 XUnusual_mm2s_hls_IsIdle(XUnusual_mm2s_hls *InstancePtr);
u32 XUnusual_mm2s_hls_IsReady(XUnusual_mm2s_hls *InstancePtr);
void XUnusual_mm2s_hls_EnableAutoRestart(XUnusual_mm2s_hls *InstancePtr);
void XUnusual_mm2s_hls_DisableAutoRestart(XUnusual_mm2s_hls *InstancePtr);

void XUnusual_mm2s_hls_Set_iteration(XUnusual_mm2s_hls *InstancePtr, u32 Data);
u32 XUnusual_mm2s_hls_Get_iteration(XUnusual_mm2s_hls *InstancePtr);

void XUnusual_mm2s_hls_InterruptGlobalEnable(XUnusual_mm2s_hls *InstancePtr);
void XUnusual_mm2s_hls_InterruptGlobalDisable(XUnusual_mm2s_hls *InstancePtr);
void XUnusual_mm2s_hls_InterruptEnable(XUnusual_mm2s_hls *InstancePtr, u32 Mask);
void XUnusual_mm2s_hls_InterruptDisable(XUnusual_mm2s_hls *InstancePtr, u32 Mask);
void XUnusual_mm2s_hls_InterruptClear(XUnusual_mm2s_hls *InstancePtr, u32 Mask);
u32 XUnusual_mm2s_hls_InterruptGetEnabled(XUnusual_mm2s_hls *InstancePtr);
u32 XUnusual_mm2s_hls_InterruptGetStatus(XUnusual_mm2s_hls *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
