set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {mm2s_sys_i/mm2s_0_stream_V_TDATA[23]}]
set_property MARK_DEBUG true [get_nets mm2s_sys_i/stream_V_TVALID]
set_property MARK_DEBUG true [get_nets mm2s_sys_i/stream_V_TREADY]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list mm2s_sys_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {mm2s_sys_i/mm2s_0_stream_V_TDATA[0]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[1]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[2]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[3]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[4]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[5]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[6]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[7]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[8]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[9]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[10]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[11]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[12]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[13]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[14]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[15]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[16]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[17]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[18]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[19]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[20]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[21]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[22]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[23]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[24]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[25]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[26]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[27]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[28]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[29]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[30]} {mm2s_sys_i/mm2s_0_stream_V_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list mm2s_sys_i/stream_V_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list mm2s_sys_i/stream_V_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
