// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;

// apint = int16
#define int16 short
// apint = int32
#define int32 int

// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "outdata"
#define AUTOTB_TVOUT_outdata  "../tv/cdatafile/c.hamming_window.autotvout_outdata.dat"
#define AUTOTB_TVIN_outdata  "../tv/cdatafile/c.hamming_window.autotvin_outdata.dat"
// wrapc file define: "indata"
#define AUTOTB_TVIN_indata  "../tv/cdatafile/c.hamming_window.autotvin_indata.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "outdata"
#define AUTOTB_TVOUT_PC_outdata  "../tv/rtldatafile/rtl.hamming_window.autotvout_outdata.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			outdata_depth = 0;
			indata_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{outdata " << outdata_depth << "}\n";
			total_list << "{indata " << indata_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int outdata_depth;
		int indata_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern "C" void hamming_window (
int32 outdata[256],
int16 indata[256]);

#define hamming_window AESL_ORIG_DUT_hamming_window
extern "C" void hamming_window (
int32 outdata[256],
int16 indata[256]);
#undef hamming_window

void hamming_window (
int32 outdata[256],
int16 indata[256])
{
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "outdata"
		aesl_fh.read(AUTOTB_TVOUT_PC_outdata, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_outdata, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_outdata, AESL_token); // data

			sc_bv<32> *outdata_pc_buffer = new sc_bv<32>[256];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'outdata', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'outdata', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					outdata_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_outdata, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_outdata))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: outdata
				{
					// bitslice(31, 0)
					// {
						// celement: outdata(31, 0)
						// {
							sc_lv<32>* outdata_lv0_0_255_1 = new sc_lv<32>[256];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: outdata(31, 0)
						{
							// carray: (0) => (255) @ (1)
							for (int i_0 = 0; i_0 <= 255; i_0 += 1)
							{
								if (&(outdata[0]) != NULL) // check the null address if the c port is array or others
								{
									outdata_lv0_0_255_1[hls_map_index++].range(31, 0) = sc_bv<32>(outdata_pc_buffer[hls_map_index].range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: outdata(31, 0)
						{
							// carray: (0) => (255) @ (1)
							for (int i_0 = 0; i_0 <= 255; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : outdata[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : outdata[0]
								// output_left_conversion : outdata[i_0]
								// output_type_conversion : (outdata_lv0_0_255_1[hls_map_index++]).to_uint64()
								if (&(outdata[0]) != NULL) // check the null address if the c port is array or others
								{
									outdata[i_0] = (outdata_lv0_0_255_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] outdata_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "outdata"
		char* tvin_outdata = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_outdata);
		char* tvout_outdata = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_outdata);

		// "indata"
		char* tvin_indata = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_indata);

		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_outdata, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_outdata, tvin_outdata);

		sc_bv<32>* outdata_tvin_wrapc_buffer = new sc_bv<32>[256];

		// RTL Name: outdata
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: outdata(31, 0)
				{
					// carray: (0) => (255) @ (1)
					for (int i_0 = 0; i_0 <= 255; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : outdata[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : outdata[0]
						// regulate_c_name       : outdata
						// input_type_conversion : outdata[i_0]
						if (&(outdata[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> outdata_tmp_mem;
							outdata_tmp_mem = outdata[i_0];
							outdata_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = outdata_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 256; i++)
		{
			sprintf(tvin_outdata, "%s\n", (outdata_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_outdata, tvin_outdata);
		}

		tcl_file.set_num(256, &tcl_file.outdata_depth);
		sprintf(tvin_outdata, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_outdata, tvin_outdata);

		// release memory allocation
		delete [] outdata_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_indata, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_indata, tvin_indata);

		sc_bv<16>* indata_tvin_wrapc_buffer = new sc_bv<16>[256];

		// RTL Name: indata
		{
			// bitslice(15, 0)
			{
				int hls_map_index = 0;
				// celement: indata(15, 0)
				{
					// carray: (0) => (255) @ (1)
					for (int i_0 = 0; i_0 <= 255; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : indata[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : indata[0]
						// regulate_c_name       : indata
						// input_type_conversion : indata[i_0]
						if (&(indata[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> indata_tmp_mem;
							indata_tmp_mem = indata[i_0];
							indata_tvin_wrapc_buffer[hls_map_index++].range(15, 0) = indata_tmp_mem.range(15, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 256; i++)
		{
			sprintf(tvin_indata, "%s\n", (indata_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_indata, tvin_indata);
		}

		tcl_file.set_num(256, &tcl_file.indata_depth);
		sprintf(tvin_indata, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_indata, tvin_indata);

		// release memory allocation
		delete [] indata_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		AESL_ORIG_DUT_hamming_window(outdata, indata);


		// [[transaction]]
		sprintf(tvout_outdata, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_outdata, tvout_outdata);

		sc_bv<32>* outdata_tvout_wrapc_buffer = new sc_bv<32>[256];

		// RTL Name: outdata
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: outdata(31, 0)
				{
					// carray: (0) => (255) @ (1)
					for (int i_0 = 0; i_0 <= 255; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : outdata[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : outdata[0]
						// regulate_c_name       : outdata
						// input_type_conversion : outdata[i_0]
						if (&(outdata[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> outdata_tmp_mem;
							outdata_tmp_mem = outdata[i_0];
							outdata_tvout_wrapc_buffer[hls_map_index++].range(31, 0) = outdata_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 256; i++)
		{
			sprintf(tvout_outdata, "%s\n", (outdata_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_outdata, tvout_outdata);
		}

		tcl_file.set_num(256, &tcl_file.outdata_depth);
		sprintf(tvout_outdata, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_outdata, tvout_outdata);

		// release memory allocation
		delete [] outdata_tvout_wrapc_buffer;

		// release memory allocation: "outdata"
		delete [] tvout_outdata;
		delete [] tvin_outdata;
		// release memory allocation: "indata"
		delete [] tvin_indata;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}


// apint = int16
#undef int16

// apint = int32
#undef int32
