#!/bin/bash -f
# Vivado (TM) v2015.3 (64-bit)
#
# Filename    : RealFFT.sh
# Simulator   : Cadence Incisive Enterprise Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do' file, copy glbl.v into the run directory for verilog sources in the design (if any),
#               execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Jul 08 02:24:30 CEST 2016
# IP Build 1367837 on Mon Sep 28 08:56:14 MDT 2015 
#
# usage: RealFFT.sh [-help]
# usage: RealFFT.sh [-lib_map_path]
# usage: RealFFT.sh [-noclean_files]
# usage: RealFFT.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'RealFFT.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Script info
echo -e "RealFFT.sh - Script generated by export_simulation (Vivado v2015.3 (64-bit)-id)\n"

# Script usage
usage()
{
  msg="Usage: RealFFT.sh [-help]\n\
Usage: RealFFT.sh [-lib_map_path]\n\
Usage: RealFFT.sh [-reset_run]\n\
Usage: RealFFT.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

if [[ ($# == 1 ) && ($1 != "-lib_map_path" && $1 != "-noclean_files" && $1 != "-reset_run" && $1 != "-help" && $1 != "-h") ]]; then
  echo -e "ERROR: Unknown option specified '$1' (type \"./RealFFT.sh -help\" for more information)\n"
  exit 1
fi

if [[ ($1 == "-help" || $1 == "-h") ]]; then
  usage
fi

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./RealFFT.sh -help\" for more information)\n"
        exit 1
      fi
      # precompiled simulation library directory path
     create_lib_mappings $2
     touch hdl.var
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
     create_lib_mappings $2
     touch hdl.var
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Copy glbl.v file into run directory
copy_glbl_file()
{
  glbl_file="glbl.v"
  src_file="/opt/Xilinx/Vivado/2015.3/data/verilog/src/glbl.v"
  if [[ ! -e $glbl_file ]]; then
    cp $src_file .
  fi
}

# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(ncsim.key irun.key ncvlog.log ncvhdl.log compile.log elaborate.log simulate.log run.log waves.shm INCA_libs)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Main steps
run()
{
  setup $1 $2
  compile
  elaborate
  simulate
}

# Create design library directory paths and define design library mappings in cds.lib
create_lib_mappings()
{
  libs=(xil_defaultlib xbip_utils_v3_0_4 axi_utils_v2_0_0 c_reg_fd_v12_0_0 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_0 xbip_dsp48_addsub_v3_0_0 xbip_addsub_v3_0_0 c_addsub_v12_0_7 c_mux_bit_v12_0_0 c_shift_ram_v12_0_7 xbip_bram18k_v3_0_0 mult_gen_v12_0_9 cmpy_v6_0_9 floating_point_v7_0_10 xfft_v9_0_8)
  file="cds.lib"
  dir="ies"

  if [[ -e $file ]]; then
    rm -f $file
  fi

  if [[ -e $dir ]]; then
    rm -rf $dir
  fi

  touch $file
  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi
  incl_ref="INCLUDE $lib_map_path/cds.lib"
  echo $incl_ref >> $file

  for (( i=0; i<${#libs[*]}; i++ )); do
    lib="${libs[i]}"
    lib_dir="$dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
      mapping="DEFINE $lib $dir/$lib"
      echo $mapping >> $file
    fi
  done
}


# RUN_STEP: <compile>
compile()
{
  # Directory path for design sources and include directories (if any) wrt this path
  ref_dir="."
  # Command line options
  opts_ver="-64bit -messages -logfile ncvlog.log -append_log"
  opts_vhd="-64bit -V93 -RELAX -logfile ncvhdl.log -append_log"

  # Compile design files
  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_xfft2real_v1_0/hdl/vhdl/hls_xfft2real_mac_mulsub_16s_16s_31s_31_3.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_xfft2real_v1_0/hdl/vhdl/hls_xfft2real_Loop_realfft_be_buffer_proc.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_xfft2real_v1_0/hdl/vhdl/hls_xfft2real.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_xfft2real_v1_0/hdl/vhdl/hls_xfft2real_descramble_buf_0_M_real_V.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_xfft2real_v1_0/hdl/vhdl/hls_xfft2real_mac_muladd_16s_16s_31s_31_3.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_xfft2real_v1_0/hdl/vhdl/hls_xfft2real_Loop_realfft_be_descramble_pro_twid_rom_0.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_xfft2real_v1_0/hdl/vhdl/hls_xfft2real_Loop_realfft_be_descramble_pro_twid_rom_1.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_xfft2real_v1_0/hdl/vhdl/hls_xfft2real_Loop_realfft_be_descramble_pro.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_xfft2real_v1_0/hdl/vhdl/hls_xfft2real_descramble_buf_0_M_real_V_memcore.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_xfft2real_v1_0/hdl/vhdl/hls_xfft2real_mul_mul_16s_16s_31_3.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ip/RealFFT_hls_xfft2real_0_0/sim/RealFFT_hls_xfft2real_0_0.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/hls_real2xfft_Loop_real2xfft_output_proc.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/FIFO_hls_real2xfft_windowed_0_channel.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/hls_real2xfft_window_fn_coeff_tab1_0.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/hls_real2xfft_window_fn_coeff_tab1_1.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/FIFO_hls_real2xfft_delayed_i_0_channel.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/FIFO_hls_real2xfft_nodelay_i_1_channel.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/hls_real2xfft_window_fn.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/FIFO_hls_real2xfft_data2window_0_channel.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/hls_real2xfft_Loop_sliding_win_delay_proc_delay_line_Array_V.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/FIFO_hls_real2xfft_windowed_1_channel.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/hls_real2xfft_Loop_sliding_win_output_proc.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/FIFO_hls_real2xfft_data2window_1_channel.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/hls_real2xfft_Loop_sliding_win_delay_proc.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/hls_real2xfft.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/FIFO_hls_real2xfft_nodelay_i_0_channel.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/FIFO_hls_real2xfft_delayed_i_1_channel.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/hls_real2xfft_v1_0/hdl/vhdl/hls_real2xfft_mul_mul_16s_15ns_31_3.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ip/RealFFT_hls_real2xfft_0_0/sim/RealFFT_hls_real2xfft_0_0.vhd" \

  ncvhdl -work xbip_utils_v3_0_4 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xbip_utils_v3_0/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

  ncvhdl -work axi_utils_v2_0_0 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/axi_utils_v2_0/hdl/axi_utils_v2_0_vh_rfs.vhd" \

  ncvhdl -work c_reg_fd_v12_0_0 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/c_reg_fd_v12_0/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/c_reg_fd_v12_0/hdl/c_reg_fd_v12_0.vhd" \

  ncvhdl -work xbip_dsp48_wrapper_v3_0_4 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xbip_dsp48_wrapper_v3_0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

  ncvhdl -work xbip_pipe_v3_0_0 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xbip_pipe_v3_0/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xbip_pipe_v3_0/hdl/xbip_pipe_v3_0.vhd" \

  ncvhdl -work xbip_dsp48_addsub_v3_0_0 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xbip_dsp48_addsub_v3_0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xbip_dsp48_addsub_v3_0/hdl/xbip_dsp48_addsub_v3_0.vhd" \

  ncvhdl -work xbip_addsub_v3_0_0 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xbip_addsub_v3_0/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xbip_addsub_v3_0/hdl/xbip_addsub_v3_0.vhd" \

  ncvhdl -work c_addsub_v12_0_7 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/c_addsub_v12_0/hdl/c_addsub_v12_0_vh_rfs.vhd" \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/c_addsub_v12_0/hdl/c_addsub_v12_0.vhd" \

  ncvhdl -work c_mux_bit_v12_0_0 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/c_mux_bit_v12_0/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/c_mux_bit_v12_0/hdl/c_mux_bit_v12_0.vhd" \

  ncvhdl -work c_shift_ram_v12_0_7 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/c_shift_ram_v12_0/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/c_shift_ram_v12_0/hdl/c_shift_ram_v12_0.vhd" \

  ncvhdl -work xbip_bram18k_v3_0_0 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xbip_bram18k_v3_0/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xbip_bram18k_v3_0/hdl/xbip_bram18k_v3_0.vhd" \

  ncvhdl -work mult_gen_v12_0_9 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/mult_gen_v12_0/hdl/mult_gen_v12_0_vh_rfs.vhd" \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/mult_gen_v12_0/hdl/mult_gen_v12_0.vhd" \

  ncvhdl -work cmpy_v6_0_9 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/cmpy_v6_0/hdl/cmpy_v6_0_vh_rfs.vhd" \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/cmpy_v6_0/hdl/cmpy_v6_0.vhd" \

  ncvhdl -work floating_point_v7_0_10 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/floating_point_v7_0/hdl/floating_point_v7_0_vh_rfs.vhd" \

  ncvhdl -work xfft_v9_0_8 $opts_vhd \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xfft_v9_0/hdl/xfft_v9_0_vh_rfs.vhd" \
    "$ref_dir/./../../../../vivado.srcs/sources_1/bd/RealFFT/ipshared/xilinx.com/xfft_v9_0/hdl/xfft_v9_0.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/./../../../bd/RealFFT/ip/RealFFT_xfft_0_0/sim/RealFFT_xfft_0_0.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ipshared/xilinx.com/xlconstant_v1_1/xlconstant.vhd" \
    "$ref_dir/./../../../bd/RealFFT/ip/RealFFT_xlconstant_0_0/sim/RealFFT_xlconstant_0_0.vhd" \
    "$ref_dir/./../../../bd/RealFFT/hdl/RealFFT.vhd" \


}

# RUN_STEP: <elaborate>
elaborate()
{
  opts="-64bit -relax -access +rwc -messages -logfile elaborate.log -timescale 1ps/1ps"
  libs="-libname secureip -libname xil_defaultlib -libname xbip_utils_v3_0_4 -libname axi_utils_v2_0_0 -libname c_reg_fd_v12_0_0 -libname xbip_dsp48_wrapper_v3_0_4 -libname xbip_pipe_v3_0_0 -libname xbip_dsp48_addsub_v3_0_0 -libname xbip_addsub_v3_0_0 -libname c_addsub_v12_0_7 -libname c_mux_bit_v12_0_0 -libname c_shift_ram_v12_0_7 -libname xbip_bram18k_v3_0_0 -libname mult_gen_v12_0_9 -libname cmpy_v6_0_9 -libname floating_point_v7_0_10 -libname xfft_v9_0_8"
  ncelab $opts xil_defaultlib.RealFFT $libs
}

# RUN_STEP: <simulate>
simulate()
{
  opts="-64bit -logfile simulate.log"
  ncsim $opts xil_defaultlib.RealFFT -input simulate.do
}
# Script usage
usage()
{
  msg="Usage: RealFFT.sh [-help]\n\
Usage: RealFFT.sh [-lib_map_path]\n\
Usage: RealFFT.sh [-reset_run]\n\
Usage: RealFFT.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}


# Launch script
run $1 $2
