// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dct,hls_ip_2015_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160tfbg484-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.930000,HLS_SYN_LAT=283,HLS_SYN_TPT=67,HLS_SYN_MEM=14,HLS_SYN_DSP=96,HLS_SYN_FF=3016,HLS_SYN_LUT=2052}" *)

module dct (
        ap_clk,
        ap_rst,
        input_r_address0,
        input_r_ce0,
        input_r_d0,
        input_r_q0,
        input_r_we0,
        input_r_address1,
        input_r_ce1,
        input_r_d1,
        input_r_q1,
        input_r_we1,
        output_r_address0,
        output_r_ce0,
        output_r_d0,
        output_r_q0,
        output_r_we0,
        output_r_address1,
        output_r_ce1,
        output_r_d1,
        output_r_q1,
        output_r_we1,
        ap_done,
        ap_start,
        ap_idle,
        ap_ready
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_true = 1'b1;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv4_1 = 4'b1;

input   ap_clk;
input   ap_rst;
output  [5:0] input_r_address0;
output   input_r_ce0;
output  [15:0] input_r_d0;
input  [15:0] input_r_q0;
output   input_r_we0;
output  [5:0] input_r_address1;
output   input_r_ce1;
output  [15:0] input_r_d1;
input  [15:0] input_r_q1;
output   input_r_we1;
output  [5:0] output_r_address0;
output   output_r_ce0;
output  [15:0] output_r_d0;
input  [15:0] output_r_q0;
output   output_r_we0;
output  [5:0] output_r_address1;
output   output_r_ce1;
output  [15:0] output_r_d1;
input  [15:0] output_r_q1;
output   output_r_we1;
output   ap_done;
input   ap_start;
output   ap_idle;
output   ap_ready;

reg ap_idle;
wire   [5:0] row_outbuf_i_i_address0;
wire    row_outbuf_i_i_ce0;
wire    row_outbuf_i_i_we0;
wire   [15:0] row_outbuf_i_i_d0;
wire   [15:0] row_outbuf_i_i_q0;
wire   [5:0] row_outbuf_i_i_address1;
wire    row_outbuf_i_i_ce1;
wire    row_outbuf_i_i_we1;
wire   [15:0] row_outbuf_i_i_d1;
wire   [5:0] row_outbuf_i_t_address0;
wire    row_outbuf_i_t_ce0;
wire    row_outbuf_i_t_we0;
wire   [15:0] row_outbuf_i_t_d0;
wire   [15:0] row_outbuf_i_t_q0;
wire   [5:0] row_outbuf_i_t_address1;
wire    row_outbuf_i_t_ce1;
wire    row_outbuf_i_t_we1;
wire   [15:0] row_outbuf_i_t_d1;
wire    row_outbuf_i_U_ap_dummy_ce;
wire   [5:0] col_outbuf_i_i_address0;
wire    col_outbuf_i_i_ce0;
wire    col_outbuf_i_i_we0;
wire   [15:0] col_outbuf_i_i_d0;
wire   [15:0] col_outbuf_i_i_q0;
wire   [5:0] col_outbuf_i_i_address1;
wire    col_outbuf_i_i_ce1;
wire    col_outbuf_i_i_we1;
wire   [15:0] col_outbuf_i_i_d1;
wire   [5:0] col_outbuf_i_t_address0;
wire    col_outbuf_i_t_ce0;
wire    col_outbuf_i_t_we0;
wire   [15:0] col_outbuf_i_t_d0;
wire   [15:0] col_outbuf_i_t_q0;
wire   [5:0] col_outbuf_i_t_address1;
wire    col_outbuf_i_t_ce1;
wire    col_outbuf_i_t_we1;
wire   [15:0] col_outbuf_i_t_d1;
wire    col_outbuf_i_U_ap_dummy_ce;
wire   [3:0] col_inbuf_0_i_address0;
wire    col_inbuf_0_i_ce0;
wire    col_inbuf_0_i_we0;
wire   [15:0] col_inbuf_0_i_d0;
wire   [15:0] col_inbuf_0_i_q0;
wire   [3:0] col_inbuf_0_i_address1;
wire    col_inbuf_0_i_ce1;
wire   [15:0] col_inbuf_0_i_q1;
wire   [3:0] col_inbuf_0_t_address0;
wire    col_inbuf_0_t_ce0;
wire    col_inbuf_0_t_we0;
wire   [15:0] col_inbuf_0_t_d0;
wire   [15:0] col_inbuf_0_t_q0;
wire   [3:0] col_inbuf_0_t_address1;
wire    col_inbuf_0_t_ce1;
wire   [15:0] col_inbuf_0_t_q1;
wire    col_inbuf_0_U_ap_dummy_ce;
wire   [3:0] col_inbuf_1_i_address0;
wire    col_inbuf_1_i_ce0;
wire    col_inbuf_1_i_we0;
wire   [15:0] col_inbuf_1_i_d0;
wire   [15:0] col_inbuf_1_i_q0;
wire   [3:0] col_inbuf_1_i_address1;
wire    col_inbuf_1_i_ce1;
wire   [15:0] col_inbuf_1_i_q1;
wire   [3:0] col_inbuf_1_t_address0;
wire    col_inbuf_1_t_ce0;
wire    col_inbuf_1_t_we0;
wire   [15:0] col_inbuf_1_t_d0;
wire   [15:0] col_inbuf_1_t_q0;
wire   [3:0] col_inbuf_1_t_address1;
wire    col_inbuf_1_t_ce1;
wire   [15:0] col_inbuf_1_t_q1;
wire    col_inbuf_1_U_ap_dummy_ce;
wire   [3:0] col_inbuf_2_i_address0;
wire    col_inbuf_2_i_ce0;
wire    col_inbuf_2_i_we0;
wire   [15:0] col_inbuf_2_i_d0;
wire   [15:0] col_inbuf_2_i_q0;
wire   [3:0] col_inbuf_2_i_address1;
wire    col_inbuf_2_i_ce1;
wire   [15:0] col_inbuf_2_i_q1;
wire   [3:0] col_inbuf_2_t_address0;
wire    col_inbuf_2_t_ce0;
wire    col_inbuf_2_t_we0;
wire   [15:0] col_inbuf_2_t_d0;
wire   [15:0] col_inbuf_2_t_q0;
wire   [3:0] col_inbuf_2_t_address1;
wire    col_inbuf_2_t_ce1;
wire   [15:0] col_inbuf_2_t_q1;
wire    col_inbuf_2_U_ap_dummy_ce;
wire   [3:0] col_inbuf_3_i_address0;
wire    col_inbuf_3_i_ce0;
wire    col_inbuf_3_i_we0;
wire   [15:0] col_inbuf_3_i_d0;
wire   [15:0] col_inbuf_3_i_q0;
wire   [3:0] col_inbuf_3_i_address1;
wire    col_inbuf_3_i_ce1;
wire   [15:0] col_inbuf_3_i_q1;
wire   [3:0] col_inbuf_3_t_address0;
wire    col_inbuf_3_t_ce0;
wire    col_inbuf_3_t_we0;
wire   [15:0] col_inbuf_3_t_d0;
wire   [15:0] col_inbuf_3_t_q0;
wire   [3:0] col_inbuf_3_t_address1;
wire    col_inbuf_3_t_ce1;
wire   [15:0] col_inbuf_3_t_q1;
wire    col_inbuf_3_U_ap_dummy_ce;
wire   [3:0] buf_2d_in_0_i_address0;
wire    buf_2d_in_0_i_ce0;
wire    buf_2d_in_0_i_we0;
wire   [15:0] buf_2d_in_0_i_d0;
wire   [15:0] buf_2d_in_0_i_q0;
wire   [3:0] buf_2d_in_0_i_address1;
wire    buf_2d_in_0_i_ce1;
wire    buf_2d_in_0_i_we1;
wire   [15:0] buf_2d_in_0_i_d1;
wire   [15:0] buf_2d_in_0_i_q1;
wire   [3:0] buf_2d_in_0_t_address0;
wire    buf_2d_in_0_t_ce0;
wire    buf_2d_in_0_t_we0;
wire   [15:0] buf_2d_in_0_t_d0;
wire   [15:0] buf_2d_in_0_t_q0;
wire   [3:0] buf_2d_in_0_t_address1;
wire    buf_2d_in_0_t_ce1;
wire    buf_2d_in_0_t_we1;
wire   [15:0] buf_2d_in_0_t_d1;
wire   [15:0] buf_2d_in_0_t_q1;
wire    buf_2d_in_0_U_ap_dummy_ce;
wire   [3:0] buf_2d_in_1_i_address0;
wire    buf_2d_in_1_i_ce0;
wire    buf_2d_in_1_i_we0;
wire   [15:0] buf_2d_in_1_i_d0;
wire   [15:0] buf_2d_in_1_i_q0;
wire   [3:0] buf_2d_in_1_i_address1;
wire    buf_2d_in_1_i_ce1;
wire    buf_2d_in_1_i_we1;
wire   [15:0] buf_2d_in_1_i_d1;
wire   [15:0] buf_2d_in_1_i_q1;
wire   [3:0] buf_2d_in_1_t_address0;
wire    buf_2d_in_1_t_ce0;
wire    buf_2d_in_1_t_we0;
wire   [15:0] buf_2d_in_1_t_d0;
wire   [15:0] buf_2d_in_1_t_q0;
wire   [3:0] buf_2d_in_1_t_address1;
wire    buf_2d_in_1_t_ce1;
wire    buf_2d_in_1_t_we1;
wire   [15:0] buf_2d_in_1_t_d1;
wire   [15:0] buf_2d_in_1_t_q1;
wire    buf_2d_in_1_U_ap_dummy_ce;
wire   [3:0] buf_2d_in_2_i_address0;
wire    buf_2d_in_2_i_ce0;
wire    buf_2d_in_2_i_we0;
wire   [15:0] buf_2d_in_2_i_d0;
wire   [15:0] buf_2d_in_2_i_q0;
wire   [3:0] buf_2d_in_2_i_address1;
wire    buf_2d_in_2_i_ce1;
wire    buf_2d_in_2_i_we1;
wire   [15:0] buf_2d_in_2_i_d1;
wire   [15:0] buf_2d_in_2_i_q1;
wire   [3:0] buf_2d_in_2_t_address0;
wire    buf_2d_in_2_t_ce0;
wire    buf_2d_in_2_t_we0;
wire   [15:0] buf_2d_in_2_t_d0;
wire   [15:0] buf_2d_in_2_t_q0;
wire   [3:0] buf_2d_in_2_t_address1;
wire    buf_2d_in_2_t_ce1;
wire    buf_2d_in_2_t_we1;
wire   [15:0] buf_2d_in_2_t_d1;
wire   [15:0] buf_2d_in_2_t_q1;
wire    buf_2d_in_2_U_ap_dummy_ce;
wire   [3:0] buf_2d_in_3_i_address0;
wire    buf_2d_in_3_i_ce0;
wire    buf_2d_in_3_i_we0;
wire   [15:0] buf_2d_in_3_i_d0;
wire   [15:0] buf_2d_in_3_i_q0;
wire   [3:0] buf_2d_in_3_i_address1;
wire    buf_2d_in_3_i_ce1;
wire    buf_2d_in_3_i_we1;
wire   [15:0] buf_2d_in_3_i_d1;
wire   [15:0] buf_2d_in_3_i_q1;
wire   [3:0] buf_2d_in_3_t_address0;
wire    buf_2d_in_3_t_ce0;
wire    buf_2d_in_3_t_we0;
wire   [15:0] buf_2d_in_3_t_d0;
wire   [15:0] buf_2d_in_3_t_q0;
wire   [3:0] buf_2d_in_3_t_address1;
wire    buf_2d_in_3_t_ce1;
wire    buf_2d_in_3_t_we1;
wire   [15:0] buf_2d_in_3_t_d1;
wire   [15:0] buf_2d_in_3_t_q1;
wire    buf_2d_in_3_U_ap_dummy_ce;
wire   [5:0] buf_2d_out_i_address0;
wire    buf_2d_out_i_ce0;
wire    buf_2d_out_i_we0;
wire   [15:0] buf_2d_out_i_d0;
wire   [15:0] buf_2d_out_i_q0;
wire   [5:0] buf_2d_out_i_address1;
wire    buf_2d_out_i_ce1;
wire   [15:0] buf_2d_out_i_q1;
wire   [5:0] buf_2d_out_t_address0;
wire    buf_2d_out_t_ce0;
wire    buf_2d_out_t_we0;
wire   [15:0] buf_2d_out_t_d0;
wire   [15:0] buf_2d_out_t_q0;
wire   [5:0] buf_2d_out_t_address1;
wire    buf_2d_out_t_ce1;
wire   [15:0] buf_2d_out_t_q1;
wire    buf_2d_out_U_ap_dummy_ce;
wire    dct_read_data_U0_ap_start;
wire    dct_read_data_U0_ap_done;
reg    dct_read_data_U0_ap_continue;
wire    dct_read_data_U0_ap_idle;
wire    dct_read_data_U0_ap_ready;
wire   [5:0] dct_read_data_U0_input_r_address0;
wire    dct_read_data_U0_input_r_ce0;
wire   [15:0] dct_read_data_U0_input_r_q0;
wire   [5:0] dct_read_data_U0_input_r_address1;
wire    dct_read_data_U0_input_r_ce1;
wire   [15:0] dct_read_data_U0_input_r_q1;
wire   [3:0] dct_read_data_U0_buf_0_address0;
wire    dct_read_data_U0_buf_0_ce0;
wire    dct_read_data_U0_buf_0_we0;
wire   [15:0] dct_read_data_U0_buf_0_d0;
wire   [3:0] dct_read_data_U0_buf_0_address1;
wire    dct_read_data_U0_buf_0_ce1;
wire    dct_read_data_U0_buf_0_we1;
wire   [15:0] dct_read_data_U0_buf_0_d1;
wire   [3:0] dct_read_data_U0_buf_1_address0;
wire    dct_read_data_U0_buf_1_ce0;
wire    dct_read_data_U0_buf_1_we0;
wire   [15:0] dct_read_data_U0_buf_1_d0;
wire   [3:0] dct_read_data_U0_buf_1_address1;
wire    dct_read_data_U0_buf_1_ce1;
wire    dct_read_data_U0_buf_1_we1;
wire   [15:0] dct_read_data_U0_buf_1_d1;
wire   [3:0] dct_read_data_U0_buf_2_address0;
wire    dct_read_data_U0_buf_2_ce0;
wire    dct_read_data_U0_buf_2_we0;
wire   [15:0] dct_read_data_U0_buf_2_d0;
wire   [3:0] dct_read_data_U0_buf_2_address1;
wire    dct_read_data_U0_buf_2_ce1;
wire    dct_read_data_U0_buf_2_we1;
wire   [15:0] dct_read_data_U0_buf_2_d1;
wire   [3:0] dct_read_data_U0_buf_3_address0;
wire    dct_read_data_U0_buf_3_ce0;
wire    dct_read_data_U0_buf_3_we0;
wire   [15:0] dct_read_data_U0_buf_3_d0;
wire   [3:0] dct_read_data_U0_buf_3_address1;
wire    dct_read_data_U0_buf_3_ce1;
wire    dct_read_data_U0_buf_3_we1;
wire   [15:0] dct_read_data_U0_buf_3_d1;
reg    ap_chn_write_dct_read_data_U0_buf_2d_in_0;
wire    dct_read_data_U0_buf_0_pipo_status;
reg    ap_reg_ready_dct_read_data_U0_buf_0_pipo_status = 1'b0;
reg    ap_sig_ready_dct_read_data_U0_buf_0_pipo_status;
reg    ap_chn_write_dct_read_data_U0_buf_2d_in_1;
wire    dct_read_data_U0_buf_1_pipo_status;
reg    ap_reg_ready_dct_read_data_U0_buf_1_pipo_status = 1'b0;
reg    ap_sig_ready_dct_read_data_U0_buf_1_pipo_status;
reg    ap_chn_write_dct_read_data_U0_buf_2d_in_2;
wire    dct_read_data_U0_buf_2_pipo_status;
reg    ap_reg_ready_dct_read_data_U0_buf_2_pipo_status = 1'b0;
reg    ap_sig_ready_dct_read_data_U0_buf_2_pipo_status;
reg    ap_chn_write_dct_read_data_U0_buf_2d_in_3;
wire    dct_read_data_U0_buf_3_pipo_status;
reg    ap_reg_ready_dct_read_data_U0_buf_3_pipo_status = 1'b0;
reg    ap_sig_ready_dct_read_data_U0_buf_3_pipo_status;
wire    dct_Loop_Row_DCT_Loop_proc_U0_ap_start;
wire    dct_Loop_Row_DCT_Loop_proc_U0_ap_done;
wire    dct_Loop_Row_DCT_Loop_proc_U0_ap_continue;
wire    dct_Loop_Row_DCT_Loop_proc_U0_ap_idle;
wire    dct_Loop_Row_DCT_Loop_proc_U0_ap_ready;
wire   [3:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_address0;
wire    dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_ce0;
wire   [15:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_q0;
wire   [3:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_address1;
wire    dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_ce1;
wire   [15:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_q1;
wire   [3:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_address0;
wire    dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_ce0;
wire   [15:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_q0;
wire   [3:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_address1;
wire    dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_ce1;
wire   [15:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_q1;
wire   [3:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_address0;
wire    dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_ce0;
wire   [15:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_q0;
wire   [3:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_address1;
wire    dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_ce1;
wire   [15:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_q1;
wire   [3:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_address0;
wire    dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_ce0;
wire   [15:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_q0;
wire   [3:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_address1;
wire    dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_ce1;
wire   [15:0] dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_q1;
wire   [5:0] dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_address0;
wire    dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_ce0;
wire    dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_we0;
wire   [15:0] dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_d0;
wire   [5:0] dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_address1;
wire    dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_ce1;
wire    dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_we1;
wire   [15:0] dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_d1;
wire    ap_chn_write_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i;
wire    dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_pipo_status;
wire    dct_Loop_2_proc_U0_ap_start;
wire    dct_Loop_2_proc_U0_ap_done;
reg    dct_Loop_2_proc_U0_ap_continue;
wire    dct_Loop_2_proc_U0_ap_idle;
wire    dct_Loop_2_proc_U0_ap_ready;
wire   [5:0] dct_Loop_2_proc_U0_row_outbuf_i_address0;
wire    dct_Loop_2_proc_U0_row_outbuf_i_ce0;
wire   [15:0] dct_Loop_2_proc_U0_row_outbuf_i_q0;
wire   [3:0] dct_Loop_2_proc_U0_col_inbuf_0_address0;
wire    dct_Loop_2_proc_U0_col_inbuf_0_ce0;
wire    dct_Loop_2_proc_U0_col_inbuf_0_we0;
wire   [15:0] dct_Loop_2_proc_U0_col_inbuf_0_d0;
wire   [3:0] dct_Loop_2_proc_U0_col_inbuf_1_address0;
wire    dct_Loop_2_proc_U0_col_inbuf_1_ce0;
wire    dct_Loop_2_proc_U0_col_inbuf_1_we0;
wire   [15:0] dct_Loop_2_proc_U0_col_inbuf_1_d0;
wire   [3:0] dct_Loop_2_proc_U0_col_inbuf_2_address0;
wire    dct_Loop_2_proc_U0_col_inbuf_2_ce0;
wire    dct_Loop_2_proc_U0_col_inbuf_2_we0;
wire   [15:0] dct_Loop_2_proc_U0_col_inbuf_2_d0;
wire   [3:0] dct_Loop_2_proc_U0_col_inbuf_3_address0;
wire    dct_Loop_2_proc_U0_col_inbuf_3_ce0;
wire    dct_Loop_2_proc_U0_col_inbuf_3_we0;
wire   [15:0] dct_Loop_2_proc_U0_col_inbuf_3_d0;
reg    ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_3;
wire    dct_Loop_2_proc_U0_col_inbuf_3_pipo_status;
reg    ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status = 1'b0;
reg    ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status;
reg    ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_0;
wire    dct_Loop_2_proc_U0_col_inbuf_0_pipo_status;
reg    ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status = 1'b0;
reg    ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status;
reg    ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_1;
wire    dct_Loop_2_proc_U0_col_inbuf_1_pipo_status;
reg    ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status = 1'b0;
reg    ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status;
reg    ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_2;
wire    dct_Loop_2_proc_U0_col_inbuf_2_pipo_status;
reg    ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status = 1'b0;
reg    ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status;
wire    dct_Loop_Col_DCT_Loop_proc_U0_ap_start;
wire    dct_Loop_Col_DCT_Loop_proc_U0_ap_done;
wire    dct_Loop_Col_DCT_Loop_proc_U0_ap_continue;
wire    dct_Loop_Col_DCT_Loop_proc_U0_ap_idle;
wire    dct_Loop_Col_DCT_Loop_proc_U0_ap_ready;
wire   [3:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_address0;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_ce0;
wire   [15:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_q0;
wire   [3:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_address1;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_ce1;
wire   [15:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_q1;
wire   [3:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_address0;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_ce0;
wire   [15:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_q0;
wire   [3:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_address1;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_ce1;
wire   [15:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_q1;
wire   [3:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_address0;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_ce0;
wire   [15:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_q0;
wire   [3:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_address1;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_ce1;
wire   [15:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_q1;
wire   [3:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_address0;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_ce0;
wire   [15:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_q0;
wire   [3:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_address1;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_ce1;
wire   [15:0] dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_q1;
wire   [5:0] dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_address0;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_ce0;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_we0;
wire   [15:0] dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_d0;
wire   [5:0] dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_address1;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_ce1;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_we1;
wire   [15:0] dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_d1;
wire    ap_chn_write_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i;
wire    dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_pipo_status;
wire    dct_Loop_4_proc_U0_ap_start;
wire    dct_Loop_4_proc_U0_ap_done;
wire    dct_Loop_4_proc_U0_ap_continue;
wire    dct_Loop_4_proc_U0_ap_idle;
wire    dct_Loop_4_proc_U0_ap_ready;
wire   [5:0] dct_Loop_4_proc_U0_col_outbuf_i_address0;
wire    dct_Loop_4_proc_U0_col_outbuf_i_ce0;
wire   [15:0] dct_Loop_4_proc_U0_col_outbuf_i_q0;
wire   [5:0] dct_Loop_4_proc_U0_buf_2d_out_address0;
wire    dct_Loop_4_proc_U0_buf_2d_out_ce0;
wire    dct_Loop_4_proc_U0_buf_2d_out_we0;
wire   [15:0] dct_Loop_4_proc_U0_buf_2d_out_d0;
wire    ap_chn_write_dct_Loop_4_proc_U0_buf_2d_out;
wire    dct_Loop_4_proc_U0_buf_2d_out_pipo_status;
wire    dct_write_data_U0_ap_start;
wire    dct_write_data_U0_ap_done;
wire    dct_write_data_U0_ap_continue;
wire    dct_write_data_U0_ap_idle;
wire    dct_write_data_U0_ap_ready;
wire   [5:0] dct_write_data_U0_buf_r_address0;
wire    dct_write_data_U0_buf_r_ce0;
wire   [15:0] dct_write_data_U0_buf_r_q0;
wire   [5:0] dct_write_data_U0_buf_r_address1;
wire    dct_write_data_U0_buf_r_ce1;
wire   [15:0] dct_write_data_U0_buf_r_q1;
wire   [5:0] dct_write_data_U0_output_r_address0;
wire    dct_write_data_U0_output_r_ce0;
wire    dct_write_data_U0_output_r_we0;
wire   [15:0] dct_write_data_U0_output_r_d0;
wire   [5:0] dct_write_data_U0_output_r_address1;
wire    dct_write_data_U0_output_r_ce1;
wire    dct_write_data_U0_output_r_we1;
wire   [15:0] dct_write_data_U0_output_r_d1;
wire    ap_sig_hs_continue;
wire    buf_2d_in_0_i_full_n;
wire    buf_2d_in_0_i_write;
wire    buf_2d_in_0_t_empty_n;
wire    buf_2d_in_0_t_read;
wire    buf_2d_in_1_i_full_n;
wire    buf_2d_in_1_i_write;
wire    buf_2d_in_1_t_empty_n;
wire    buf_2d_in_1_t_read;
wire    buf_2d_in_2_i_full_n;
wire    buf_2d_in_2_i_write;
wire    buf_2d_in_2_t_empty_n;
wire    buf_2d_in_2_t_read;
wire    buf_2d_in_3_i_full_n;
wire    buf_2d_in_3_i_write;
wire    buf_2d_in_3_t_empty_n;
wire    buf_2d_in_3_t_read;
wire    row_outbuf_i_i_full_n;
wire    row_outbuf_i_i_write;
wire    row_outbuf_i_t_empty_n;
wire    row_outbuf_i_t_read;
wire    col_inbuf_0_i_full_n;
wire    col_inbuf_0_i_write;
wire    col_inbuf_0_t_empty_n;
wire    col_inbuf_0_t_read;
wire   [15:0] col_inbuf_0_t_d1;
wire    col_inbuf_0_t_we1;
wire    col_inbuf_1_i_full_n;
wire    col_inbuf_1_i_write;
wire    col_inbuf_1_t_empty_n;
wire    col_inbuf_1_t_read;
wire   [15:0] col_inbuf_1_t_d1;
wire    col_inbuf_1_t_we1;
wire    col_inbuf_2_i_full_n;
wire    col_inbuf_2_i_write;
wire    col_inbuf_2_t_empty_n;
wire    col_inbuf_2_t_read;
wire   [15:0] col_inbuf_2_t_d1;
wire    col_inbuf_2_t_we1;
wire    col_inbuf_3_i_full_n;
wire    col_inbuf_3_i_write;
wire    col_inbuf_3_t_empty_n;
wire    col_inbuf_3_t_read;
wire   [15:0] col_inbuf_3_t_d1;
wire    col_inbuf_3_t_we1;
wire    col_outbuf_i_i_full_n;
wire    col_outbuf_i_i_write;
wire    col_outbuf_i_t_empty_n;
wire    col_outbuf_i_t_read;
wire    buf_2d_out_i_full_n;
wire    buf_2d_out_i_write;
wire    buf_2d_out_t_empty_n;
wire    buf_2d_out_t_read;
wire   [15:0] buf_2d_out_t_d1;
wire    buf_2d_out_t_we1;
reg    ap_reg_procdone_dct_read_data_U0 = 1'b0;
reg    ap_sig_hs_done;
reg    ap_reg_procdone_dct_Loop_Row_DCT_Loop_proc_U0 = 1'b0;
reg    ap_reg_procdone_dct_Loop_2_proc_U0 = 1'b0;
reg    ap_reg_procdone_dct_Loop_Col_DCT_Loop_proc_U0 = 1'b0;
reg    ap_reg_procdone_dct_Loop_4_proc_U0 = 1'b0;
reg    ap_reg_procdone_dct_write_data_U0 = 1'b0;
reg    ap_CS;
wire    ap_sig_top_allready;


dct_row_outbuf_i #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
row_outbuf_i_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .i_address0( row_outbuf_i_i_address0 ),
    .i_ce0( row_outbuf_i_i_ce0 ),
    .i_we0( row_outbuf_i_i_we0 ),
    .i_d0( row_outbuf_i_i_d0 ),
    .i_q0( row_outbuf_i_i_q0 ),
    .i_address1( row_outbuf_i_i_address1 ),
    .i_ce1( row_outbuf_i_i_ce1 ),
    .i_we1( row_outbuf_i_i_we1 ),
    .i_d1( row_outbuf_i_i_d1 ),
    .t_address0( row_outbuf_i_t_address0 ),
    .t_ce0( row_outbuf_i_t_ce0 ),
    .t_we0( row_outbuf_i_t_we0 ),
    .t_d0( row_outbuf_i_t_d0 ),
    .t_q0( row_outbuf_i_t_q0 ),
    .t_address1( row_outbuf_i_t_address1 ),
    .t_ce1( row_outbuf_i_t_ce1 ),
    .t_we1( row_outbuf_i_t_we1 ),
    .t_d1( row_outbuf_i_t_d1 ),
    .i_ce( row_outbuf_i_U_ap_dummy_ce ),
    .t_ce( row_outbuf_i_U_ap_dummy_ce ),
    .i_full_n( row_outbuf_i_i_full_n ),
    .i_write( row_outbuf_i_i_write ),
    .t_empty_n( row_outbuf_i_t_empty_n ),
    .t_read( row_outbuf_i_t_read )
);

dct_row_outbuf_i #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
col_outbuf_i_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .i_address0( col_outbuf_i_i_address0 ),
    .i_ce0( col_outbuf_i_i_ce0 ),
    .i_we0( col_outbuf_i_i_we0 ),
    .i_d0( col_outbuf_i_i_d0 ),
    .i_q0( col_outbuf_i_i_q0 ),
    .i_address1( col_outbuf_i_i_address1 ),
    .i_ce1( col_outbuf_i_i_ce1 ),
    .i_we1( col_outbuf_i_i_we1 ),
    .i_d1( col_outbuf_i_i_d1 ),
    .t_address0( col_outbuf_i_t_address0 ),
    .t_ce0( col_outbuf_i_t_ce0 ),
    .t_we0( col_outbuf_i_t_we0 ),
    .t_d0( col_outbuf_i_t_d0 ),
    .t_q0( col_outbuf_i_t_q0 ),
    .t_address1( col_outbuf_i_t_address1 ),
    .t_ce1( col_outbuf_i_t_ce1 ),
    .t_we1( col_outbuf_i_t_we1 ),
    .t_d1( col_outbuf_i_t_d1 ),
    .i_ce( col_outbuf_i_U_ap_dummy_ce ),
    .t_ce( col_outbuf_i_U_ap_dummy_ce ),
    .i_full_n( col_outbuf_i_i_full_n ),
    .i_write( col_outbuf_i_i_write ),
    .t_empty_n( col_outbuf_i_t_empty_n ),
    .t_read( col_outbuf_i_t_read )
);

dct_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
col_inbuf_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .i_address0( col_inbuf_0_i_address0 ),
    .i_ce0( col_inbuf_0_i_ce0 ),
    .i_we0( col_inbuf_0_i_we0 ),
    .i_d0( col_inbuf_0_i_d0 ),
    .i_q0( col_inbuf_0_i_q0 ),
    .i_address1( col_inbuf_0_i_address1 ),
    .i_ce1( col_inbuf_0_i_ce1 ),
    .i_q1( col_inbuf_0_i_q1 ),
    .t_address0( col_inbuf_0_t_address0 ),
    .t_ce0( col_inbuf_0_t_ce0 ),
    .t_we0( col_inbuf_0_t_we0 ),
    .t_d0( col_inbuf_0_t_d0 ),
    .t_q0( col_inbuf_0_t_q0 ),
    .t_address1( col_inbuf_0_t_address1 ),
    .t_ce1( col_inbuf_0_t_ce1 ),
    .t_q1( col_inbuf_0_t_q1 ),
    .i_ce( col_inbuf_0_U_ap_dummy_ce ),
    .t_ce( col_inbuf_0_U_ap_dummy_ce ),
    .i_full_n( col_inbuf_0_i_full_n ),
    .i_write( col_inbuf_0_i_write ),
    .t_empty_n( col_inbuf_0_t_empty_n ),
    .t_read( col_inbuf_0_t_read )
);

dct_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
col_inbuf_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .i_address0( col_inbuf_1_i_address0 ),
    .i_ce0( col_inbuf_1_i_ce0 ),
    .i_we0( col_inbuf_1_i_we0 ),
    .i_d0( col_inbuf_1_i_d0 ),
    .i_q0( col_inbuf_1_i_q0 ),
    .i_address1( col_inbuf_1_i_address1 ),
    .i_ce1( col_inbuf_1_i_ce1 ),
    .i_q1( col_inbuf_1_i_q1 ),
    .t_address0( col_inbuf_1_t_address0 ),
    .t_ce0( col_inbuf_1_t_ce0 ),
    .t_we0( col_inbuf_1_t_we0 ),
    .t_d0( col_inbuf_1_t_d0 ),
    .t_q0( col_inbuf_1_t_q0 ),
    .t_address1( col_inbuf_1_t_address1 ),
    .t_ce1( col_inbuf_1_t_ce1 ),
    .t_q1( col_inbuf_1_t_q1 ),
    .i_ce( col_inbuf_1_U_ap_dummy_ce ),
    .t_ce( col_inbuf_1_U_ap_dummy_ce ),
    .i_full_n( col_inbuf_1_i_full_n ),
    .i_write( col_inbuf_1_i_write ),
    .t_empty_n( col_inbuf_1_t_empty_n ),
    .t_read( col_inbuf_1_t_read )
);

dct_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
col_inbuf_2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .i_address0( col_inbuf_2_i_address0 ),
    .i_ce0( col_inbuf_2_i_ce0 ),
    .i_we0( col_inbuf_2_i_we0 ),
    .i_d0( col_inbuf_2_i_d0 ),
    .i_q0( col_inbuf_2_i_q0 ),
    .i_address1( col_inbuf_2_i_address1 ),
    .i_ce1( col_inbuf_2_i_ce1 ),
    .i_q1( col_inbuf_2_i_q1 ),
    .t_address0( col_inbuf_2_t_address0 ),
    .t_ce0( col_inbuf_2_t_ce0 ),
    .t_we0( col_inbuf_2_t_we0 ),
    .t_d0( col_inbuf_2_t_d0 ),
    .t_q0( col_inbuf_2_t_q0 ),
    .t_address1( col_inbuf_2_t_address1 ),
    .t_ce1( col_inbuf_2_t_ce1 ),
    .t_q1( col_inbuf_2_t_q1 ),
    .i_ce( col_inbuf_2_U_ap_dummy_ce ),
    .t_ce( col_inbuf_2_U_ap_dummy_ce ),
    .i_full_n( col_inbuf_2_i_full_n ),
    .i_write( col_inbuf_2_i_write ),
    .t_empty_n( col_inbuf_2_t_empty_n ),
    .t_read( col_inbuf_2_t_read )
);

dct_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
col_inbuf_3_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .i_address0( col_inbuf_3_i_address0 ),
    .i_ce0( col_inbuf_3_i_ce0 ),
    .i_we0( col_inbuf_3_i_we0 ),
    .i_d0( col_inbuf_3_i_d0 ),
    .i_q0( col_inbuf_3_i_q0 ),
    .i_address1( col_inbuf_3_i_address1 ),
    .i_ce1( col_inbuf_3_i_ce1 ),
    .i_q1( col_inbuf_3_i_q1 ),
    .t_address0( col_inbuf_3_t_address0 ),
    .t_ce0( col_inbuf_3_t_ce0 ),
    .t_we0( col_inbuf_3_t_we0 ),
    .t_d0( col_inbuf_3_t_d0 ),
    .t_q0( col_inbuf_3_t_q0 ),
    .t_address1( col_inbuf_3_t_address1 ),
    .t_ce1( col_inbuf_3_t_ce1 ),
    .t_q1( col_inbuf_3_t_q1 ),
    .i_ce( col_inbuf_3_U_ap_dummy_ce ),
    .t_ce( col_inbuf_3_U_ap_dummy_ce ),
    .i_full_n( col_inbuf_3_i_full_n ),
    .i_write( col_inbuf_3_i_write ),
    .t_empty_n( col_inbuf_3_t_empty_n ),
    .t_read( col_inbuf_3_t_read )
);

dct_buf_2d_in_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
buf_2d_in_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .i_address0( buf_2d_in_0_i_address0 ),
    .i_ce0( buf_2d_in_0_i_ce0 ),
    .i_we0( buf_2d_in_0_i_we0 ),
    .i_d0( buf_2d_in_0_i_d0 ),
    .i_q0( buf_2d_in_0_i_q0 ),
    .i_address1( buf_2d_in_0_i_address1 ),
    .i_ce1( buf_2d_in_0_i_ce1 ),
    .i_we1( buf_2d_in_0_i_we1 ),
    .i_d1( buf_2d_in_0_i_d1 ),
    .i_q1( buf_2d_in_0_i_q1 ),
    .t_address0( buf_2d_in_0_t_address0 ),
    .t_ce0( buf_2d_in_0_t_ce0 ),
    .t_we0( buf_2d_in_0_t_we0 ),
    .t_d0( buf_2d_in_0_t_d0 ),
    .t_q0( buf_2d_in_0_t_q0 ),
    .t_address1( buf_2d_in_0_t_address1 ),
    .t_ce1( buf_2d_in_0_t_ce1 ),
    .t_we1( buf_2d_in_0_t_we1 ),
    .t_d1( buf_2d_in_0_t_d1 ),
    .t_q1( buf_2d_in_0_t_q1 ),
    .i_ce( buf_2d_in_0_U_ap_dummy_ce ),
    .t_ce( buf_2d_in_0_U_ap_dummy_ce ),
    .i_full_n( buf_2d_in_0_i_full_n ),
    .i_write( buf_2d_in_0_i_write ),
    .t_empty_n( buf_2d_in_0_t_empty_n ),
    .t_read( buf_2d_in_0_t_read )
);

dct_buf_2d_in_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
buf_2d_in_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .i_address0( buf_2d_in_1_i_address0 ),
    .i_ce0( buf_2d_in_1_i_ce0 ),
    .i_we0( buf_2d_in_1_i_we0 ),
    .i_d0( buf_2d_in_1_i_d0 ),
    .i_q0( buf_2d_in_1_i_q0 ),
    .i_address1( buf_2d_in_1_i_address1 ),
    .i_ce1( buf_2d_in_1_i_ce1 ),
    .i_we1( buf_2d_in_1_i_we1 ),
    .i_d1( buf_2d_in_1_i_d1 ),
    .i_q1( buf_2d_in_1_i_q1 ),
    .t_address0( buf_2d_in_1_t_address0 ),
    .t_ce0( buf_2d_in_1_t_ce0 ),
    .t_we0( buf_2d_in_1_t_we0 ),
    .t_d0( buf_2d_in_1_t_d0 ),
    .t_q0( buf_2d_in_1_t_q0 ),
    .t_address1( buf_2d_in_1_t_address1 ),
    .t_ce1( buf_2d_in_1_t_ce1 ),
    .t_we1( buf_2d_in_1_t_we1 ),
    .t_d1( buf_2d_in_1_t_d1 ),
    .t_q1( buf_2d_in_1_t_q1 ),
    .i_ce( buf_2d_in_1_U_ap_dummy_ce ),
    .t_ce( buf_2d_in_1_U_ap_dummy_ce ),
    .i_full_n( buf_2d_in_1_i_full_n ),
    .i_write( buf_2d_in_1_i_write ),
    .t_empty_n( buf_2d_in_1_t_empty_n ),
    .t_read( buf_2d_in_1_t_read )
);

dct_buf_2d_in_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
buf_2d_in_2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .i_address0( buf_2d_in_2_i_address0 ),
    .i_ce0( buf_2d_in_2_i_ce0 ),
    .i_we0( buf_2d_in_2_i_we0 ),
    .i_d0( buf_2d_in_2_i_d0 ),
    .i_q0( buf_2d_in_2_i_q0 ),
    .i_address1( buf_2d_in_2_i_address1 ),
    .i_ce1( buf_2d_in_2_i_ce1 ),
    .i_we1( buf_2d_in_2_i_we1 ),
    .i_d1( buf_2d_in_2_i_d1 ),
    .i_q1( buf_2d_in_2_i_q1 ),
    .t_address0( buf_2d_in_2_t_address0 ),
    .t_ce0( buf_2d_in_2_t_ce0 ),
    .t_we0( buf_2d_in_2_t_we0 ),
    .t_d0( buf_2d_in_2_t_d0 ),
    .t_q0( buf_2d_in_2_t_q0 ),
    .t_address1( buf_2d_in_2_t_address1 ),
    .t_ce1( buf_2d_in_2_t_ce1 ),
    .t_we1( buf_2d_in_2_t_we1 ),
    .t_d1( buf_2d_in_2_t_d1 ),
    .t_q1( buf_2d_in_2_t_q1 ),
    .i_ce( buf_2d_in_2_U_ap_dummy_ce ),
    .t_ce( buf_2d_in_2_U_ap_dummy_ce ),
    .i_full_n( buf_2d_in_2_i_full_n ),
    .i_write( buf_2d_in_2_i_write ),
    .t_empty_n( buf_2d_in_2_t_empty_n ),
    .t_read( buf_2d_in_2_t_read )
);

dct_buf_2d_in_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
buf_2d_in_3_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .i_address0( buf_2d_in_3_i_address0 ),
    .i_ce0( buf_2d_in_3_i_ce0 ),
    .i_we0( buf_2d_in_3_i_we0 ),
    .i_d0( buf_2d_in_3_i_d0 ),
    .i_q0( buf_2d_in_3_i_q0 ),
    .i_address1( buf_2d_in_3_i_address1 ),
    .i_ce1( buf_2d_in_3_i_ce1 ),
    .i_we1( buf_2d_in_3_i_we1 ),
    .i_d1( buf_2d_in_3_i_d1 ),
    .i_q1( buf_2d_in_3_i_q1 ),
    .t_address0( buf_2d_in_3_t_address0 ),
    .t_ce0( buf_2d_in_3_t_ce0 ),
    .t_we0( buf_2d_in_3_t_we0 ),
    .t_d0( buf_2d_in_3_t_d0 ),
    .t_q0( buf_2d_in_3_t_q0 ),
    .t_address1( buf_2d_in_3_t_address1 ),
    .t_ce1( buf_2d_in_3_t_ce1 ),
    .t_we1( buf_2d_in_3_t_we1 ),
    .t_d1( buf_2d_in_3_t_d1 ),
    .t_q1( buf_2d_in_3_t_q1 ),
    .i_ce( buf_2d_in_3_U_ap_dummy_ce ),
    .t_ce( buf_2d_in_3_U_ap_dummy_ce ),
    .i_full_n( buf_2d_in_3_i_full_n ),
    .i_write( buf_2d_in_3_i_write ),
    .t_empty_n( buf_2d_in_3_t_empty_n ),
    .t_read( buf_2d_in_3_t_read )
);

dct_buf_2d_out #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
buf_2d_out_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .i_address0( buf_2d_out_i_address0 ),
    .i_ce0( buf_2d_out_i_ce0 ),
    .i_we0( buf_2d_out_i_we0 ),
    .i_d0( buf_2d_out_i_d0 ),
    .i_q0( buf_2d_out_i_q0 ),
    .i_address1( buf_2d_out_i_address1 ),
    .i_ce1( buf_2d_out_i_ce1 ),
    .i_q1( buf_2d_out_i_q1 ),
    .t_address0( buf_2d_out_t_address0 ),
    .t_ce0( buf_2d_out_t_ce0 ),
    .t_we0( buf_2d_out_t_we0 ),
    .t_d0( buf_2d_out_t_d0 ),
    .t_q0( buf_2d_out_t_q0 ),
    .t_address1( buf_2d_out_t_address1 ),
    .t_ce1( buf_2d_out_t_ce1 ),
    .t_q1( buf_2d_out_t_q1 ),
    .i_ce( buf_2d_out_U_ap_dummy_ce ),
    .t_ce( buf_2d_out_U_ap_dummy_ce ),
    .i_full_n( buf_2d_out_i_full_n ),
    .i_write( buf_2d_out_i_write ),
    .t_empty_n( buf_2d_out_t_empty_n ),
    .t_read( buf_2d_out_t_read )
);

dct_read_data dct_read_data_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( dct_read_data_U0_ap_start ),
    .ap_done( dct_read_data_U0_ap_done ),
    .ap_continue( dct_read_data_U0_ap_continue ),
    .ap_idle( dct_read_data_U0_ap_idle ),
    .ap_ready( dct_read_data_U0_ap_ready ),
    .input_r_address0( dct_read_data_U0_input_r_address0 ),
    .input_r_ce0( dct_read_data_U0_input_r_ce0 ),
    .input_r_q0( dct_read_data_U0_input_r_q0 ),
    .input_r_address1( dct_read_data_U0_input_r_address1 ),
    .input_r_ce1( dct_read_data_U0_input_r_ce1 ),
    .input_r_q1( dct_read_data_U0_input_r_q1 ),
    .buf_0_address0( dct_read_data_U0_buf_0_address0 ),
    .buf_0_ce0( dct_read_data_U0_buf_0_ce0 ),
    .buf_0_we0( dct_read_data_U0_buf_0_we0 ),
    .buf_0_d0( dct_read_data_U0_buf_0_d0 ),
    .buf_0_address1( dct_read_data_U0_buf_0_address1 ),
    .buf_0_ce1( dct_read_data_U0_buf_0_ce1 ),
    .buf_0_we1( dct_read_data_U0_buf_0_we1 ),
    .buf_0_d1( dct_read_data_U0_buf_0_d1 ),
    .buf_1_address0( dct_read_data_U0_buf_1_address0 ),
    .buf_1_ce0( dct_read_data_U0_buf_1_ce0 ),
    .buf_1_we0( dct_read_data_U0_buf_1_we0 ),
    .buf_1_d0( dct_read_data_U0_buf_1_d0 ),
    .buf_1_address1( dct_read_data_U0_buf_1_address1 ),
    .buf_1_ce1( dct_read_data_U0_buf_1_ce1 ),
    .buf_1_we1( dct_read_data_U0_buf_1_we1 ),
    .buf_1_d1( dct_read_data_U0_buf_1_d1 ),
    .buf_2_address0( dct_read_data_U0_buf_2_address0 ),
    .buf_2_ce0( dct_read_data_U0_buf_2_ce0 ),
    .buf_2_we0( dct_read_data_U0_buf_2_we0 ),
    .buf_2_d0( dct_read_data_U0_buf_2_d0 ),
    .buf_2_address1( dct_read_data_U0_buf_2_address1 ),
    .buf_2_ce1( dct_read_data_U0_buf_2_ce1 ),
    .buf_2_we1( dct_read_data_U0_buf_2_we1 ),
    .buf_2_d1( dct_read_data_U0_buf_2_d1 ),
    .buf_3_address0( dct_read_data_U0_buf_3_address0 ),
    .buf_3_ce0( dct_read_data_U0_buf_3_ce0 ),
    .buf_3_we0( dct_read_data_U0_buf_3_we0 ),
    .buf_3_d0( dct_read_data_U0_buf_3_d0 ),
    .buf_3_address1( dct_read_data_U0_buf_3_address1 ),
    .buf_3_ce1( dct_read_data_U0_buf_3_ce1 ),
    .buf_3_we1( dct_read_data_U0_buf_3_we1 ),
    .buf_3_d1( dct_read_data_U0_buf_3_d1 )
);

dct_Loop_Row_DCT_Loop_proc dct_Loop_Row_DCT_Loop_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( dct_Loop_Row_DCT_Loop_proc_U0_ap_start ),
    .ap_done( dct_Loop_Row_DCT_Loop_proc_U0_ap_done ),
    .ap_continue( dct_Loop_Row_DCT_Loop_proc_U0_ap_continue ),
    .ap_idle( dct_Loop_Row_DCT_Loop_proc_U0_ap_idle ),
    .ap_ready( dct_Loop_Row_DCT_Loop_proc_U0_ap_ready ),
    .buf_2d_in_0_address0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_address0 ),
    .buf_2d_in_0_ce0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_ce0 ),
    .buf_2d_in_0_q0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_q0 ),
    .buf_2d_in_0_address1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_address1 ),
    .buf_2d_in_0_ce1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_ce1 ),
    .buf_2d_in_0_q1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_q1 ),
    .buf_2d_in_1_address0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_address0 ),
    .buf_2d_in_1_ce0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_ce0 ),
    .buf_2d_in_1_q0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_q0 ),
    .buf_2d_in_1_address1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_address1 ),
    .buf_2d_in_1_ce1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_ce1 ),
    .buf_2d_in_1_q1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_q1 ),
    .buf_2d_in_2_address0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_address0 ),
    .buf_2d_in_2_ce0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_ce0 ),
    .buf_2d_in_2_q0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_q0 ),
    .buf_2d_in_2_address1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_address1 ),
    .buf_2d_in_2_ce1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_ce1 ),
    .buf_2d_in_2_q1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_q1 ),
    .buf_2d_in_3_address0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_address0 ),
    .buf_2d_in_3_ce0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_ce0 ),
    .buf_2d_in_3_q0( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_q0 ),
    .buf_2d_in_3_address1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_address1 ),
    .buf_2d_in_3_ce1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_ce1 ),
    .buf_2d_in_3_q1( dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_q1 ),
    .row_outbuf_i_address0( dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_address0 ),
    .row_outbuf_i_ce0( dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_ce0 ),
    .row_outbuf_i_we0( dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_we0 ),
    .row_outbuf_i_d0( dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_d0 ),
    .row_outbuf_i_address1( dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_address1 ),
    .row_outbuf_i_ce1( dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_ce1 ),
    .row_outbuf_i_we1( dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_we1 ),
    .row_outbuf_i_d1( dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_d1 )
);

dct_Loop_2_proc dct_Loop_2_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( dct_Loop_2_proc_U0_ap_start ),
    .ap_done( dct_Loop_2_proc_U0_ap_done ),
    .ap_continue( dct_Loop_2_proc_U0_ap_continue ),
    .ap_idle( dct_Loop_2_proc_U0_ap_idle ),
    .ap_ready( dct_Loop_2_proc_U0_ap_ready ),
    .row_outbuf_i_address0( dct_Loop_2_proc_U0_row_outbuf_i_address0 ),
    .row_outbuf_i_ce0( dct_Loop_2_proc_U0_row_outbuf_i_ce0 ),
    .row_outbuf_i_q0( dct_Loop_2_proc_U0_row_outbuf_i_q0 ),
    .col_inbuf_0_address0( dct_Loop_2_proc_U0_col_inbuf_0_address0 ),
    .col_inbuf_0_ce0( dct_Loop_2_proc_U0_col_inbuf_0_ce0 ),
    .col_inbuf_0_we0( dct_Loop_2_proc_U0_col_inbuf_0_we0 ),
    .col_inbuf_0_d0( dct_Loop_2_proc_U0_col_inbuf_0_d0 ),
    .col_inbuf_1_address0( dct_Loop_2_proc_U0_col_inbuf_1_address0 ),
    .col_inbuf_1_ce0( dct_Loop_2_proc_U0_col_inbuf_1_ce0 ),
    .col_inbuf_1_we0( dct_Loop_2_proc_U0_col_inbuf_1_we0 ),
    .col_inbuf_1_d0( dct_Loop_2_proc_U0_col_inbuf_1_d0 ),
    .col_inbuf_2_address0( dct_Loop_2_proc_U0_col_inbuf_2_address0 ),
    .col_inbuf_2_ce0( dct_Loop_2_proc_U0_col_inbuf_2_ce0 ),
    .col_inbuf_2_we0( dct_Loop_2_proc_U0_col_inbuf_2_we0 ),
    .col_inbuf_2_d0( dct_Loop_2_proc_U0_col_inbuf_2_d0 ),
    .col_inbuf_3_address0( dct_Loop_2_proc_U0_col_inbuf_3_address0 ),
    .col_inbuf_3_ce0( dct_Loop_2_proc_U0_col_inbuf_3_ce0 ),
    .col_inbuf_3_we0( dct_Loop_2_proc_U0_col_inbuf_3_we0 ),
    .col_inbuf_3_d0( dct_Loop_2_proc_U0_col_inbuf_3_d0 )
);

dct_Loop_Col_DCT_Loop_proc dct_Loop_Col_DCT_Loop_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( dct_Loop_Col_DCT_Loop_proc_U0_ap_start ),
    .ap_done( dct_Loop_Col_DCT_Loop_proc_U0_ap_done ),
    .ap_continue( dct_Loop_Col_DCT_Loop_proc_U0_ap_continue ),
    .ap_idle( dct_Loop_Col_DCT_Loop_proc_U0_ap_idle ),
    .ap_ready( dct_Loop_Col_DCT_Loop_proc_U0_ap_ready ),
    .col_inbuf_0_address0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_address0 ),
    .col_inbuf_0_ce0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_ce0 ),
    .col_inbuf_0_q0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_q0 ),
    .col_inbuf_0_address1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_address1 ),
    .col_inbuf_0_ce1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_ce1 ),
    .col_inbuf_0_q1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_q1 ),
    .col_inbuf_1_address0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_address0 ),
    .col_inbuf_1_ce0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_ce0 ),
    .col_inbuf_1_q0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_q0 ),
    .col_inbuf_1_address1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_address1 ),
    .col_inbuf_1_ce1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_ce1 ),
    .col_inbuf_1_q1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_q1 ),
    .col_inbuf_2_address0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_address0 ),
    .col_inbuf_2_ce0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_ce0 ),
    .col_inbuf_2_q0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_q0 ),
    .col_inbuf_2_address1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_address1 ),
    .col_inbuf_2_ce1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_ce1 ),
    .col_inbuf_2_q1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_q1 ),
    .col_inbuf_3_address0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_address0 ),
    .col_inbuf_3_ce0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_ce0 ),
    .col_inbuf_3_q0( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_q0 ),
    .col_inbuf_3_address1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_address1 ),
    .col_inbuf_3_ce1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_ce1 ),
    .col_inbuf_3_q1( dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_q1 ),
    .col_outbuf_i_address0( dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_address0 ),
    .col_outbuf_i_ce0( dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_ce0 ),
    .col_outbuf_i_we0( dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_we0 ),
    .col_outbuf_i_d0( dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_d0 ),
    .col_outbuf_i_address1( dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_address1 ),
    .col_outbuf_i_ce1( dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_ce1 ),
    .col_outbuf_i_we1( dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_we1 ),
    .col_outbuf_i_d1( dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_d1 )
);

dct_Loop_4_proc dct_Loop_4_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( dct_Loop_4_proc_U0_ap_start ),
    .ap_done( dct_Loop_4_proc_U0_ap_done ),
    .ap_continue( dct_Loop_4_proc_U0_ap_continue ),
    .ap_idle( dct_Loop_4_proc_U0_ap_idle ),
    .ap_ready( dct_Loop_4_proc_U0_ap_ready ),
    .col_outbuf_i_address0( dct_Loop_4_proc_U0_col_outbuf_i_address0 ),
    .col_outbuf_i_ce0( dct_Loop_4_proc_U0_col_outbuf_i_ce0 ),
    .col_outbuf_i_q0( dct_Loop_4_proc_U0_col_outbuf_i_q0 ),
    .buf_2d_out_address0( dct_Loop_4_proc_U0_buf_2d_out_address0 ),
    .buf_2d_out_ce0( dct_Loop_4_proc_U0_buf_2d_out_ce0 ),
    .buf_2d_out_we0( dct_Loop_4_proc_U0_buf_2d_out_we0 ),
    .buf_2d_out_d0( dct_Loop_4_proc_U0_buf_2d_out_d0 )
);

dct_write_data dct_write_data_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( dct_write_data_U0_ap_start ),
    .ap_done( dct_write_data_U0_ap_done ),
    .ap_continue( dct_write_data_U0_ap_continue ),
    .ap_idle( dct_write_data_U0_ap_idle ),
    .ap_ready( dct_write_data_U0_ap_ready ),
    .buf_r_address0( dct_write_data_U0_buf_r_address0 ),
    .buf_r_ce0( dct_write_data_U0_buf_r_ce0 ),
    .buf_r_q0( dct_write_data_U0_buf_r_q0 ),
    .buf_r_address1( dct_write_data_U0_buf_r_address1 ),
    .buf_r_ce1( dct_write_data_U0_buf_r_ce1 ),
    .buf_r_q1( dct_write_data_U0_buf_r_q1 ),
    .output_r_address0( dct_write_data_U0_output_r_address0 ),
    .output_r_ce0( dct_write_data_U0_output_r_ce0 ),
    .output_r_we0( dct_write_data_U0_output_r_we0 ),
    .output_r_d0( dct_write_data_U0_output_r_d0 ),
    .output_r_address1( dct_write_data_U0_output_r_address1 ),
    .output_r_ce1( dct_write_data_U0_output_r_ce1 ),
    .output_r_we1( dct_write_data_U0_output_r_we1 ),
    .output_r_d1( dct_write_data_U0_output_r_d1 )
);



/// ap_reg_procdone_dct_Loop_2_proc_U0 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_dct_Loop_2_proc_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_dct_Loop_2_proc_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_dct_Loop_2_proc_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == dct_Loop_2_proc_U0_ap_done)) begin
            ap_reg_procdone_dct_Loop_2_proc_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_dct_Loop_4_proc_U0 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_dct_Loop_4_proc_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_dct_Loop_4_proc_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_dct_Loop_4_proc_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == dct_Loop_4_proc_U0_ap_done)) begin
            ap_reg_procdone_dct_Loop_4_proc_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_dct_Loop_Col_DCT_Loop_proc_U0 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_dct_Loop_Col_DCT_Loop_proc_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_dct_Loop_Col_DCT_Loop_proc_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_dct_Loop_Col_DCT_Loop_proc_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == dct_Loop_Col_DCT_Loop_proc_U0_ap_done)) begin
            ap_reg_procdone_dct_Loop_Col_DCT_Loop_proc_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_dct_Loop_Row_DCT_Loop_proc_U0 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_dct_Loop_Row_DCT_Loop_proc_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_dct_Loop_Row_DCT_Loop_proc_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_dct_Loop_Row_DCT_Loop_proc_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == dct_Loop_Row_DCT_Loop_proc_U0_ap_done)) begin
            ap_reg_procdone_dct_Loop_Row_DCT_Loop_proc_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_dct_read_data_U0 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_dct_read_data_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_dct_read_data_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_dct_read_data_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == dct_read_data_U0_ap_done)) begin
            ap_reg_procdone_dct_read_data_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_dct_write_data_U0 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_dct_write_data_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_dct_write_data_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_dct_write_data_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == dct_write_data_U0_ap_done)) begin
            ap_reg_procdone_dct_write_data_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status
    if (ap_rst == 1'b1) begin
        ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == dct_Loop_2_proc_U0_ap_done) & (ap_const_logic_1 == dct_Loop_2_proc_U0_ap_continue))) begin
            ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == dct_Loop_2_proc_U0_ap_done) & (ap_const_logic_1 == dct_Loop_2_proc_U0_col_inbuf_0_pipo_status))) begin
            ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status
    if (ap_rst == 1'b1) begin
        ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == dct_Loop_2_proc_U0_ap_done) & (ap_const_logic_1 == dct_Loop_2_proc_U0_ap_continue))) begin
            ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == dct_Loop_2_proc_U0_ap_done) & (ap_const_logic_1 == dct_Loop_2_proc_U0_col_inbuf_1_pipo_status))) begin
            ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status
    if (ap_rst == 1'b1) begin
        ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == dct_Loop_2_proc_U0_ap_done) & (ap_const_logic_1 == dct_Loop_2_proc_U0_ap_continue))) begin
            ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == dct_Loop_2_proc_U0_ap_done) & (ap_const_logic_1 == dct_Loop_2_proc_U0_col_inbuf_2_pipo_status))) begin
            ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status
    if (ap_rst == 1'b1) begin
        ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == dct_Loop_2_proc_U0_ap_done) & (ap_const_logic_1 == dct_Loop_2_proc_U0_ap_continue))) begin
            ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == dct_Loop_2_proc_U0_ap_done) & (ap_const_logic_1 == dct_Loop_2_proc_U0_col_inbuf_3_pipo_status))) begin
            ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_dct_read_data_U0_buf_0_pipo_status assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_dct_read_data_U0_buf_0_pipo_status
    if (ap_rst == 1'b1) begin
        ap_reg_ready_dct_read_data_U0_buf_0_pipo_status <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == dct_read_data_U0_ap_done) & (ap_const_logic_1 == dct_read_data_U0_ap_continue))) begin
            ap_reg_ready_dct_read_data_U0_buf_0_pipo_status <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == dct_read_data_U0_ap_done) & (ap_const_logic_1 == dct_read_data_U0_buf_0_pipo_status))) begin
            ap_reg_ready_dct_read_data_U0_buf_0_pipo_status <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_dct_read_data_U0_buf_1_pipo_status assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_dct_read_data_U0_buf_1_pipo_status
    if (ap_rst == 1'b1) begin
        ap_reg_ready_dct_read_data_U0_buf_1_pipo_status <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == dct_read_data_U0_ap_done) & (ap_const_logic_1 == dct_read_data_U0_ap_continue))) begin
            ap_reg_ready_dct_read_data_U0_buf_1_pipo_status <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == dct_read_data_U0_ap_done) & (ap_const_logic_1 == dct_read_data_U0_buf_1_pipo_status))) begin
            ap_reg_ready_dct_read_data_U0_buf_1_pipo_status <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_dct_read_data_U0_buf_2_pipo_status assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_dct_read_data_U0_buf_2_pipo_status
    if (ap_rst == 1'b1) begin
        ap_reg_ready_dct_read_data_U0_buf_2_pipo_status <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == dct_read_data_U0_ap_done) & (ap_const_logic_1 == dct_read_data_U0_ap_continue))) begin
            ap_reg_ready_dct_read_data_U0_buf_2_pipo_status <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == dct_read_data_U0_ap_done) & (ap_const_logic_1 == dct_read_data_U0_buf_2_pipo_status))) begin
            ap_reg_ready_dct_read_data_U0_buf_2_pipo_status <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_dct_read_data_U0_buf_3_pipo_status assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ready_dct_read_data_U0_buf_3_pipo_status
    if (ap_rst == 1'b1) begin
        ap_reg_ready_dct_read_data_U0_buf_3_pipo_status <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == dct_read_data_U0_ap_done) & (ap_const_logic_1 == dct_read_data_U0_ap_continue))) begin
            ap_reg_ready_dct_read_data_U0_buf_3_pipo_status <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == dct_read_data_U0_ap_done) & (ap_const_logic_1 == dct_read_data_U0_buf_3_pipo_status))) begin
            ap_reg_ready_dct_read_data_U0_buf_3_pipo_status <= ap_const_logic_1;
        end
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    ap_CS <= ap_const_logic_0;
end

/// ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_0 assign process. ///
always @ (dct_Loop_2_proc_U0_ap_done or ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status) begin
    if ((ap_const_logic_1 == ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status)) begin
        ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_0 = ap_const_logic_0;
    end else begin
        ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_0 = dct_Loop_2_proc_U0_ap_done;
    end
end

/// ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_1 assign process. ///
always @ (dct_Loop_2_proc_U0_ap_done or ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status) begin
    if ((ap_const_logic_1 == ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status)) begin
        ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_1 = ap_const_logic_0;
    end else begin
        ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_1 = dct_Loop_2_proc_U0_ap_done;
    end
end

/// ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_2 assign process. ///
always @ (dct_Loop_2_proc_U0_ap_done or ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status) begin
    if ((ap_const_logic_1 == ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status)) begin
        ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_2 = ap_const_logic_0;
    end else begin
        ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_2 = dct_Loop_2_proc_U0_ap_done;
    end
end

/// ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_3 assign process. ///
always @ (dct_Loop_2_proc_U0_ap_done or ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status) begin
    if ((ap_const_logic_1 == ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status)) begin
        ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_3 = ap_const_logic_0;
    end else begin
        ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_3 = dct_Loop_2_proc_U0_ap_done;
    end
end

/// ap_chn_write_dct_read_data_U0_buf_2d_in_0 assign process. ///
always @ (dct_read_data_U0_ap_done or ap_reg_ready_dct_read_data_U0_buf_0_pipo_status) begin
    if ((ap_const_logic_1 == ap_reg_ready_dct_read_data_U0_buf_0_pipo_status)) begin
        ap_chn_write_dct_read_data_U0_buf_2d_in_0 = ap_const_logic_0;
    end else begin
        ap_chn_write_dct_read_data_U0_buf_2d_in_0 = dct_read_data_U0_ap_done;
    end
end

/// ap_chn_write_dct_read_data_U0_buf_2d_in_1 assign process. ///
always @ (dct_read_data_U0_ap_done or ap_reg_ready_dct_read_data_U0_buf_1_pipo_status) begin
    if ((ap_const_logic_1 == ap_reg_ready_dct_read_data_U0_buf_1_pipo_status)) begin
        ap_chn_write_dct_read_data_U0_buf_2d_in_1 = ap_const_logic_0;
    end else begin
        ap_chn_write_dct_read_data_U0_buf_2d_in_1 = dct_read_data_U0_ap_done;
    end
end

/// ap_chn_write_dct_read_data_U0_buf_2d_in_2 assign process. ///
always @ (dct_read_data_U0_ap_done or ap_reg_ready_dct_read_data_U0_buf_2_pipo_status) begin
    if ((ap_const_logic_1 == ap_reg_ready_dct_read_data_U0_buf_2_pipo_status)) begin
        ap_chn_write_dct_read_data_U0_buf_2d_in_2 = ap_const_logic_0;
    end else begin
        ap_chn_write_dct_read_data_U0_buf_2d_in_2 = dct_read_data_U0_ap_done;
    end
end

/// ap_chn_write_dct_read_data_U0_buf_2d_in_3 assign process. ///
always @ (dct_read_data_U0_ap_done or ap_reg_ready_dct_read_data_U0_buf_3_pipo_status) begin
    if ((ap_const_logic_1 == ap_reg_ready_dct_read_data_U0_buf_3_pipo_status)) begin
        ap_chn_write_dct_read_data_U0_buf_2d_in_3 = ap_const_logic_0;
    end else begin
        ap_chn_write_dct_read_data_U0_buf_2d_in_3 = dct_read_data_U0_ap_done;
    end
end

/// ap_idle assign process. ///
always @ (dct_read_data_U0_ap_idle or dct_Loop_Row_DCT_Loop_proc_U0_ap_idle or dct_Loop_2_proc_U0_ap_idle or dct_Loop_Col_DCT_Loop_proc_U0_ap_idle or dct_Loop_4_proc_U0_ap_idle or dct_write_data_U0_ap_idle or buf_2d_in_0_t_empty_n or buf_2d_in_1_t_empty_n or buf_2d_in_2_t_empty_n or buf_2d_in_3_t_empty_n or row_outbuf_i_t_empty_n or col_inbuf_0_t_empty_n or col_inbuf_1_t_empty_n or col_inbuf_2_t_empty_n or col_inbuf_3_t_empty_n or col_outbuf_i_t_empty_n or buf_2d_out_t_empty_n) begin
    if (((ap_const_logic_1 == dct_read_data_U0_ap_idle) & (ap_const_logic_1 == dct_Loop_Row_DCT_Loop_proc_U0_ap_idle) & (ap_const_logic_1 == dct_Loop_2_proc_U0_ap_idle) & (ap_const_logic_1 == dct_Loop_Col_DCT_Loop_proc_U0_ap_idle) & (ap_const_logic_1 == dct_Loop_4_proc_U0_ap_idle) & (ap_const_logic_1 == dct_write_data_U0_ap_idle) & (ap_const_logic_0 == buf_2d_in_0_t_empty_n) & (ap_const_logic_0 == buf_2d_in_1_t_empty_n) & (ap_const_logic_0 == buf_2d_in_2_t_empty_n) & (ap_const_logic_0 == buf_2d_in_3_t_empty_n) & (ap_const_logic_0 == row_outbuf_i_t_empty_n) & (ap_const_logic_0 == col_inbuf_0_t_empty_n) & (ap_const_logic_0 == col_inbuf_1_t_empty_n) & (ap_const_logic_0 == col_inbuf_2_t_empty_n) & (ap_const_logic_0 == col_inbuf_3_t_empty_n) & (ap_const_logic_0 == col_outbuf_i_t_empty_n) & (ap_const_logic_0 == buf_2d_out_t_empty_n))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_sig_hs_done assign process. ///
always @ (dct_write_data_U0_ap_done) begin
    if ((ap_const_logic_1 == dct_write_data_U0_ap_done)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

/// ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status assign process. ///
always @ (dct_Loop_2_proc_U0_col_inbuf_0_pipo_status or ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status) begin
    if ((ap_const_logic_0 == ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status)) begin
        ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status = dct_Loop_2_proc_U0_col_inbuf_0_pipo_status;
    end else begin
        ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status = ap_const_logic_1;
    end
end

/// ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status assign process. ///
always @ (dct_Loop_2_proc_U0_col_inbuf_1_pipo_status or ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status) begin
    if ((ap_const_logic_0 == ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status)) begin
        ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status = dct_Loop_2_proc_U0_col_inbuf_1_pipo_status;
    end else begin
        ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status = ap_const_logic_1;
    end
end

/// ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status assign process. ///
always @ (dct_Loop_2_proc_U0_col_inbuf_2_pipo_status or ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status) begin
    if ((ap_const_logic_0 == ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status)) begin
        ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status = dct_Loop_2_proc_U0_col_inbuf_2_pipo_status;
    end else begin
        ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status = ap_const_logic_1;
    end
end

/// ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status assign process. ///
always @ (dct_Loop_2_proc_U0_col_inbuf_3_pipo_status or ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status) begin
    if ((ap_const_logic_0 == ap_reg_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status)) begin
        ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status = dct_Loop_2_proc_U0_col_inbuf_3_pipo_status;
    end else begin
        ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status = ap_const_logic_1;
    end
end

/// ap_sig_ready_dct_read_data_U0_buf_0_pipo_status assign process. ///
always @ (dct_read_data_U0_buf_0_pipo_status or ap_reg_ready_dct_read_data_U0_buf_0_pipo_status) begin
    if ((ap_const_logic_0 == ap_reg_ready_dct_read_data_U0_buf_0_pipo_status)) begin
        ap_sig_ready_dct_read_data_U0_buf_0_pipo_status = dct_read_data_U0_buf_0_pipo_status;
    end else begin
        ap_sig_ready_dct_read_data_U0_buf_0_pipo_status = ap_const_logic_1;
    end
end

/// ap_sig_ready_dct_read_data_U0_buf_1_pipo_status assign process. ///
always @ (dct_read_data_U0_buf_1_pipo_status or ap_reg_ready_dct_read_data_U0_buf_1_pipo_status) begin
    if ((ap_const_logic_0 == ap_reg_ready_dct_read_data_U0_buf_1_pipo_status)) begin
        ap_sig_ready_dct_read_data_U0_buf_1_pipo_status = dct_read_data_U0_buf_1_pipo_status;
    end else begin
        ap_sig_ready_dct_read_data_U0_buf_1_pipo_status = ap_const_logic_1;
    end
end

/// ap_sig_ready_dct_read_data_U0_buf_2_pipo_status assign process. ///
always @ (dct_read_data_U0_buf_2_pipo_status or ap_reg_ready_dct_read_data_U0_buf_2_pipo_status) begin
    if ((ap_const_logic_0 == ap_reg_ready_dct_read_data_U0_buf_2_pipo_status)) begin
        ap_sig_ready_dct_read_data_U0_buf_2_pipo_status = dct_read_data_U0_buf_2_pipo_status;
    end else begin
        ap_sig_ready_dct_read_data_U0_buf_2_pipo_status = ap_const_logic_1;
    end
end

/// ap_sig_ready_dct_read_data_U0_buf_3_pipo_status assign process. ///
always @ (dct_read_data_U0_buf_3_pipo_status or ap_reg_ready_dct_read_data_U0_buf_3_pipo_status) begin
    if ((ap_const_logic_0 == ap_reg_ready_dct_read_data_U0_buf_3_pipo_status)) begin
        ap_sig_ready_dct_read_data_U0_buf_3_pipo_status = dct_read_data_U0_buf_3_pipo_status;
    end else begin
        ap_sig_ready_dct_read_data_U0_buf_3_pipo_status = ap_const_logic_1;
    end
end

/// dct_Loop_2_proc_U0_ap_continue assign process. ///
always @ (ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status or ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status or ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status or ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status) begin
    if (((ap_const_logic_1 == ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_3_pipo_status) & (ap_const_logic_1 == ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_0_pipo_status) & (ap_const_logic_1 == ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_1_pipo_status) & (ap_const_logic_1 == ap_sig_ready_dct_Loop_2_proc_U0_col_inbuf_2_pipo_status))) begin
        dct_Loop_2_proc_U0_ap_continue = ap_const_logic_1;
    end else begin
        dct_Loop_2_proc_U0_ap_continue = ap_const_logic_0;
    end
end

/// dct_read_data_U0_ap_continue assign process. ///
always @ (ap_sig_ready_dct_read_data_U0_buf_0_pipo_status or ap_sig_ready_dct_read_data_U0_buf_1_pipo_status or ap_sig_ready_dct_read_data_U0_buf_2_pipo_status or ap_sig_ready_dct_read_data_U0_buf_3_pipo_status) begin
    if (((ap_const_logic_1 == ap_sig_ready_dct_read_data_U0_buf_0_pipo_status) & (ap_const_logic_1 == ap_sig_ready_dct_read_data_U0_buf_1_pipo_status) & (ap_const_logic_1 == ap_sig_ready_dct_read_data_U0_buf_2_pipo_status) & (ap_const_logic_1 == ap_sig_ready_dct_read_data_U0_buf_3_pipo_status))) begin
        dct_read_data_U0_ap_continue = ap_const_logic_1;
    end else begin
        dct_read_data_U0_ap_continue = ap_const_logic_0;
    end
end
assign ap_chn_write_dct_Loop_4_proc_U0_buf_2d_out = dct_Loop_4_proc_U0_ap_done;
assign ap_chn_write_dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i = dct_Loop_Col_DCT_Loop_proc_U0_ap_done;
assign ap_chn_write_dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i = dct_Loop_Row_DCT_Loop_proc_U0_ap_done;
assign ap_done = ap_sig_hs_done;
assign ap_ready = ap_sig_top_allready;
assign ap_sig_hs_continue = ap_const_logic_1;
assign ap_sig_top_allready = dct_read_data_U0_ap_ready;
assign buf_2d_in_0_U_ap_dummy_ce = ap_const_logic_1;
assign buf_2d_in_0_i_address0 = dct_read_data_U0_buf_0_address0;
assign buf_2d_in_0_i_address1 = dct_read_data_U0_buf_0_address1;
assign buf_2d_in_0_i_ce0 = dct_read_data_U0_buf_0_ce0;
assign buf_2d_in_0_i_ce1 = dct_read_data_U0_buf_0_ce1;
assign buf_2d_in_0_i_d0 = dct_read_data_U0_buf_0_d0;
assign buf_2d_in_0_i_d1 = dct_read_data_U0_buf_0_d1;
assign buf_2d_in_0_i_we0 = dct_read_data_U0_buf_0_we0;
assign buf_2d_in_0_i_we1 = dct_read_data_U0_buf_0_we1;
assign buf_2d_in_0_i_write = ap_chn_write_dct_read_data_U0_buf_2d_in_0;
assign buf_2d_in_0_t_address0 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_address0;
assign buf_2d_in_0_t_address1 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_address1;
assign buf_2d_in_0_t_ce0 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_ce0;
assign buf_2d_in_0_t_ce1 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_ce1;
assign buf_2d_in_0_t_d0 = ap_const_lv16_0;
assign buf_2d_in_0_t_d1 = ap_const_lv16_0;
assign buf_2d_in_0_t_read = dct_Loop_Row_DCT_Loop_proc_U0_ap_ready;
assign buf_2d_in_0_t_we0 = ap_const_logic_0;
assign buf_2d_in_0_t_we1 = ap_const_logic_0;
assign buf_2d_in_1_U_ap_dummy_ce = ap_const_logic_1;
assign buf_2d_in_1_i_address0 = dct_read_data_U0_buf_1_address0;
assign buf_2d_in_1_i_address1 = dct_read_data_U0_buf_1_address1;
assign buf_2d_in_1_i_ce0 = dct_read_data_U0_buf_1_ce0;
assign buf_2d_in_1_i_ce1 = dct_read_data_U0_buf_1_ce1;
assign buf_2d_in_1_i_d0 = dct_read_data_U0_buf_1_d0;
assign buf_2d_in_1_i_d1 = dct_read_data_U0_buf_1_d1;
assign buf_2d_in_1_i_we0 = dct_read_data_U0_buf_1_we0;
assign buf_2d_in_1_i_we1 = dct_read_data_U0_buf_1_we1;
assign buf_2d_in_1_i_write = ap_chn_write_dct_read_data_U0_buf_2d_in_1;
assign buf_2d_in_1_t_address0 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_address0;
assign buf_2d_in_1_t_address1 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_address1;
assign buf_2d_in_1_t_ce0 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_ce0;
assign buf_2d_in_1_t_ce1 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_ce1;
assign buf_2d_in_1_t_d0 = ap_const_lv16_0;
assign buf_2d_in_1_t_d1 = ap_const_lv16_0;
assign buf_2d_in_1_t_read = dct_Loop_Row_DCT_Loop_proc_U0_ap_ready;
assign buf_2d_in_1_t_we0 = ap_const_logic_0;
assign buf_2d_in_1_t_we1 = ap_const_logic_0;
assign buf_2d_in_2_U_ap_dummy_ce = ap_const_logic_1;
assign buf_2d_in_2_i_address0 = dct_read_data_U0_buf_2_address0;
assign buf_2d_in_2_i_address1 = dct_read_data_U0_buf_2_address1;
assign buf_2d_in_2_i_ce0 = dct_read_data_U0_buf_2_ce0;
assign buf_2d_in_2_i_ce1 = dct_read_data_U0_buf_2_ce1;
assign buf_2d_in_2_i_d0 = dct_read_data_U0_buf_2_d0;
assign buf_2d_in_2_i_d1 = dct_read_data_U0_buf_2_d1;
assign buf_2d_in_2_i_we0 = dct_read_data_U0_buf_2_we0;
assign buf_2d_in_2_i_we1 = dct_read_data_U0_buf_2_we1;
assign buf_2d_in_2_i_write = ap_chn_write_dct_read_data_U0_buf_2d_in_2;
assign buf_2d_in_2_t_address0 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_address0;
assign buf_2d_in_2_t_address1 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_address1;
assign buf_2d_in_2_t_ce0 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_ce0;
assign buf_2d_in_2_t_ce1 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_ce1;
assign buf_2d_in_2_t_d0 = ap_const_lv16_0;
assign buf_2d_in_2_t_d1 = ap_const_lv16_0;
assign buf_2d_in_2_t_read = dct_Loop_Row_DCT_Loop_proc_U0_ap_ready;
assign buf_2d_in_2_t_we0 = ap_const_logic_0;
assign buf_2d_in_2_t_we1 = ap_const_logic_0;
assign buf_2d_in_3_U_ap_dummy_ce = ap_const_logic_1;
assign buf_2d_in_3_i_address0 = dct_read_data_U0_buf_3_address0;
assign buf_2d_in_3_i_address1 = dct_read_data_U0_buf_3_address1;
assign buf_2d_in_3_i_ce0 = dct_read_data_U0_buf_3_ce0;
assign buf_2d_in_3_i_ce1 = dct_read_data_U0_buf_3_ce1;
assign buf_2d_in_3_i_d0 = dct_read_data_U0_buf_3_d0;
assign buf_2d_in_3_i_d1 = dct_read_data_U0_buf_3_d1;
assign buf_2d_in_3_i_we0 = dct_read_data_U0_buf_3_we0;
assign buf_2d_in_3_i_we1 = dct_read_data_U0_buf_3_we1;
assign buf_2d_in_3_i_write = ap_chn_write_dct_read_data_U0_buf_2d_in_3;
assign buf_2d_in_3_t_address0 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_address0;
assign buf_2d_in_3_t_address1 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_address1;
assign buf_2d_in_3_t_ce0 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_ce0;
assign buf_2d_in_3_t_ce1 = dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_ce1;
assign buf_2d_in_3_t_d0 = ap_const_lv16_0;
assign buf_2d_in_3_t_d1 = ap_const_lv16_0;
assign buf_2d_in_3_t_read = dct_Loop_Row_DCT_Loop_proc_U0_ap_ready;
assign buf_2d_in_3_t_we0 = ap_const_logic_0;
assign buf_2d_in_3_t_we1 = ap_const_logic_0;
assign buf_2d_out_U_ap_dummy_ce = ap_const_logic_1;
assign buf_2d_out_i_address0 = dct_Loop_4_proc_U0_buf_2d_out_address0;
assign buf_2d_out_i_address1 = ap_const_lv6_0;
assign buf_2d_out_i_ce0 = dct_Loop_4_proc_U0_buf_2d_out_ce0;
assign buf_2d_out_i_ce1 = ap_const_logic_0;
assign buf_2d_out_i_d0 = dct_Loop_4_proc_U0_buf_2d_out_d0;
assign buf_2d_out_i_we0 = dct_Loop_4_proc_U0_buf_2d_out_we0;
assign buf_2d_out_i_write = dct_Loop_4_proc_U0_ap_done;
assign buf_2d_out_t_address0 = dct_write_data_U0_buf_r_address0;
assign buf_2d_out_t_address1 = dct_write_data_U0_buf_r_address1;
assign buf_2d_out_t_ce0 = dct_write_data_U0_buf_r_ce0;
assign buf_2d_out_t_ce1 = dct_write_data_U0_buf_r_ce1;
assign buf_2d_out_t_d0 = ap_const_lv16_0;
assign buf_2d_out_t_d1 = ap_const_lv16_0;
assign buf_2d_out_t_read = dct_write_data_U0_ap_ready;
assign buf_2d_out_t_we0 = ap_const_logic_0;
assign buf_2d_out_t_we1 = ap_const_logic_0;
assign col_inbuf_0_U_ap_dummy_ce = ap_const_logic_1;
assign col_inbuf_0_i_address0 = dct_Loop_2_proc_U0_col_inbuf_0_address0;
assign col_inbuf_0_i_address1 = ap_const_lv4_0;
assign col_inbuf_0_i_ce0 = dct_Loop_2_proc_U0_col_inbuf_0_ce0;
assign col_inbuf_0_i_ce1 = ap_const_logic_0;
assign col_inbuf_0_i_d0 = dct_Loop_2_proc_U0_col_inbuf_0_d0;
assign col_inbuf_0_i_we0 = dct_Loop_2_proc_U0_col_inbuf_0_we0;
assign col_inbuf_0_i_write = ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_0;
assign col_inbuf_0_t_address0 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_address0;
assign col_inbuf_0_t_address1 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_address1;
assign col_inbuf_0_t_ce0 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_ce0;
assign col_inbuf_0_t_ce1 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_ce1;
assign col_inbuf_0_t_d0 = ap_const_lv16_0;
assign col_inbuf_0_t_d1 = ap_const_lv16_0;
assign col_inbuf_0_t_read = dct_Loop_Col_DCT_Loop_proc_U0_ap_ready;
assign col_inbuf_0_t_we0 = ap_const_logic_0;
assign col_inbuf_0_t_we1 = ap_const_logic_0;
assign col_inbuf_1_U_ap_dummy_ce = ap_const_logic_1;
assign col_inbuf_1_i_address0 = dct_Loop_2_proc_U0_col_inbuf_1_address0;
assign col_inbuf_1_i_address1 = ap_const_lv4_0;
assign col_inbuf_1_i_ce0 = dct_Loop_2_proc_U0_col_inbuf_1_ce0;
assign col_inbuf_1_i_ce1 = ap_const_logic_0;
assign col_inbuf_1_i_d0 = dct_Loop_2_proc_U0_col_inbuf_1_d0;
assign col_inbuf_1_i_we0 = dct_Loop_2_proc_U0_col_inbuf_1_we0;
assign col_inbuf_1_i_write = ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_1;
assign col_inbuf_1_t_address0 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_address0;
assign col_inbuf_1_t_address1 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_address1;
assign col_inbuf_1_t_ce0 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_ce0;
assign col_inbuf_1_t_ce1 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_ce1;
assign col_inbuf_1_t_d0 = ap_const_lv16_0;
assign col_inbuf_1_t_d1 = ap_const_lv16_0;
assign col_inbuf_1_t_read = dct_Loop_Col_DCT_Loop_proc_U0_ap_ready;
assign col_inbuf_1_t_we0 = ap_const_logic_0;
assign col_inbuf_1_t_we1 = ap_const_logic_0;
assign col_inbuf_2_U_ap_dummy_ce = ap_const_logic_1;
assign col_inbuf_2_i_address0 = dct_Loop_2_proc_U0_col_inbuf_2_address0;
assign col_inbuf_2_i_address1 = ap_const_lv4_0;
assign col_inbuf_2_i_ce0 = dct_Loop_2_proc_U0_col_inbuf_2_ce0;
assign col_inbuf_2_i_ce1 = ap_const_logic_0;
assign col_inbuf_2_i_d0 = dct_Loop_2_proc_U0_col_inbuf_2_d0;
assign col_inbuf_2_i_we0 = dct_Loop_2_proc_U0_col_inbuf_2_we0;
assign col_inbuf_2_i_write = ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_2;
assign col_inbuf_2_t_address0 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_address0;
assign col_inbuf_2_t_address1 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_address1;
assign col_inbuf_2_t_ce0 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_ce0;
assign col_inbuf_2_t_ce1 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_ce1;
assign col_inbuf_2_t_d0 = ap_const_lv16_0;
assign col_inbuf_2_t_d1 = ap_const_lv16_0;
assign col_inbuf_2_t_read = dct_Loop_Col_DCT_Loop_proc_U0_ap_ready;
assign col_inbuf_2_t_we0 = ap_const_logic_0;
assign col_inbuf_2_t_we1 = ap_const_logic_0;
assign col_inbuf_3_U_ap_dummy_ce = ap_const_logic_1;
assign col_inbuf_3_i_address0 = dct_Loop_2_proc_U0_col_inbuf_3_address0;
assign col_inbuf_3_i_address1 = ap_const_lv4_0;
assign col_inbuf_3_i_ce0 = dct_Loop_2_proc_U0_col_inbuf_3_ce0;
assign col_inbuf_3_i_ce1 = ap_const_logic_0;
assign col_inbuf_3_i_d0 = dct_Loop_2_proc_U0_col_inbuf_3_d0;
assign col_inbuf_3_i_we0 = dct_Loop_2_proc_U0_col_inbuf_3_we0;
assign col_inbuf_3_i_write = ap_chn_write_dct_Loop_2_proc_U0_col_inbuf_3;
assign col_inbuf_3_t_address0 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_address0;
assign col_inbuf_3_t_address1 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_address1;
assign col_inbuf_3_t_ce0 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_ce0;
assign col_inbuf_3_t_ce1 = dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_ce1;
assign col_inbuf_3_t_d0 = ap_const_lv16_0;
assign col_inbuf_3_t_d1 = ap_const_lv16_0;
assign col_inbuf_3_t_read = dct_Loop_Col_DCT_Loop_proc_U0_ap_ready;
assign col_inbuf_3_t_we0 = ap_const_logic_0;
assign col_inbuf_3_t_we1 = ap_const_logic_0;
assign col_outbuf_i_U_ap_dummy_ce = ap_const_logic_1;
assign col_outbuf_i_i_address0 = dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_address0;
assign col_outbuf_i_i_address1 = dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_address1;
assign col_outbuf_i_i_ce0 = dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_ce0;
assign col_outbuf_i_i_ce1 = dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_ce1;
assign col_outbuf_i_i_d0 = dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_d0;
assign col_outbuf_i_i_d1 = dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_d1;
assign col_outbuf_i_i_we0 = dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_we0;
assign col_outbuf_i_i_we1 = dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_we1;
assign col_outbuf_i_i_write = dct_Loop_Col_DCT_Loop_proc_U0_ap_done;
assign col_outbuf_i_t_address0 = dct_Loop_4_proc_U0_col_outbuf_i_address0;
assign col_outbuf_i_t_address1 = ap_const_lv6_0;
assign col_outbuf_i_t_ce0 = dct_Loop_4_proc_U0_col_outbuf_i_ce0;
assign col_outbuf_i_t_ce1 = ap_const_logic_0;
assign col_outbuf_i_t_d0 = ap_const_lv16_0;
assign col_outbuf_i_t_d1 = ap_const_lv16_0;
assign col_outbuf_i_t_read = dct_Loop_4_proc_U0_ap_ready;
assign col_outbuf_i_t_we0 = ap_const_logic_0;
assign col_outbuf_i_t_we1 = ap_const_logic_0;
assign dct_Loop_2_proc_U0_ap_start = row_outbuf_i_t_empty_n;
assign dct_Loop_2_proc_U0_col_inbuf_0_pipo_status = col_inbuf_0_i_full_n;
assign dct_Loop_2_proc_U0_col_inbuf_1_pipo_status = col_inbuf_1_i_full_n;
assign dct_Loop_2_proc_U0_col_inbuf_2_pipo_status = col_inbuf_2_i_full_n;
assign dct_Loop_2_proc_U0_col_inbuf_3_pipo_status = col_inbuf_3_i_full_n;
assign dct_Loop_2_proc_U0_row_outbuf_i_q0 = row_outbuf_i_t_q0;
assign dct_Loop_4_proc_U0_ap_continue = dct_Loop_4_proc_U0_buf_2d_out_pipo_status;
assign dct_Loop_4_proc_U0_ap_start = col_outbuf_i_t_empty_n;
assign dct_Loop_4_proc_U0_buf_2d_out_pipo_status = buf_2d_out_i_full_n;
assign dct_Loop_4_proc_U0_col_outbuf_i_q0 = col_outbuf_i_t_q0;
assign dct_Loop_Col_DCT_Loop_proc_U0_ap_continue = dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_pipo_status;
assign dct_Loop_Col_DCT_Loop_proc_U0_ap_start = (col_inbuf_0_t_empty_n & col_inbuf_1_t_empty_n & col_inbuf_2_t_empty_n & col_inbuf_3_t_empty_n);
assign dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_q0 = col_inbuf_0_t_q0;
assign dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_0_q1 = col_inbuf_0_t_q1;
assign dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_q0 = col_inbuf_1_t_q0;
assign dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_1_q1 = col_inbuf_1_t_q1;
assign dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_q0 = col_inbuf_2_t_q0;
assign dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_2_q1 = col_inbuf_2_t_q1;
assign dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_q0 = col_inbuf_3_t_q0;
assign dct_Loop_Col_DCT_Loop_proc_U0_col_inbuf_3_q1 = col_inbuf_3_t_q1;
assign dct_Loop_Col_DCT_Loop_proc_U0_col_outbuf_i_pipo_status = col_outbuf_i_i_full_n;
assign dct_Loop_Row_DCT_Loop_proc_U0_ap_continue = dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_pipo_status;
assign dct_Loop_Row_DCT_Loop_proc_U0_ap_start = (buf_2d_in_0_t_empty_n & buf_2d_in_1_t_empty_n & buf_2d_in_2_t_empty_n & buf_2d_in_3_t_empty_n);
assign dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_q0 = buf_2d_in_0_t_q0;
assign dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_0_q1 = buf_2d_in_0_t_q1;
assign dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_q0 = buf_2d_in_1_t_q0;
assign dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_1_q1 = buf_2d_in_1_t_q1;
assign dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_q0 = buf_2d_in_2_t_q0;
assign dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_2_q1 = buf_2d_in_2_t_q1;
assign dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_q0 = buf_2d_in_3_t_q0;
assign dct_Loop_Row_DCT_Loop_proc_U0_buf_2d_in_3_q1 = buf_2d_in_3_t_q1;
assign dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_pipo_status = row_outbuf_i_i_full_n;
assign dct_read_data_U0_ap_start = ap_start;
assign dct_read_data_U0_buf_0_pipo_status = buf_2d_in_0_i_full_n;
assign dct_read_data_U0_buf_1_pipo_status = buf_2d_in_1_i_full_n;
assign dct_read_data_U0_buf_2_pipo_status = buf_2d_in_2_i_full_n;
assign dct_read_data_U0_buf_3_pipo_status = buf_2d_in_3_i_full_n;
assign dct_read_data_U0_input_r_q0 = input_r_q0;
assign dct_read_data_U0_input_r_q1 = input_r_q1;
assign dct_write_data_U0_ap_continue = ap_sig_hs_continue;
assign dct_write_data_U0_ap_start = buf_2d_out_t_empty_n;
assign dct_write_data_U0_buf_r_q0 = buf_2d_out_t_q0;
assign dct_write_data_U0_buf_r_q1 = buf_2d_out_t_q1;
assign input_r_address0 = dct_read_data_U0_input_r_address0;
assign input_r_address1 = dct_read_data_U0_input_r_address1;
assign input_r_ce0 = dct_read_data_U0_input_r_ce0;
assign input_r_ce1 = dct_read_data_U0_input_r_ce1;
assign input_r_d0 = ap_const_lv16_0;
assign input_r_d1 = ap_const_lv16_0;
assign input_r_we0 = ap_const_logic_0;
assign input_r_we1 = ap_const_logic_0;
assign output_r_address0 = dct_write_data_U0_output_r_address0;
assign output_r_address1 = dct_write_data_U0_output_r_address1;
assign output_r_ce0 = dct_write_data_U0_output_r_ce0;
assign output_r_ce1 = dct_write_data_U0_output_r_ce1;
assign output_r_d0 = dct_write_data_U0_output_r_d0;
assign output_r_d1 = dct_write_data_U0_output_r_d1;
assign output_r_we0 = dct_write_data_U0_output_r_we0;
assign output_r_we1 = dct_write_data_U0_output_r_we1;
assign row_outbuf_i_U_ap_dummy_ce = ap_const_logic_1;
assign row_outbuf_i_i_address0 = dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_address0;
assign row_outbuf_i_i_address1 = dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_address1;
assign row_outbuf_i_i_ce0 = dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_ce0;
assign row_outbuf_i_i_ce1 = dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_ce1;
assign row_outbuf_i_i_d0 = dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_d0;
assign row_outbuf_i_i_d1 = dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_d1;
assign row_outbuf_i_i_we0 = dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_we0;
assign row_outbuf_i_i_we1 = dct_Loop_Row_DCT_Loop_proc_U0_row_outbuf_i_we1;
assign row_outbuf_i_i_write = dct_Loop_Row_DCT_Loop_proc_U0_ap_done;
assign row_outbuf_i_t_address0 = dct_Loop_2_proc_U0_row_outbuf_i_address0;
assign row_outbuf_i_t_address1 = ap_const_lv6_0;
assign row_outbuf_i_t_ce0 = dct_Loop_2_proc_U0_row_outbuf_i_ce0;
assign row_outbuf_i_t_ce1 = ap_const_logic_0;
assign row_outbuf_i_t_d0 = ap_const_lv16_0;
assign row_outbuf_i_t_d1 = ap_const_lv16_0;
assign row_outbuf_i_t_read = dct_Loop_2_proc_U0_ap_ready;
assign row_outbuf_i_t_we0 = ap_const_logic_0;
assign row_outbuf_i_t_we1 = ap_const_logic_0;


endmodule //dct

