<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="11">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>dct_Loop_Col_DCT_Loop_proc</name>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>5</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>col_inbuf_0</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName>RAM</coreName>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>1</if_type>
          <array_size>16</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>col_inbuf_1</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName>RAM</coreName>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>1</if_type>
          <array_size>16</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_3">
          <Value>
            <Obj>
              <type>1</type>
              <id>3</id>
              <name>col_inbuf_2</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName>RAM</coreName>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>1</if_type>
          <array_size>16</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_4">
          <Value>
            <Obj>
              <type>1</type>
              <id>4</id>
              <name>col_inbuf_3</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName>RAM</coreName>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>1</if_type>
          <array_size>16</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_5">
          <Value>
            <Obj>
              <type>1</type>
              <id>5</id>
              <name>col_outbuf_i</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName>RAM</coreName>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>1</if_type>
          <array_size>64</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>8</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>6</id>
              <name/>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>23</item>
          </oprand_edges>
          <opcode>br</opcode>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>8</id>
              <name>i_2_i</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>i</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>24</item>
            <item>25</item>
            <item>27</item>
            <item>28</item>
          </oprand_edges>
          <opcode>phi</opcode>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>9</id>
              <name>exitcond2_i</name>
              <fileName>dct.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>84</lineNumber>
              <contextFuncName>dct_2d</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="11" tracking_level="0" version="0">
                  <first>/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1</first>
                  <second class_id="12" tracking_level="0" version="0">
                    <count>2</count>
                    <item_version>0</item_version>
                    <item class_id="13" tracking_level="0" version="0">
                      <first class_id="14" tracking_level="0" version="0">
                        <first>dct.cpp</first>
                        <second>dct</second>
                      </first>
                      <second>139</second>
                    </item>
                    <item>
                      <first>
                        <first>dct.cpp</first>
                        <second>dct_2d</second>
                      </first>
                      <second>84</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>exitcond2_i_fu_68_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>29</item>
            <item>31</item>
          </oprand_edges>
          <opcode>icmp</opcode>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>10</id>
              <name>i</name>
              <fileName>dct.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>84</lineNumber>
              <contextFuncName>dct_2d</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>dct.cpp</first>
                        <second>dct</second>
                      </first>
                      <second>139</second>
                    </item>
                    <item>
                      <first>
                        <first>dct.cpp</first>
                        <second>dct_2d</second>
                      </first>
                      <second>84</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>i</originalName>
              <rtlName>i_fu_74_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>32</item>
            <item>34</item>
          </oprand_edges>
          <opcode>add</opcode>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>11</id>
              <name/>
              <fileName>dct.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>84</lineNumber>
              <contextFuncName>dct_2d</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>dct.cpp</first>
                        <second>dct</second>
                      </first>
                      <second>139</second>
                    </item>
                    <item>
                      <first>
                        <first>dct.cpp</first>
                        <second>dct_2d</second>
                      </first>
                      <second>84</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>35</item>
            <item>36</item>
            <item>37</item>
          </oprand_edges>
          <opcode>br</opcode>
        </item>
        <item class_id_reference="9" object_id="_11">
          <Value>
            <Obj>
              <type>0</type>
              <id>17</id>
              <name/>
              <fileName>dct.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>85</lineNumber>
              <contextFuncName>dct_2d</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>dct.cpp</first>
                        <second>dct</second>
                      </first>
                      <second>139</second>
                    </item>
                    <item>
                      <first>
                        <first>dct.cpp</first>
                        <second>dct_2d</second>
                      </first>
                      <second>85</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>grp_dct_dct_1d_fu_50</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>8</count>
            <item_version>0</item_version>
            <item>39</item>
            <item>40</item>
            <item>41</item>
            <item>42</item>
            <item>43</item>
            <item>44</item>
            <item>45</item>
            <item>46</item>
          </oprand_edges>
          <opcode>call</opcode>
        </item>
        <item class_id_reference="9" object_id="_12">
          <Value>
            <Obj>
              <type>0</type>
              <id>19</id>
              <name/>
              <fileName>dct.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>84</lineNumber>
              <contextFuncName>dct_2d</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>dct.cpp</first>
                        <second>dct</second>
                      </first>
                      <second>139</second>
                    </item>
                    <item>
                      <first>
                        <first>dct.cpp</first>
                        <second>dct_2d</second>
                      </first>
                      <second>84</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>47</item>
          </oprand_edges>
          <opcode>br</opcode>
        </item>
        <item class_id_reference="9" object_id="_13">
          <Value>
            <Obj>
              <type>0</type>
              <id>21</id>
              <name/>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>ret</opcode>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_14">
          <Value>
            <Obj>
              <type>2</type>
              <id>26</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
        <item class_id_reference="16" object_id="_15">
          <Value>
            <Obj>
              <type>2</type>
              <id>30</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>8</content>
        </item>
        <item class_id_reference="16" object_id="_16">
          <Value>
            <Obj>
              <type>2</type>
              <id>33</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_17">
          <Value>
            <Obj>
              <type>2</type>
              <id>38</id>
              <name>dct_dct_1d</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:dct_dct_1d&gt;</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_18">
          <Obj>
            <type>3</type>
            <id>7</id>
            <name>newFuncRoot</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>1</count>
            <item_version>0</item_version>
            <item>6</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_19">
          <Obj>
            <type>3</type>
            <id>12</id>
            <name>.preheader7.i</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>4</count>
            <item_version>0</item_version>
            <item>8</item>
            <item>9</item>
            <item>10</item>
            <item>11</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_20">
          <Obj>
            <type>3</type>
            <id>20</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>2</count>
            <item_version>0</item_version>
            <item>17</item>
            <item>19</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_21">
          <Obj>
            <type>3</type>
            <id>22</id>
            <name>.preheader6.i.exitStub</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>1</count>
            <item_version>0</item_version>
            <item>21</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>25</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_22">
          <id>23</id>
          <edge_type>2</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>6</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_23">
          <id>24</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>8</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_24">
          <id>25</id>
          <edge_type>2</edge_type>
          <source_obj>20</source_obj>
          <sink_obj>8</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_25">
          <id>27</id>
          <edge_type>1</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>8</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_26">
          <id>28</id>
          <edge_type>2</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>8</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_27">
          <id>29</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>9</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>31</id>
          <edge_type>1</edge_type>
          <source_obj>30</source_obj>
          <sink_obj>9</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>32</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>10</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_30">
          <id>34</id>
          <edge_type>1</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>10</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>35</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>11</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>36</id>
          <edge_type>2</edge_type>
          <source_obj>20</source_obj>
          <sink_obj>11</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>37</id>
          <edge_type>2</edge_type>
          <source_obj>22</source_obj>
          <sink_obj>11</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>39</id>
          <edge_type>1</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>17</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>40</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>17</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>41</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>17</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>42</id>
          <edge_type>1</edge_type>
          <source_obj>3</source_obj>
          <sink_obj>17</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>43</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>17</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>44</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>17</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>45</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>17</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>46</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>17</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>47</id>
          <edge_type>2</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>19</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>75</id>
          <edge_type>2</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>12</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>76</id>
          <edge_type>2</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>22</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>77</id>
          <edge_type>2</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>20</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>78</id>
          <edge_type>2</edge_type>
          <source_obj>20</source_obj>
          <sink_obj>12</sink_obj>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_47">
        <mId>1</mId>
        <mTag>dct_Loop_Col_DCT_Loop_proc</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>3</count>
          <item_version>0</item_version>
          <item>2</item>
          <item>3</item>
          <item>4</item>
        </sub_regions>
        <basic_blocks>
          <count>0</count>
          <item_version>0</item_version>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>39</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_48">
        <mId>2</mId>
        <mTag>Entry</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_49">
        <mId>3</mId>
        <mTag>Col_DCT_Loop</mTag>
        <mType>1</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>2</count>
          <item_version>0</item_version>
          <item>12</item>
          <item>20</item>
        </basic_blocks>
        <mII>4</mII>
        <mDepth>10</mDepth>
        <mMinTripCount>8</mMinTripCount>
        <mMaxTripCount>8</mMaxTripCount>
        <mMinLatency>37</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_50">
        <mId>4</mId>
        <mTag>Return</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>22</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_51">
      <states class_id="25" tracking_level="0" version="0">
        <count>12</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_52">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>1</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_53">
              <id>6</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_54">
          <id>2</id>
          <operations>
            <count>4</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_55">
              <id>8</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_56">
              <id>9</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_57">
              <id>10</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_58">
              <id>11</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_59">
          <id>3</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_60">
              <id>17</id>
              <stage>9</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_61">
          <id>4</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_62">
              <id>17</id>
              <stage>8</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_63">
          <id>5</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_64">
              <id>17</id>
              <stage>7</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_65">
          <id>6</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_66">
              <id>17</id>
              <stage>6</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_67">
          <id>7</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_68">
              <id>17</id>
              <stage>5</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_69">
          <id>8</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_70">
              <id>17</id>
              <stage>4</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_71">
          <id>9</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_72">
              <id>17</id>
              <stage>3</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_73">
          <id>10</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_74">
              <id>17</id>
              <stage>2</stage>
              <latency>9</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_75">
          <id>11</id>
          <operations>
            <count>7</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_76">
              <id>13</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_77">
              <id>14</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_78">
              <id>15</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_79">
              <id>16</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_80">
              <id>17</id>
              <stage>1</stage>
              <latency>9</latency>
            </item>
            <item class_id_reference="28" object_id="_81">
              <id>18</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_82">
              <id>19</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_83">
          <id>12</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_84">
              <id>21</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>12</count>
        <item_version>0</item_version>
        <item class_id="30" tracking_level="1" version="0" object_id="_85">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="31" tracking_level="0" version="0">
            <id>12</id>
            <sop class_id="32" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="33" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_86">
          <inState>3</inState>
          <outState>4</outState>
          <condition>
            <id>27</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_87">
          <inState>4</inState>
          <outState>5</outState>
          <condition>
            <id>28</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_88">
          <inState>5</inState>
          <outState>6</outState>
          <condition>
            <id>29</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_89">
          <inState>6</inState>
          <outState>7</outState>
          <condition>
            <id>30</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_90">
          <inState>7</inState>
          <outState>8</outState>
          <condition>
            <id>31</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_91">
          <inState>8</inState>
          <outState>9</outState>
          <condition>
            <id>32</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_92">
          <inState>9</inState>
          <outState>10</outState>
          <condition>
            <id>33</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_93">
          <inState>10</inState>
          <outState>11</outState>
          <condition>
            <id>34</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_94">
          <inState>11</inState>
          <outState>2</outState>
          <condition>
            <id>35</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_95">
          <inState>2</inState>
          <outState>12</outState>
          <condition>
            <id>26</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="34" tracking_level="0" version="0">
                  <first class_id="35" tracking_level="0" version="0">
                    <first>9</first>
                    <second>0</second>
                  </first>
                  <second>0</second>
                </item>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_96">
          <inState>2</inState>
          <outState>3</outState>
          <condition>
            <id>36</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>
                    <first>9</first>
                    <second>0</second>
                  </first>
                  <second>1</second>
                </item>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="36" tracking_level="1" version="0" object_id="_97">
      <dp_component_resource class_id="37" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="38" tracking_level="0" version="0">
          <first>grp_dct_dct_1d_fu_50 (dct_dct_1d)</first>
          <second class_id="39" tracking_level="0" version="0">
            <count>3</count>
            <item_version>0</item_version>
            <item class_id="40" tracking_level="0" version="0">
              <first>DSP48E</first>
              <second>48</second>
            </item>
            <item>
              <first>FF</first>
              <second>1248</second>
            </item>
            <item>
              <first>LUT</first>
              <second>782</second>
            </item>
          </second>
        </item>
      </dp_component_resource>
      <dp_expression_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>ap_sig_bdd_107 ( or ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>exitcond2_i_fu_68_p2 ( icmp ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>4</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>5</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>i_fu_74_p2 ( + ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>4</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>4</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>16</count>
        <item_version>0</item_version>
        <item>
          <first>ap_NS_fsm</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>7</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>7</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_reg_ppiten_pp0_it2</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_inbuf_0_ce0</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_inbuf_0_ce1</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_inbuf_1_ce0</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_inbuf_1_ce1</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_inbuf_2_ce0</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_inbuf_2_ce1</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_inbuf_3_ce0</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_inbuf_3_ce1</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_outbuf_i_ce0</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_outbuf_i_ce1</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_outbuf_i_we0</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>col_outbuf_i_we1</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>i_2_i_phi_fu_42_p4</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>4</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>8</second>
            </item>
            <item>
              <first>LUT</first>
              <second>4</second>
            </item>
          </second>
        </item>
        <item>
          <first>i_2_i_reg_38</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>4</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>8</second>
            </item>
            <item>
              <first>LUT</first>
              <second>4</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>9</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>6</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>6</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_done_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_reg_ppiten_pp0_it0</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_reg_ppiten_pp0_it1</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_reg_ppiten_pp0_it2</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>exitcond2_i_reg_80</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>grp_dct_dct_1d_fu_50_ap_start_ap_start_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>i_2_i_reg_38</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>4</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>4</second>
            </item>
          </second>
        </item>
        <item>
          <first>i_reg_84</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>4</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>4</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_component_map class_id="41" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="42" tracking_level="0" version="0">
          <first>grp_dct_dct_1d_fu_50 (dct_dct_1d)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>17</item>
          </second>
        </item>
      </dp_component_map>
      <dp_expression_map>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>exitcond2_i_fu_68_p2 ( icmp ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>9</item>
          </second>
        </item>
        <item>
          <first>i_fu_74_p2 ( + ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>10</item>
          </second>
        </item>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="43" tracking_level="0" version="0">
      <count>8</count>
      <item_version>0</item_version>
      <item class_id="44" tracking_level="0" version="0">
        <first>6</first>
        <second class_id="45" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>8</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>9</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>10</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>11</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>17</first>
        <second>
          <first>2</first>
          <second>8</second>
        </second>
      </item>
      <item>
        <first>19</first>
        <second>
          <first>10</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>21</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="46" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="47" tracking_level="0" version="0">
        <first>7</first>
        <second class_id="48" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>12</first>
        <second>
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>20</first>
        <second>
          <first>2</first>
          <second>10</second>
        </second>
      </item>
      <item>
        <first>22</first>
        <second>
          <first>2</first>
          <second>2</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="49" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="50" tracking_level="1" version="0" object_id="_98">
        <region_name>Col_DCT_Loop</region_name>
        <basic_blocks>
          <count>2</count>
          <item_version>0</item_version>
          <item>12</item>
          <item>20</item>
        </basic_blocks>
        <nodes>
          <count>0</count>
          <item_version>0</item_version>
        </nodes>
        <anchor_node>-1</anchor_node>
        <region_type>8</region_type>
        <interval>4</interval>
        <pipe_depth>10</pipe_depth>
      </item>
    </regions>
    <dp_fu_nodes class_id="51" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="52" tracking_level="0" version="0">
        <first>42</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>50</first>
        <second>
          <count>9</count>
          <item_version>0</item_version>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>68</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
      <item>
        <first>74</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="54" tracking_level="0" version="0">
      <count>3</count>
      <item_version>0</item_version>
      <item class_id="55" tracking_level="0" version="0">
        <first>exitcond2_i_fu_68</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
      <item>
        <first>i_2_i_phi_fu_42</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>i_fu_74</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>grp_dct_dct_1d_fu_50</first>
        <second>
          <count>9</count>
          <item_version>0</item_version>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
          <item>17</item>
        </second>
      </item>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="56" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>38</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>80</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
      <item>
        <first>84</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>exitcond2_i_reg_80</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
      <item>
        <first>i_2_i_reg_38</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>i_reg_84</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>38</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>i_2_i_reg_38</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="57" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_port_io_nodes>
    <port2core class_id="58" tracking_level="0" version="0">
      <count>5</count>
      <item_version>0</item_version>
      <item class_id="59" tracking_level="0" version="0">
        <first>1</first>
        <second>RAM</second>
      </item>
      <item>
        <first>2</first>
        <second>RAM</second>
      </item>
      <item>
        <first>3</first>
        <second>RAM</second>
      </item>
      <item>
        <first>4</first>
        <second>RAM</second>
      </item>
      <item>
        <first>5</first>
        <second>RAM</second>
      </item>
    </port2core>
    <node2core>
      <count>0</count>
      <item_version>0</item_version>
    </node2core>
  </syndb>
</boost_serialization>
