lappend pragmaStatus0 {pragma "UNROLL" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "dct_1d/DCT_Inner_Loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "PIPELINE" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "dct_1d/DCT_Outer_Loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "ARRAY_PARTITION" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "dct_2d" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "col_inbuf"}
lappend pragmaStatus3 {pragma "ARRAY_PARTITION" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "dct" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "buf_2d_in"}
lappend pragmaStatus4 {pragma "DATAFLOW" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "dct" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "INLINE" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "dct_2d" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "PIPELINE" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "read_data/RD_Loop_Row" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "PIPELINE" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "write_data/WR_Loop_Row" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "PIPELINE" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "dct_2d/Xpose_Row_Inner_Loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "PIPELINE" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "dct_2d/Xpose_Col_Inner_Loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "PIPELINE" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "dct_2d/Row_DCT_Loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "PIPELINE" source "/home/ctnguyen/work/tut_vivadohls/Vivado_HLS_Tutorial/Design_Analysis/lab1/dct.cpp" location "dct_2d/Col_DCT_Loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
