// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _hls_real2xfft_HH_
#define _hls_real2xfft_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "hls_real2xfft_Loop_sliding_win_delay_proc.h"
#include "hls_real2xfft_Loop_sliding_win_output_proc.h"
#include "hls_real2xfft_window_fn.h"
#include "hls_real2xfft_Loop_real2xfft_output_proc.h"
#include "FIFO_hls_real2xfft_delayed_i_0_channel.h"
#include "FIFO_hls_real2xfft_delayed_i_1_channel.h"
#include "FIFO_hls_real2xfft_nodelay_i_0_channel.h"
#include "FIFO_hls_real2xfft_nodelay_i_1_channel.h"
#include "FIFO_hls_real2xfft_data2window_1_channel.h"
#include "FIFO_hls_real2xfft_data2window_0_channel.h"
#include "FIFO_hls_real2xfft_windowed_0_channel.h"
#include "FIFO_hls_real2xfft_windowed_1_channel.h"

namespace ap_rtl {

struct hls_real2xfft : public sc_module {
    // Port declarations 13
    sc_in< sc_lv<16> > din_V_V_TDATA;
    sc_out< sc_lv<32> > dout_TDATA;
    sc_out< sc_lv<1> > dout_TLAST;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > din_V_V_TVALID;
    sc_out< sc_logic > din_V_V_TREADY;
    sc_out< sc_logic > dout_TVALID;
    sc_in< sc_logic > dout_TREADY;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;


    // Module declarations
    hls_real2xfft(sc_module_name name);
    SC_HAS_PROCESS(hls_real2xfft);

    ~hls_real2xfft();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    hls_real2xfft_Loop_sliding_win_delay_proc* hls_real2xfft_Loop_sliding_win_delay_proc_U0;
    hls_real2xfft_Loop_sliding_win_output_proc* hls_real2xfft_Loop_sliding_win_output_proc_U0;
    hls_real2xfft_window_fn* hls_real2xfft_window_fn_U0;
    hls_real2xfft_Loop_real2xfft_output_proc* hls_real2xfft_Loop_real2xfft_output_proc_U0;
    FIFO_hls_real2xfft_delayed_i_0_channel* delayed_i_0_channel_U;
    FIFO_hls_real2xfft_delayed_i_1_channel* delayed_i_1_channel_U;
    FIFO_hls_real2xfft_nodelay_i_0_channel* nodelay_i_0_channel_U;
    FIFO_hls_real2xfft_nodelay_i_1_channel* nodelay_i_1_channel_U;
    FIFO_hls_real2xfft_data2window_1_channel* data2window_1_channel_U;
    FIFO_hls_real2xfft_data2window_0_channel* data2window_0_channel_U;
    FIFO_hls_real2xfft_windowed_0_channel* windowed_0_channel_U;
    FIFO_hls_real2xfft_windowed_1_channel* windowed_1_channel_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_ap_start;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_ap_done;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_ap_continue;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_ap_idle;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_ap_ready;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_din_V_V_TVALID;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_sliding_win_delay_proc_U0_nodelay_i_0_din;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_nodelay_i_0_full_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_nodelay_i_0_write;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_sliding_win_delay_proc_U0_nodelay_i_1_din;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_nodelay_i_1_full_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_nodelay_i_1_write;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_sliding_win_delay_proc_U0_delayed_i_0_din;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_delayed_i_0_full_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_delayed_i_0_write;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_sliding_win_delay_proc_U0_delayed_i_1_din;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_delayed_i_1_full_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_delayed_i_1_write;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_sliding_win_delay_proc_U0_din_V_V_TDATA;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_delay_proc_U0_din_V_V_TREADY;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_ap_start;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_ap_done;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_ap_continue;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_ap_idle;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_ap_ready;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_sliding_win_output_proc_U0_delayed_i_0_dout;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_delayed_i_0_empty_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_delayed_i_0_read;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_sliding_win_output_proc_U0_nodelay_i_0_dout;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_nodelay_i_0_empty_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_nodelay_i_0_read;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_sliding_win_output_proc_U0_delayed_i_1_dout;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_delayed_i_1_empty_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_delayed_i_1_read;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_sliding_win_output_proc_U0_nodelay_i_1_dout;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_nodelay_i_1_empty_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_nodelay_i_1_read;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_sliding_win_output_proc_U0_data2window_0_din;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_data2window_0_full_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_data2window_0_write;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_sliding_win_output_proc_U0_data2window_1_din;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_data2window_1_full_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_sliding_win_output_proc_U0_data2window_1_write;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_ap_start;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_ap_done;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_ap_continue;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_ap_idle;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_ap_ready;
    sc_signal< sc_lv<16> > hls_real2xfft_window_fn_U0_indata_0_V_dout;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_indata_0_V_empty_n;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_indata_0_V_read;
    sc_signal< sc_lv<16> > hls_real2xfft_window_fn_U0_indata_1_V_dout;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_indata_1_V_empty_n;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_indata_1_V_read;
    sc_signal< sc_lv<16> > hls_real2xfft_window_fn_U0_outdata_0_V_din;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_outdata_0_V_full_n;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_outdata_0_V_write;
    sc_signal< sc_lv<16> > hls_real2xfft_window_fn_U0_outdata_1_V_din;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_outdata_1_V_full_n;
    sc_signal< sc_logic > hls_real2xfft_window_fn_U0_outdata_1_V_write;
    sc_signal< sc_logic > hls_real2xfft_Loop_real2xfft_output_proc_U0_ap_start;
    sc_signal< sc_logic > hls_real2xfft_Loop_real2xfft_output_proc_U0_ap_done;
    sc_signal< sc_logic > hls_real2xfft_Loop_real2xfft_output_proc_U0_ap_continue;
    sc_signal< sc_logic > hls_real2xfft_Loop_real2xfft_output_proc_U0_ap_idle;
    sc_signal< sc_logic > hls_real2xfft_Loop_real2xfft_output_proc_U0_ap_ready;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_real2xfft_output_proc_U0_windowed_0_dout;
    sc_signal< sc_logic > hls_real2xfft_Loop_real2xfft_output_proc_U0_windowed_0_empty_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_real2xfft_output_proc_U0_windowed_0_read;
    sc_signal< sc_lv<16> > hls_real2xfft_Loop_real2xfft_output_proc_U0_windowed_1_dout;
    sc_signal< sc_logic > hls_real2xfft_Loop_real2xfft_output_proc_U0_windowed_1_empty_n;
    sc_signal< sc_logic > hls_real2xfft_Loop_real2xfft_output_proc_U0_windowed_1_read;
    sc_signal< sc_lv<32> > hls_real2xfft_Loop_real2xfft_output_proc_U0_dout_TDATA;
    sc_signal< sc_logic > hls_real2xfft_Loop_real2xfft_output_proc_U0_dout_TVALID;
    sc_signal< sc_logic > hls_real2xfft_Loop_real2xfft_output_proc_U0_dout_TREADY;
    sc_signal< sc_lv<1> > hls_real2xfft_Loop_real2xfft_output_proc_U0_dout_TLAST;
    sc_signal< sc_logic > ap_sig_hs_continue;
    sc_signal< sc_logic > delayed_i_0_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<16> > delayed_i_0_channel_din;
    sc_signal< sc_logic > delayed_i_0_channel_full_n;
    sc_signal< sc_logic > delayed_i_0_channel_write;
    sc_signal< sc_lv<16> > delayed_i_0_channel_dout;
    sc_signal< sc_logic > delayed_i_0_channel_empty_n;
    sc_signal< sc_logic > delayed_i_0_channel_read;
    sc_signal< sc_logic > delayed_i_1_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<16> > delayed_i_1_channel_din;
    sc_signal< sc_logic > delayed_i_1_channel_full_n;
    sc_signal< sc_logic > delayed_i_1_channel_write;
    sc_signal< sc_lv<16> > delayed_i_1_channel_dout;
    sc_signal< sc_logic > delayed_i_1_channel_empty_n;
    sc_signal< sc_logic > delayed_i_1_channel_read;
    sc_signal< sc_logic > nodelay_i_0_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<16> > nodelay_i_0_channel_din;
    sc_signal< sc_logic > nodelay_i_0_channel_full_n;
    sc_signal< sc_logic > nodelay_i_0_channel_write;
    sc_signal< sc_lv<16> > nodelay_i_0_channel_dout;
    sc_signal< sc_logic > nodelay_i_0_channel_empty_n;
    sc_signal< sc_logic > nodelay_i_0_channel_read;
    sc_signal< sc_logic > nodelay_i_1_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<16> > nodelay_i_1_channel_din;
    sc_signal< sc_logic > nodelay_i_1_channel_full_n;
    sc_signal< sc_logic > nodelay_i_1_channel_write;
    sc_signal< sc_lv<16> > nodelay_i_1_channel_dout;
    sc_signal< sc_logic > nodelay_i_1_channel_empty_n;
    sc_signal< sc_logic > nodelay_i_1_channel_read;
    sc_signal< sc_logic > data2window_1_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<16> > data2window_1_channel_din;
    sc_signal< sc_logic > data2window_1_channel_full_n;
    sc_signal< sc_logic > data2window_1_channel_write;
    sc_signal< sc_lv<16> > data2window_1_channel_dout;
    sc_signal< sc_logic > data2window_1_channel_empty_n;
    sc_signal< sc_logic > data2window_1_channel_read;
    sc_signal< sc_logic > data2window_0_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<16> > data2window_0_channel_din;
    sc_signal< sc_logic > data2window_0_channel_full_n;
    sc_signal< sc_logic > data2window_0_channel_write;
    sc_signal< sc_lv<16> > data2window_0_channel_dout;
    sc_signal< sc_logic > data2window_0_channel_empty_n;
    sc_signal< sc_logic > data2window_0_channel_read;
    sc_signal< sc_logic > windowed_0_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<16> > windowed_0_channel_din;
    sc_signal< sc_logic > windowed_0_channel_full_n;
    sc_signal< sc_logic > windowed_0_channel_write;
    sc_signal< sc_lv<16> > windowed_0_channel_dout;
    sc_signal< sc_logic > windowed_0_channel_empty_n;
    sc_signal< sc_logic > windowed_0_channel_read;
    sc_signal< sc_logic > windowed_1_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<16> > windowed_1_channel_din;
    sc_signal< sc_logic > windowed_1_channel_full_n;
    sc_signal< sc_logic > windowed_1_channel_write;
    sc_signal< sc_lv<16> > windowed_1_channel_dout;
    sc_signal< sc_logic > windowed_1_channel_empty_n;
    sc_signal< sc_logic > windowed_1_channel_read;
    sc_signal< sc_logic > ap_reg_procdone_hls_real2xfft_Loop_sliding_win_delay_proc_U0;
    sc_signal< sc_logic > ap_sig_hs_done;
    sc_signal< sc_logic > ap_reg_procdone_hls_real2xfft_Loop_sliding_win_output_proc_U0;
    sc_signal< sc_logic > ap_reg_procdone_hls_real2xfft_window_fn_U0;
    sc_signal< sc_logic > ap_reg_procdone_hls_real2xfft_Loop_real2xfft_output_proc_U0;
    sc_signal< sc_logic > ap_CS;
    sc_signal< sc_logic > ap_sig_top_allready;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_true;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_hs_continue();
    void thread_ap_sig_hs_done();
    void thread_ap_sig_top_allready();
    void thread_data2window_0_channel_U_ap_dummy_ce();
    void thread_data2window_0_channel_din();
    void thread_data2window_0_channel_read();
    void thread_data2window_0_channel_write();
    void thread_data2window_1_channel_U_ap_dummy_ce();
    void thread_data2window_1_channel_din();
    void thread_data2window_1_channel_read();
    void thread_data2window_1_channel_write();
    void thread_delayed_i_0_channel_U_ap_dummy_ce();
    void thread_delayed_i_0_channel_din();
    void thread_delayed_i_0_channel_read();
    void thread_delayed_i_0_channel_write();
    void thread_delayed_i_1_channel_U_ap_dummy_ce();
    void thread_delayed_i_1_channel_din();
    void thread_delayed_i_1_channel_read();
    void thread_delayed_i_1_channel_write();
    void thread_din_V_V_TREADY();
    void thread_dout_TDATA();
    void thread_dout_TLAST();
    void thread_dout_TVALID();
    void thread_hls_real2xfft_Loop_real2xfft_output_proc_U0_ap_continue();
    void thread_hls_real2xfft_Loop_real2xfft_output_proc_U0_dout_TREADY();
    void thread_hls_real2xfft_Loop_real2xfft_output_proc_U0_windowed_0_dout();
    void thread_hls_real2xfft_Loop_real2xfft_output_proc_U0_windowed_0_empty_n();
    void thread_hls_real2xfft_Loop_real2xfft_output_proc_U0_windowed_1_dout();
    void thread_hls_real2xfft_Loop_real2xfft_output_proc_U0_windowed_1_empty_n();
    void thread_hls_real2xfft_Loop_sliding_win_delay_proc_U0_ap_continue();
    void thread_hls_real2xfft_Loop_sliding_win_delay_proc_U0_ap_start();
    void thread_hls_real2xfft_Loop_sliding_win_delay_proc_U0_delayed_i_0_full_n();
    void thread_hls_real2xfft_Loop_sliding_win_delay_proc_U0_delayed_i_1_full_n();
    void thread_hls_real2xfft_Loop_sliding_win_delay_proc_U0_din_V_V_TDATA();
    void thread_hls_real2xfft_Loop_sliding_win_delay_proc_U0_din_V_V_TVALID();
    void thread_hls_real2xfft_Loop_sliding_win_delay_proc_U0_nodelay_i_0_full_n();
    void thread_hls_real2xfft_Loop_sliding_win_delay_proc_U0_nodelay_i_1_full_n();
    void thread_hls_real2xfft_Loop_sliding_win_output_proc_U0_ap_continue();
    void thread_hls_real2xfft_Loop_sliding_win_output_proc_U0_data2window_0_full_n();
    void thread_hls_real2xfft_Loop_sliding_win_output_proc_U0_data2window_1_full_n();
    void thread_hls_real2xfft_Loop_sliding_win_output_proc_U0_delayed_i_0_dout();
    void thread_hls_real2xfft_Loop_sliding_win_output_proc_U0_delayed_i_0_empty_n();
    void thread_hls_real2xfft_Loop_sliding_win_output_proc_U0_delayed_i_1_dout();
    void thread_hls_real2xfft_Loop_sliding_win_output_proc_U0_delayed_i_1_empty_n();
    void thread_hls_real2xfft_Loop_sliding_win_output_proc_U0_nodelay_i_0_dout();
    void thread_hls_real2xfft_Loop_sliding_win_output_proc_U0_nodelay_i_0_empty_n();
    void thread_hls_real2xfft_Loop_sliding_win_output_proc_U0_nodelay_i_1_dout();
    void thread_hls_real2xfft_Loop_sliding_win_output_proc_U0_nodelay_i_1_empty_n();
    void thread_hls_real2xfft_window_fn_U0_ap_continue();
    void thread_hls_real2xfft_window_fn_U0_indata_0_V_dout();
    void thread_hls_real2xfft_window_fn_U0_indata_0_V_empty_n();
    void thread_hls_real2xfft_window_fn_U0_indata_1_V_dout();
    void thread_hls_real2xfft_window_fn_U0_indata_1_V_empty_n();
    void thread_hls_real2xfft_window_fn_U0_outdata_0_V_full_n();
    void thread_hls_real2xfft_window_fn_U0_outdata_1_V_full_n();
    void thread_nodelay_i_0_channel_U_ap_dummy_ce();
    void thread_nodelay_i_0_channel_din();
    void thread_nodelay_i_0_channel_read();
    void thread_nodelay_i_0_channel_write();
    void thread_nodelay_i_1_channel_U_ap_dummy_ce();
    void thread_nodelay_i_1_channel_din();
    void thread_nodelay_i_1_channel_read();
    void thread_nodelay_i_1_channel_write();
    void thread_windowed_0_channel_U_ap_dummy_ce();
    void thread_windowed_0_channel_din();
    void thread_windowed_0_channel_read();
    void thread_windowed_0_channel_write();
    void thread_windowed_1_channel_U_ap_dummy_ce();
    void thread_windowed_1_channel_din();
    void thread_windowed_1_channel_read();
    void thread_windowed_1_channel_write();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
